CPLP-1134 Add Notification
catenax-ng/product-portal-backend pull request #110
Opened 2022-07-01 07:59 UTC by Phil91

✅  Add Notification incl. NotificationStatus & NotificationType
✅ Add migration
⬜ Edit database scripts

2022-07-04 11:34 UTC, jjeroch commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220704105649_CPLP-1134-AddNotification.cs
> +                    company_user_id = table.Column<Guid>(type: "uuid", nullable: false),
@Phil91 since we have the creator_id and the company_user_id. My proposal is to make the difference between those two more clear by calling them

- receiver_user_id
- creator_user_id

2022-07-04 11:34 UTC, jjeroch commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Notification.cs
> +    /// <param name="companyUserId">Mapping to the company user</param>
might change depending on our discussion above.

2022-07-04 11:52 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220704105649_CPLP-1134-AddNotification.cs
> +                    company_user_id = table.Column<Guid>(type: "uuid", nullable: false),
changed the naming of the user properties

2022-07-04 11:52 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Notification.cs
> +    /// <param name="companyUserId">Mapping to the company user</param>
changed the comment

2022-07-08 05:45 UTC, Phil91 commented
> @Phil91 Looks good to me! But the trivy scan is still failing https://github.com/catenax-ng/product-portal-backend/actions/runs/2630347468, I assume that is because an old image (not using the alpine base image yet) is scanned, can you please verify that?

You were right. I created a new Image, now the Trivy Scan successfully runs through

2022-07-08 09:50 UTC, evegufy commented on postman/CatenaX Portal Notification.json
> +{
Cool, great idea with the collection! Only thing: spaces in the file name: IMO not worth the trouble even though mostly handled alright.

2022-07-08 09:55 UTC, evegufy requested changes

2022-07-08 09:55 UTC, evegufy commented on src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json
> +    "AllowedOrigins": []
I put the cors key at the beginning of the config file (as I consider it a more non-functional config and those are mostly located at the beginning), could you please remove it here?

2022-07-08 09:58 UTC, Phil91 commented on postman/CatenaX Portal Notification.json
> +{
thanks :)
absolutley right, i've renamed the file.

2022-07-08 09:59 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json
> +    "AllowedOrigins": []
I think the merge kinda messed it up. i removed the duplicated section

2022-07-08 09:59 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/appsettings.json
> +    "AllowedOrigins": []
I think the merge kinda messed it up. i removed the duplicated section

2022-07-08 12:39 UTC, evegufy approved these changes

2022-07-12 06:28 UTC, Phil91 commented
@evegufy could you please take another look. i've made a few changes after a coordinations with martin

2022-07-12 08:40 UTC, evegufy commented
@Phil91 I rechecked it, looks fine to me!

2022-07-12 09:09 UTC, Phil91 commented
> @Phil91 I rechecked it, looks fine to me!

thanks :) i've talked to @ntruchsess he will take another look at it

2022-07-20 20:42 UTC, ntruchsess requested changes

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        return new NotificationDetailData(notificationId, content, dueDate, notificationTypeId, notificationStatusId);
as the Id of the entity is being created by the Add-method referencing notificationId here is incorrect.

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +    public async Task<IAsyncEnumerable<NotificationDetailData>> GetNotifications(string iamUserId,
The eleventh commandment is 'Thou shall not use Task\<IAsyncEnumerable\>'

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        if (companyUserId == default) throw new ForbiddenException($"iamUserId {iamUserId} is not assigned");
that check is not really reasonable - there cannot be a UserEntityId in the portal-db that is not linked to a valid companyUser as there is a foreign-key-constraint that prevents this. So this check detects that a user has got a token with an UserEntityId that is not existing in the portal-db which indicates a data-inconsistency in between keycloak and portal-db. If this really needs to be explicitly checked at all it should result in error 500. (And if so we should move this check into the controller method 'withIamUserId' so it would be checked for all endpoints)
From my point of view it is sufficient to just return an empty IAsyncEnumerable here and ignore this condition. We should discuss this with Julia.
What makes sense is to check is whether the given user is actually the receiver of a specific notification and if not throwing ForbiddenException is the correct result. (But this is a different story as in this method no specific notificationId is being specified)

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        if (companyUserId == default) throw new ForbiddenException($"iamUserId {userId} is not assigned");
this check and below 'GetNotificationCountAsync' shall be unified in a single query. (or maybe this check should be removed entirely - see my previous comment)

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        if (!await _portalRepositories.GetInstance<INotificationRepository>()
both queries can be unified into a single one. (And the query should not check the existence of the user, but whether the user is the valid receiver of the notification)

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        var exists = await notificationRepository.CheckExistsByIdAndUserIdAsync(notificationId, companyUserId).ConfigureAwait(false);
both queries can be unified into a single one. (And the query should not check the existence of the user, but whether the user is the valid receiver of the notification)

2022-07-20 20:42 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/Controllers/NotificationController.cs
> +        return CreatedAtRoute(nameof(GetNotifications), notificationDetailData);
that is not the propper use of CreatedAtRoute. It should result in an URL that allows to access this specific newly created entity, so one needs an endpoint that allows retrival of an entity by id and pass the id as parameter to CreateAtRoute.

2022-07-20 20:42 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/INotificationRepository.cs
> +    Notification Add(Guid receiverUserId, string content, NotificationTypeId notificationTypeId,
should be renamed to 'Create' as it is not adding an existing object as entity but creates a new one

2022-07-20 20:42 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +        var query = _dbContext.Notifications
Query is missing 'AsNoTracking()'

2022-07-20 20:42 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +        if (statusId.HasValue)
adding the additional conditions conditiionally to the query step by step will work for sure, but from my point of view it is harder to read and understand than including those conditions conditionally into single where-condition (like .. && statusId.HasValue ? x.ReadStatusId == statusId.Value). One cannot see on the first glance that this is all about the same query and if one forgets to use the instance being returned it would look fine but fail.

2022-07-20 20:42 UTC, ntruchsess commented on tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/NotificationRespotitoryTests.cs
> +﻿/********************************************************************************
Typo, this file should be named 'NotificationRepositoryTests.cs' not 'NotifcationRespotitoryTests.cs'

2022-07-20 20:48 UTC, ntruchsess commented
@Phil91 : I fixed all the review-comments in https://github.com/catenax-ng/product-portal-backend/pull/110/commits/e6610ee39827a2eb9df5add87d94a9c23b27fd4f adjusting the unit-tests accordingly.
please double check, of course we may discuss if you like.

2022-07-21 06:50 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/INotificationRepository.cs
> +    Notification Add(Guid receiverUserId, string content, NotificationTypeId notificationTypeId,
agreed

2022-07-21 06:51 UTC, Phil91 commented on tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/NotificationRespotitoryTests.cs
> +﻿/********************************************************************************
absolutly right

2022-07-21 06:53 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +        var query = _dbContext.Notifications
damn. thanks for adding

2022-07-21 06:54 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +        if (statusId.HasValue)
agreed. much more readable and understandable that it's one single query

2022-07-21 06:55 UTC, Phil91 commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        if (companyUserId == default) throw new ForbiddenException($"iamUserId {userId} is not assigned");
I like the new implementation

2022-07-21 06:55 UTC, Phil91 commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +    public async Task<IAsyncEnumerable<NotificationDetailData>> GetNotifications(string iamUserId,
i wrote it onto my stone wall to remember it :)

2022-07-21 06:55 UTC, Phil91 commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        return new NotificationDetailData(notificationId, content, dueDate, notificationTypeId, notificationStatusId);
missed it, thanks.

2022-07-21 10:21 UTC, Phil91 commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        if (companyUserId == default) throw new ForbiddenException($"iamUserId {iamUserId} is not assigned");
as discussed. i agree to handle it like that

2022-07-21 19:56 UTC, ntruchsess commented
there is an issue with the new Notification-entity, it comes with a circular reference:

[xUnit.net 00:00:01.13]     CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetAllFavouriteAppsForUser_ReturnsAppsSuccessfully [FAIL]
[xUnit.net 00:00:01.18]     CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetBusinessApps_ReturnsAppListSuccessfully [FAIL]
  Failed CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetAllFavouriteAppsForUser_ReturnsAppsSuccessfully [269 ms]
  Error Message:
   AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance of type AutoFixture.Kernel.SeededRequest because the traversed object graph contains a circular reference. Information about the circular path follows below. This is the correct behavior when a Fixture is equipped with a ThrowingRecursionBehavior, which is the default. This ensures that you are being made aware of circular references in your code. Your first reaction should be to redesign your API in order to get rid of all circular references. However, if this is not possible (most likely because parts or all of the API is delivered by a third party), you can replace this default behavior with a different behavior: on the Fixture instance, remove the ThrowingRecursionBehavior from Fixture.Behaviors, and instead add an instance of OmitOnRecursionBehavior:

fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
    .ForEach(b => fixture.Behaviors.Remove(b));
fixture.Behaviors.Add(new OmitOnRecursionBehavior());

                

Request path:
        CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.CompanyUser Receiver
          CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification
            System.Collections.Generic.IEnumerable`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification]
              System.Collections.Generic.IEnumerable`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] collection
                System.Collections.Generic.List`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification]
                  System.Collections.Generic.ICollection`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification]
                    System.Collections.Generic.ICollection`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] Notifications
                      CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.CompanyUser

2022-07-21 20:13 UTC, ntruchsess requested changes
there is an issue with the new Notification-entity, it comes with a circular reference:

[xUnit.net 00:00:01.13] CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetAllFavouriteAppsForUser_ReturnsAppsSuccessfully [FAIL]
[xUnit.net 00:00:01.18] CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetBusinessApps_ReturnsAppListSuccessfully [FAIL]
Failed CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetAllFavouriteAppsForUser_ReturnsAppsSuccessfully [269 ms]
Error Message:
AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance of type AutoFixture.Kernel.SeededRequest because the traversed object graph contains a circular reference. Information about the circular path follows below. This is the correct behavior when a Fixture is equipped with a ThrowingRecursionBehavior, which is the default. This ensures that you are being made aware of circular references in your code. Your first reaction should be to redesign your API in order to get rid of all circular references. However, if this is not possible (most likely because parts or all of the API is delivered by a third party), you can replace this default behavior with a different behavior: on the Fixture instance, remove the ThrowingRecursionBehavior from Fixture.Behaviors, and instead add an instance of OmitOnRecursionBehavior:

fixture.Behaviors.OfType().ToList()
.ForEach(b => fixture.Behaviors.Remove(b));
fixture.Behaviors.Add(new OmitOnRecursionBehavior());

Request path:
CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.CompanyUser Receiver
CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification
System.Collections.Generic.IEnumerable1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] System.Collections.Generic.IEnumerable1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] collection
System.Collections.Generic.List1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] System.Collections.Generic.ICollection1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification]
System.Collections.Generic.ICollection`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] Notifications
CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.CompanyUser

2022-07-22 07:40 UTC, Phil91 commented
> there is an issue with the new Notification-entity, it comes with a circular reference:
> 
> [xUnit.net 00:00:01.13] CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetAllFavouriteAppsForUser_ReturnsAppsSuccessfully [FAIL] [xUnit.net 00:00:01.18] CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetBusinessApps_ReturnsAppListSuccessfully [FAIL] Failed CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.UserRepositoryTests.GetAllFavouriteAppsForUser_ReturnsAppsSuccessfully [269 ms] Error Message: AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance of type AutoFixture.Kernel.SeededRequest because the traversed object graph contains a circular reference. Information about the circular path follows below. This is the correct behavior when a Fixture is equipped with a ThrowingRecursionBehavior, which is the default. This ensures that you are being made aware of circular references in your code. Your first reaction should be to redesign your API in order to get rid of all circular references. However, if this is not possible (most likely because parts or all of the API is delivered by a third party), you can replace this default behavior with a different behavior: on the Fixture instance, remove the ThrowingRecursionBehavior from Fixture.Behaviors, and instead add an instance of OmitOnRecursionBehavior:
> 
> fixture.Behaviors.OfType().ToList() .ForEach(b => fixture.Behaviors.Remove(b)); fixture.Behaviors.Add(new OmitOnRecursionBehavior());
> 
> Request path: CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.CompanyUser Receiver CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification System.Collections.Generic.IEnumerable1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] System.Collections.Generic.IEnumerable1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] collection System.Collections.Generic.List1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] System.Collections.Generic.ICollection1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] System.Collections.Generic.ICollection`1[CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.Notification] Notifications CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.CompanyUser

I've configured the test setup to ignore the circular reference.

2022-07-26 08:03 UTC, ntruchsess approved these changes

2022-07-26 09:08 UTC, merged