cplp-656- delete business partner number of assigned user
catenax-ng/product-portal-backend pull request #112
Opened 2022-07-04 09:53 UTC by Akshay-Chaudhari-BMW

delete business partner number of assigned user

2022-07-04 17:28 UTC, jjeroch requested changes

2022-07-04 17:28 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
>      }
@Akshay-Chaudhari-BMW  I am missing in this commit the new swagger documentation level.
If you have a look at pr https://github.com/catenax-ng/product-portal-backend/pull/91/files you can nicely see how w are changing the swagger documentation. Could you please do the same for your commit. If you have questions, please get in touch with @Phil91 he is of tomorrow but will be back on Wednesday

2022-07-04 17:28 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        public async Task<int> DeleteOwnUserBusinessPartnerNumbersAsync(Guid companyUserId, string adminUserId)
@Akshay-Chaudhari-BMW  I am missing the Exception for "User {CompanyUserID} doesn't exist"
What happens in the current implementation if the CompanyUserID doesn't exist?

2022-07-04 17:29 UTC, jjeroch commented
@Akshay-Chaudhari-BMW please share if the update of Keycloak is already a part of the commit. If not, I propose we add that before letting someone start the review.

2022-07-05 06:21 UTC, jjeroch commented
Alright all good then ;)

2022-07-08 07:53 UTC, ntruchsess requested changes

2022-07-08 07:53 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var user = await _CentralIdp.GetUserAsync(_ProvisioningSettings.CentralRealm, userWithBpn.UserEntityId.ToString()).ConfigureAwait(false);
Use of keycloak-api shall be encapsulated in provisioningmanager, please move code of lines 571-591 into ProvisioningManager.cs below method AddBpnAttributetoUserAsync

2022-07-11 09:03 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var user = await _CentralIdp.GetUserAsync(_ProvisioningSettings.CentralRealm, userWithBpn.UserEntityId.ToString()).ConfigureAwait(false);
code moved to provisioning manager

2022-07-19 04:49 UTC, jjeroch approved these changes

2022-07-19 07:56 UTC, ntruchsess requested changes

2022-07-19 07:56 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var validUsers = await userBusinessPartnerRepository.IsAdminUserAndCompanyUserHavingSameCompanyId(companyUserId, adminUserId);
please unify both queries 'IsAdminUserAndCompanyUserHavingSameCompanyId' and 'GetOwnCompanyUserWithAssignedBusinessPartnerNumberAsnc' into a single one to avoid having 2 calls to the database instead of one.
like so:
    public Task<CompanyUserBusinessPartnerNumbersDetails?> GetOwnCompanyUserWithAssignedBusinessPartnerNumbersAsync(Guid companyUserId,string adminUserId, string businessPartnerNumber) =>
      _dbContext.CompanyUsers
            .AsNoTracking()
            .Where(companyUser => companyUser.Id == companyUserId)
            .Select(companyUser => new CompanyUserBusinessPartnerNumbersDetails(
                companyUser.IamUser!.UserEntityId,
                companyUser.CompanyUserAssignedBusinessPartners.Where(assignedPartner => assignedPartner.BusinessPartnerNumber == businessPartnerNumber).SingleOrDefault(),
                companyUser.Company!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == adminUserId)
            ))
            .SingleOrDefaultAsync();

2022-07-19 07:56 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserBusinessPartnerRepository.cs
> +                companyUser.CompanyUserAssignedBusinessPartners.Where(assignedPartner => assignedPartner.BusinessPartnerNumber == businessPartnerNumber).SingleOrDefault()
this line causes a possible null-reference warning.

2022-07-20 11:11 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/ProvisioningManager.cs
> +                throw new NotFoundException($"bpn is not found in the user mapper");
new KeycloakEntityNotFoundException can be found in branch feature/CPLP-1170-Add-external-Service-ErrorHandling

2022-07-21 14:07 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/ProvisioningManager.cs
> +                throw new NotFoundException($"bpn is not found in the user mapper");
I did fix this one by myself

2022-07-21 14:33 UTC, ntruchsess approved these changes

2022-07-21 14:34 UTC, merged