cplp-1168 - fix for app user response and swagger documentation
catenax-ng/product-portal-backend pull request #118
Opened 2022-07-08 10:16 UTC by Akshay-Chaudhari-BMW

fix for app user response issue and swagger documentation has been added.

2022-07-12 19:40 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Result as a Company App Users Details</response>
Lets change the message to "Returns the company users with assigned role for the requested app id." eventhough we still need to do small adjustments on the API until this is working ;)

2022-07-12 19:40 UTC, jjeroch commented
I can take the review, we can release Norbert and Evelyn for the more critical topics :)

2022-07-13 18:53 UTC, jjeroch requested changes

2022-07-13 18:53 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Result as a Company App Users Details</response>
@Akshay-Chaudhari-BMW  can you please make the small change, the rest is all good

2022-07-14 05:02 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Result as a Company App Users Details</response>
resolved with msg change

2022-07-14 06:00 UTC, jjeroch approved these changes

2022-07-14 06:16 UTC, jjeroch commented
@Akshay-Chaudhari-BMW ready to merge whenever you want ;)

2022-07-14 06:19 UTC, Akshay-Chaudhari-BMW commented
We can merge it now.

2022-07-14 06:21 UTC, merged