CPLP-1181 add validation to create connector bl
catenax-ng/product-portal-backend pull request #120
Opened 2022-07-12 14:30 UTC by Phil91

Implementation of [CPLP-1181](https://jira.catena-x.net/browse/CPLP-1181)

2022-07-12 14:32 UTC, Phil91 commented
@jjeroch I've added a .ToUpper() to the location, which will convert e.g. 'de' to 'DE'. With that some of the errors won't occure. Hope that's fine

2022-07-15 00:22 UTC, ntruchsess requested changes

2022-07-15 00:22 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        if (provider != host && host.HasValue && !await _portalRepositories.GetInstance<ICompanyRepository>().CheckCompanyExistsByIdAsync(host.Value).ConfigureAwait(false))
If the same repository is used multiple times within a method please get a single reference and reuse it.

2022-07-15 06:57 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        if (provider != host && host.HasValue && !await _portalRepositories.GetInstance<ICompanyRepository>().CheckCompanyExistsByIdAsync(host.Value).ConfigureAwait(false))
fixed it.
just for my understanding, if we don't have the single reference we will use "different databases" correct?

2022-07-20 20:55 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        if (provider != host && host.HasValue && !await _portalRepositories.GetInstance<ICompanyRepository>().CheckCompanyExistsByIdAsync(host.Value).ConfigureAwait(false))
no we would not have different database(connections), When being called within the same execution-context of the dependency-container those calls are just redundant and besides unnecessary spending a few cycles of cpu-time it would not cause any harm.

2022-07-20 21:18 UTC, ntruchsess requested changes

2022-07-20 21:18 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        await using var transaction = await _portalRepositories.BeginTransactionAsync().ConfigureAwait(false);
I guess the intention is to run the database-update and the remote api-call atomically within a single transaction? As the api-call does not participate in this transaction it is not any better then calling safeAsync on the dbContext after the api-call and bail out in case the api-call is not succesful.
Please remove the call to saveAsync from the implementation of CreateConnectorAsync() and call it separately after the api-call (is is exposed on the instance of PortalRepositories).

2022-07-20 21:18 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        CreatedAtRoute(string.Empty, await _appsBusinessLogic.CreateAppAsync(appInputModel).ConfigureAwait(false));
That is not the propper use of CreateAtRoute. The first parameter shall refer to the name of an endpoint that can be used to retrive this newly created entity. The second paramter is an anynomous object with property-names matching the parameters of that query that is being referred to. The Framework uses this information to create the standard http-response-header 'Location'.
With Route-name being 'string.empty' this ain't work.

2022-07-20 21:18 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +    public App CreateApp(Guid id, string provider) =>
from my point of view it's preferable to create the new Guid within the Create-method.

2022-07-21 06:32 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        await using var transaction = await _portalRepositories.BeginTransactionAsync().ConfigureAwait(false);
Didn't recognized that. I've removed the Transaction call and changed it to the SaveAsync if the SdFactory Call was successfull.

2022-07-21 06:32 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        CreatedAtRoute(string.Empty, await _appsBusinessLogic.CreateAppAsync(appInputModel).ConfigureAwait(false));
Absolutly right. Changed it

2022-07-21 06:34 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +    public App CreateApp(Guid id, string provider) =>
The Id is now created in the repository

2022-07-21 16:14 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +    public App CreateApp(Guid id, string provider) =>
I just added a addOptionalParameters Action: https://github.com/catenax-ng/product-portal-backend/pull/120/commits/898ed8d649035916ce575d18397c6c9386958d5c

2022-07-21 19:42 UTC, ntruchsess requested changes

2022-07-21 19:42 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
>              var httpClient = new HttpClient();
- the api-call should be encapsulated in its own service-class that gets the required config injected and hides the technical details from the business-logic.
- in line 139 is a catch(Exception) { throw; }. That is redundant and should be removed.

2022-07-21 19:42 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ConnectorsController.cs
> +    public Task<ConnectorData> GetCompanyConnectorByIdForCurrentUserAsync([FromRoute] Guid connectorId) =>
FYI: I did add this getconnectorbyid endpoint. The CreatedAtRoute-response will create a location-header that links the created entity, not the general list of all entities.

2022-07-21 19:42 UTC, ntruchsess commented on src/keycloak/CatenaX.NetworkServices.Keycloak.Authentication/ControllerExtensions.cs
> +    public static T WithBearerToken<T>(this ControllerBase controller, Func<string, T> tokenConsumingFunction)
FYI: I did add this extension-function to the ControllerBase that extracts the bearer-token (same pattern as WithIamUSerId)

2022-07-21 19:42 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/ConnectorData.cs
> +public class ConnectorData
FYI: I moved the ViewModel to the DBAccess-Models to allow creating instances within the repository.

2022-07-21 19:42 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +    public Connector CreateConnectorAsync(string name, string location, string connectorUrl, Action<Connector>? setupOptionalFields)
Rename to 'CreateConnector' as it is not async

2022-07-21 19:42 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
> +    Task<(ConnectorData ConnectorData, bool IsProviderUser)> GetConnectorByIdForIamUser(Guid connectorId, string iamUser);
FYI: I did remove the 'public'-keywords as methods of a public interface are public by default. You need to specify 'public' in the implementation

2022-07-22 09:08 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +    public Connector CreateConnectorAsync(string name, string location, string connectorUrl, Action<Connector>? setupOptionalFields)
Renamed

2022-07-22 09:08 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
>              var httpClient = new HttpClient();
i've refactored it to a separate service

2022-07-22 13:47 UTC, ntruchsess approved these changes
I did consolidate the multiple company-related queries into a single one and did some cleanup: https://github.com/catenax-ng/product-portal-backend/pull/120/commits/f8eeb0301ddd7c698cc794c92315c06a538deca5
From my point of view it is not ready to merge. Please double-check my changes before merging

2022-07-22 14:03 UTC, merged