Feature/cplp 1109 retrieve all applications with status
catenax-ng/product-portal-backend pull request #121
Opened 2022-07-13 09:07 UTC by Akshay-Chaudhari-BMW

retrieve all applications with status and user details

2022-07-13 09:52 UTC, jjeroch commented
@Phil91  can you please take over. Target of the API: take all applications which are in the db.
Ticket: https://jira.catena-x.net/browse/CPLP-1109
Inside the Ticket there is also an example how this is supposed to show up in future in the web-application

2022-07-13 11:56 UTC, Phil91 requested changes

2022-07-13 11:56 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +         _dbContext.CompanyApplications.AsNoTracking();
is it correct to get all companyApplications that exists? In my understanding we only should get the CompanyApplications for the current users company.
@jjeroch could you clarify?

2022-07-13 11:56 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    public Task<Pagination.Response<CompanyApplicationWithCompanyUserDetails>> GetAllCompanyApplicationsDetailsAsync([FromQuery]int page, [FromQuery]int size) =>
could you please define default values for page and size

2022-07-13 18:41 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    public Task<Pagination.Response<CompanyApplicationWithCompanyUserDetails>> GetAllCompanyApplicationsDetailsAsync([FromQuery]int page, [FromQuery]int size) =>
@Akshay-Chaudhari-BMW  please go for page "0" and size "15"

2022-07-13 18:41 UTC, jjeroch commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +         _dbContext.CompanyApplications.AsNoTracking();
@Phil91  in this case its fine since this is for the operation company itself. They are allowed to see all to manage the invites

2022-07-14 05:10 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    public Task<Pagination.Response<CompanyApplicationWithCompanyUserDetails>> GetAllCompanyApplicationsDetailsAsync([FromQuery]int page, [FromQuery]int size) =>
resolved

2022-07-14 05:45 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +         _dbContext.CompanyApplications.AsNoTracking();
thanks for the clarification

2022-07-14 05:47 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    public Task<Pagination.Response<CompanyApplicationWithCompanyUserDetails>> GetAllCompanyApplicationsDetailsAsync([FromQuery]int page, [FromQuery]int size) =>
did you already pushed the changes? i don't see any new commits

2022-07-14 05:52 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    public Task<Pagination.Response<CompanyApplicationWithCompanyUserDetails>> GetAllCompanyApplicationsDetailsAsync([FromQuery]int page, [FromQuery]int size) =>
Please check now....I was not sync properly.

2022-07-14 05:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    public Task<Pagination.Response<CompanyApplicationWithCompanyUserDetails>> GetAllCompanyApplicationsDetailsAsync([FromQuery]int page, [FromQuery]int size) =>
looks good now :)

2022-07-14 05:55 UTC, Phil91 approved these changes

2022-07-14 19:27 UTC, jjeroch commented
@Akshay-Chaudhari-BMW can you please solve the conflict and merge the pr after that. Thanks!

2022-07-15 00:00 UTC, ntruchsess requested changes

2022-07-15 00:00 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                            .Select(invitation => invitation.CompanyUser)
that criteria might result in a mixture of FirstName, LastName and Email from different CompanyUsers - If this is not what is intended the criteria is redundant and should be applied only once:
                    .Select(application => new
                    {
                        Application = application,
                        CompanyUser = application.Invitations.Select(invitation => invitation.CompanyUser)
                            .Where(companyUser =>
                                companyUser!.CompanyUserStatusId == CompanyUserStatusId.ACTIVE
                                && companyUser.Firstname != null
                                && companyUser.Lastname != null
                                && companyUser.Email != null
                            ).FirstOrDefault()
                    })
                    .Select(s => new CompanyApplicationWithCompanyUserDetails(
                        s.Application.ApplicationStatusId,
                        s.Application.DateCreated,
                        s.Application.Company!.Name)
                    {
                        FirstName = s.CompanyUser!.Firstname,
                        LastName = s.CompanyUser.Lastname,
                        Email = s.CompanyUser.Email
                    })
                    .AsAsyncEnumerable()));

2022-07-15 04:33 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                            .Select(invitation => invitation.CompanyUser)
resolved

2022-07-15 10:12 UTC, ntruchsess approved these changes

2022-07-15 10:12 UTC, merged