feature/CPLP-1170 add external service error handling
catenax-ng/product-portal-backend pull request #126
Opened 2022-07-20 05:25 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1170

2022-07-20 11:33 UTC, ntruchsess requested changes
As the new EntityNotFoundException shall not be thrown by code that is not releated to keycloak-api-calls I did move the EntityNotFoundException into new namespace CatenaX.NetworkServices.Keycloak.ErrorHandling (creating a new project in the solution) renaming it to KeycloakEntityNotFoundException.
If not being caught by Provisioningmanager or BusinessLogic it will be handled by the unspecific Exception-path of GeneralHttpErrorHandler resulting in Error 500 as expected. I therefore removed the Exception-Type-specific (but redundant) error-handling from GeneralHttpErrorHandler, we just don't need it. If we want something different than error 500 it would be caught and handled in businesslogic (or provisioningManager), and if we want error 500 then we already get it.
Please see my other comments for requested changes (most are about redundant try/catch)

2022-07-20 11:33 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            catch (KeycloakEntityNotFoundException ex)
this try-catch is redundant, please remove

2022-07-20 11:33 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ClientManager.cs
>          if (credentials == null)
redundant null check, please remove (see previous comment)

2022-07-20 11:33 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ClientManager.cs
>          if (credentials == null)
redundant null check, please remove (see previous comment)

2022-07-20 11:33 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ClientManager.cs
>          {
redundant null check, please remove (see previous comment)

2022-07-20 11:33 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ServiceAccountManager.cs
> +        catch(KeycloakEntityNotFoundException nfe)
that try-catch is redundant, please remove

2022-07-20 11:33 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/ProvisioningManager.cs
> +            catch (KeycloakEntityNotFoundException ex)
redundant try/catch, please remove

2022-07-20 11:33 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/ProvisioningManager.cs
> +            catch (KeycloakEntityNotFoundException ex)
redundant try/catch, please remove and revert the declaration of providerUserId

2022-07-21 06:14 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                catch (KeycloakEntityNotFoundException exception)
fixed

2022-07-21 06:14 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            catch (KeycloakEntityNotFoundException ex)
fixed

2022-07-21 06:14 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            catch (KeycloakEntityNotFoundException ex)
fixed

2022-07-21 06:15 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            catch (KeycloakEntityNotFoundException ex)
fixed

2022-07-21 06:15 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    catch (KeycloakEntityNotFoundException ex)
fixed

2022-07-21 06:15 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ClientManager.cs
>          {
fixed

2022-07-21 06:15 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ServiceAccountManager.cs
> +        catch(KeycloakEntityNotFoundException nfe)
fixed

2022-07-21 06:15 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/UserManager.cs
>              if (user == null)
fixed

2022-07-21 06:15 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/ProvisioningManager.cs
> +            catch (KeycloakEntityNotFoundException ex)
fixed

2022-07-21 12:05 UTC, merged