CPLP 1189 - get app details
catenax-ng/product-portal-backend pull request #127
Opened 2022-07-20 07:40 UTC by Phil91

Implementation of [CPLP-1189](https://jira.catena-x.net/browse/CPLP-1189)

2022-07-20 21:39 UTC, ntruchsess requested changes

2022-07-20 21:39 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +    public async Task<AppDetailsData> GetAppDetailsByIdAsync(Guid appId, string iamUserId, string? languageShortName)
please check line 58-74 (as you did not modify within this PR I cannot add comments there:
        if(new []{ appDetails.Name, appDetails.Provider, appDetails.ContactEmail }.Any(d => d is null))
        {
            var nullProperties = new List<string>();
            if (appDetails.Name is null)
            {
                nullProperties.Add($"{nameof(App)}.{nameof(appDetails.Name)}");
            }
            if (appDetails.Provider is null)
            {
                nullProperties.Add($"{nameof(App)}.{nameof(appDetails.Provider)}");
            }
@@ -97,27 +98,27 @@
                UseCaseNames = a.UseCases.Select(uc => uc.Name),
                a.ThumbnailUrl,
                ShortDescription =
                    _context.Languages.SingleOrDefault(l => l.ShortName == languageShortName) == null 
                        ? null 
                        : a.AppDescriptions.SingleOrDefault(d => d.LanguageShortName == languageShortName)!.DescriptionShort
                          ?? a.AppDescriptions.SingleOrDefault(d => d.LanguageShortName == Constants.DefaultLanguage)!.DescriptionShort,
                LicenseText = a.AppLicenses
                    .Select(license => license.Licensetext)
                    .FirstOrDefault()
            }).AsAsyncEnumerable().Select(app => new AppData(
                app.Name ?? Constants.ErrorString,
                app.ShortDescription ?? Constants.ErrorString,
                app.VendorCompanyName ?? Constants.ErrorString,
                app.LicenseText ?? Constants.ErrorString,
                app.ThumbnailUrl ?? Constants.ErrorString
                )
            {
                Id = app.Id,
                UseCases = app.UseCaseNames.Select(name => name).ToList()
            });

Please move this check to the businesslogic.

2022-07-20 21:39 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                IsPurchased = a.Companies.FirstOrDefault(c => c.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == iamUserId)) == null ?
IsPurchased = a.Companies.Where(c => c.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == iamUserId)).SelectMany(company => company.CompanyAssignedApps.Where(x => x.AppId == appId)).Select(x => x.AppSubscriptionStatusId).FirstOrDefault(),

2022-07-21 05:45 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +    public async Task<AppDetailsData> GetAppDetailsByIdAsync(Guid appId, string iamUserId, string? languageShortName)
moved it

2022-07-21 05:45 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                IsPurchased = a.Companies.FirstOrDefault(c => c.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == iamUserId)) == null ?
thanks. if changed the query

2022-07-21 11:56 UTC, ntruchsess approved these changes

2022-07-21 11:56 UTC, merged