cplp - 463 - get app user role with respective app
catenax-ng/product-portal-backend pull request #128
Opened 2022-07-21 12:09 UTC by Akshay-Chaudhari-BMW

get app user role with respective app

2022-07-21 15:54 UTC, ntruchsess requested changes

2022-07-21 15:54 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var companyId = await _portalRepositories.GetInstance<IUserRepository>().GetCompanyIdForIamUserUntrackedAsync(iamUserId).ConfigureAwait(false);
we should avoid to go to the database more often than necessary. To get the roles associated with a specific appId that are actually assigned to users of the same company as the calling user I suggest the following query:

```
    public IQueryable<CompanyUserAssignedRole> GetOwnCompanyAppUserAssignedRolesUntrackedAsync(Guid appId, string iamUserId) =>
        _context.CompanyUserAssignedRoles
            .AsNoTracking()
            .Where(assignedRole => assignedRole.UserRole!.IamClient!.Apps.Any(app => app.Id == appId)
                && assignedRole.CompanyUser!.Company!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == iamUserId));

```

2022-07-22 08:21 UTC, ntruchsess requested changes

2022-07-22 08:21 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
> +    public IQueryable<CompanyUserAssignedRole> GetOwnCompanyAppUsersUntrackedAsync(Guid appId, string iamUserId) =>
To match my comment above I suggest:

```
    public IQueryable<CompanyUser> GetOwnCompanyAppUsersUntrackedAsync(Guid appId, string iamUserId) =>
       _context.CompanyUsers
            .AsNoTracking()
            .Where(companyUser => companyUser.UserRoles.Any(userRole => userRole.IamClient!.Apps.Any(app => app.Id == appId))
                && companyUser.Company!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == iamUserId));

```

2022-07-22 10:06 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                        .Select(companyUserAssignedRoles => new CompanyAppUserDetails(
resolved

2022-07-22 10:07 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
> +    public IQueryable<CompanyUserAssignedRole> GetOwnCompanyAppUsersUntrackedAsync(Guid appId, string iamUserId) =>
resolved

2022-07-22 11:48 UTC, ntruchsess approved these changes

2022-07-22 11:49 UTC, merged