CPLP-410 Email Registration Welcome Dev. Changes
catenax-ng/product-portal-backend pull request #13
Opened 2022-04-12 09:58 UTC by Akshay-Chaudhari-BMW

2022-04-12 18:02 UTC, ntruchsess requested changes
see my comments inline

2022-04-12 18:10 UTC, jjeroch commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +             await _mailingService.SendMails("julia.jeroch@bmw.de", mailParameters, new List<string> { "EmailRegistrationWelcomeTemplate"} );
Yes true. I guess thats a mistake cause the last test email was send to me. But fully agree, that need to get corrected ;)

2022-04-13 07:30 UTC, Akshay-Chaudhari-BMW commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/Controllers/UserAdministrationController.cs
> +        public async Task<IActionResult> PostRegistrationWelcomeEmailAsync([FromBody] RegistrationData registrationData)
I discussed with Julia and Evelyn, So retrieving data from database is out of scope for this user story. This needs to be address by other user story and this story should not be too complex. But its completely valid comment.

2022-04-13 09:26 UTC, Akshay-Chaudhari-BMW commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +             await _mailingService.SendMails("julia.jeroch@bmw.de", mailParameters, new List<string> { "EmailRegistrationWelcomeTemplate"} );
Wrongly checked-In code, Now removed hard-code value.

2022-04-13 10:30 UTC, evegufy requested changes

2022-04-13 10:30 UTC, evegufy commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/Models/WelcomeData.cs
> +        [JsonPropertyName("organisationName")]
I'd suggest calling it 'companyName' instead of 'organisationName', in the majority of cases and also in the database call it about company. I know this isn't the case everywhere like in 'CompanyInvitationData' but we should try to consolidate towards one term.

2022-04-13 10:30 UTC, evegufy commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                { "Company_Name", welcomeData.organisationName },
I think it's a confusing to pass the same value twice within different parameters. I'd suggest removing the parameter 'organizationName' and naming the company parameter 'companyName'. For that you'd also need to adjust the template 'portal_welcome_email.html' to only use 'companyName', also where currently 'organizationName' is used.

2022-04-13 10:30 UTC, evegufy commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                { "url", $"{_settings.RegistrationBasePortalAddress}"},
I think you don't want to pass the '_settings.RegistrationBasePortalAddress but rather the '_settings.Portal.BasePortalAddress'

2022-04-13 12:47 UTC, Akshay-Chaudhari-BMW commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                { "Company_Name", welcomeData.organisationName },
renamed organisationName to companyName

2022-04-13 12:48 UTC, Akshay-Chaudhari-BMW commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/Models/WelcomeData.cs
> +        [JsonPropertyName("organisationName")]
renamed organisationName to companyName

2022-04-13 12:48 UTC, Akshay-Chaudhari-BMW commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                { "url", $"{_settings.RegistrationBasePortalAddress}"},
url value changed.

2022-04-13 15:59 UTC, ntruchsess approved these changes

2022-04-13 16:01 UTC, ntruchsess commented
codingwise it looks fine, given that further functional changes have been agreed on to be implemented in later sprint I think this PR is ready to merge.

2022-04-13 21:47 UTC, jjeroch requested changes
@Akshay-Chaudhari-BMW since there is an important pre-assumption in that implementation and we need to ensure that this assumption is kept in mind and still needs development, please add infront of the newly added business logic a comment inside the code that the full functionality is not yet delivered and currently the service is working with a submitted (json?) file where user email, application ID and organization name are handed over, otherwise the job is not usable.

2022-04-14 08:35 UTC, evegufy approved these changes

2022-04-14 08:42 UTC, Akshay-Chaudhari-BMW commented
@jjeroch I have added comments on implementation.

2022-04-14 08:44 UTC, evegufy commented
@Akshay-Chaudhari-BMW I think you accidentally closed the PR when commenting, I reopened it

2022-04-14 08:56 UTC, jjeroch requested changes
@Akshay-Chaudhari-BMW 
`submitted (json?) file`
what is the exact file type? Can you please add the information of the input file format which is needed to run the service? Just replace the information here with the truth ;) we should not write anything with a question mark. I just took the questions mark since I am not sure if my statement was right

2022-04-14 09:06 UTC, Akshay-Chaudhari-BMW commented
@jjeroch Json file format is needed to run the service.

2022-04-14 10:45 UTC, jjeroch approved these changes

2022-04-14 13:27 UTC, evegufy commented
@Akshay-Chaudhari-BMW If nobody of the reviewers also merges the PR you can just go ahead and merge the PR yourself. For this PR, I'll do the merge now.

2022-04-14 13:27 UTC, merged