CPLP-1247 welcome notification
catenax-ng/product-portal-backend pull request #137
Opened 2022-07-27 09:59 UTC by Phil91

Implementation of [CPLP-1247](https://jira.catena-x.net/browse/CPLP-1247)

✅ Add system generated welcome notifications on application approval 
✅ Extend the notification types
✅ Add a NotificationService to create notifications solution wide
✅ Add UnitTests

Also check [PR](https://github.com/tractusx-team-portal-onboarding/devenv/pull/91)

2022-07-28 13:59 UTC, ntruchsess requested changes

2022-07-28 13:59 UTC, ntruchsess commented on src/CatenaX.NetworkServices.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CatenaX.NetworkServices.Framework.Notifications", "framework\CatenaX.NetworkServices.Framework.Notifications\CatenaX.NetworkServices.Framework.Not
I suggest naming this module CatenaX.NetworkServices.Notification.Library
'FrameWork' should be used for code that is more technical by it's nature so it might also be useful outside the scope of catena and portal.

2022-07-28 13:59 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.Models/Constants.cs
> +    public const string CatenaXCompanyName = "Catena-X";
those constants do not belong to 'Framework'. They should be configurable in appsettings.json (resp. in the secrets)

2022-07-28 13:59 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +                         NotificationTypeId.WELCOME,
this set of NotificationTypeIds should also be configurable in appsettings.json

2022-07-28 13:59 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public IAsyncEnumerable<(Guid CompanyUserId, bool IsCatenaXAdmin, bool IsCompanyAdmin)> GetCatenaAndCompanyAdminIdAsync(Guid companyId) =>
repository-methods shall contain business-functionality. In this case the query should not refer to constants, those values should be passed as parameters (where the values in this case should be taken from the appsettings.json by the businesslogic).
It would be even more generic to pass in the roles as IEnumerable and then return the roles that are actually assigned per user also as IEnumerable. The check whether a specific role in this set of roles being queried would then be executed in the business-logic. Of course this will enlarge the size of the result a bit (as role-names are being transfered instead of boolean values) but the method itself then would be 100% free of businesslogic and if we would need to include further roles in the futher the query would not have to change.
There should be no significant difference in execution-time of the query as the very same data needs to be accessed in the db for this.

2022-07-28 13:59 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyUser.cs
>      public virtual ICollection<Notification> Notifications { get; set; }
same as UserRoles. please change the setter to private and adjust the test-code accordingly.

2022-07-28 13:59 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyUser.cs
> +    public virtual ICollection<UserRole> UserRoles { get; set; }
Navigational Properties of x-n relationships shall not be public settable.
In Tests use xxx.UserRoles.Add(...) to seed test-data.

2022-07-28 13:59 UTC, ntruchsess commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        NotificationCreationData creationData, Guid receiverId) =>
async + await are redundant, please remove

2022-07-28 13:59 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +        await _portalRepositories.SaveAsync().ConfigureAwait(false);
if this method is meant to be called from other business-logic it should participate in the transaction of that calling code to ensure registration and creation of notifications will happen atomically both or not at all.

2022-07-28 13:59 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +    public async Task CreateWelcomeNotificationsForCompanyAsync(Guid companyId)
As this method is called by the Registration-service only it should rather be implemented in that module so configuration of welcome notification type ids would also be part of the registration-settings.
@jjeroch : Is there any intention to send out this specific set of notifications in any other context?

2022-07-28 13:59 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +        await _portalRepositories.SaveAsync().ConfigureAwait(false);
if this method is meant to be called from other busineslogic (currently this is where the only reference originates from) it should participate in the calling codes transaction.

2022-07-28 18:14 UTC, ntruchsess requested changes

2022-07-28 18:14 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Select(companyUser => ((Guid CompanyUserId, bool IsIamUser)) new ValueTuple<Guid, bool>(companyUser.Id, companyUser.IamUser!.UserEntityId == iamUserId))
specifying 'ValueTuple' is not required in dotnet6 any more. It's sufficient to use 'new (companyUser.Id, companyUser.IamUser...)' to create an anonymous tuple-typed object.
(The cast to the specific tuple-type with property-names is still required though).

2022-07-29 12:50 UTC, Phil91 commented on src/CatenaX.NetworkServices.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CatenaX.NetworkServices.Framework.Notifications", "framework\CatenaX.NetworkServices.Framework.Notifications\CatenaX.NetworkServices.Framework.Not
I've refactored it a bit, guess we don't really need a separat project for it since the notifications are only created in the specific use cases and for general purposes we have our repositories

2022-07-29 12:53 UTC, Phil91 commented on src/framework/CatenaX.NetworkServices.Framework.Models/Constants.cs
> +    public const string CatenaXCompanyName = "Catena-X";
i've moved it to the secrets

2022-07-29 12:53 UTC, Phil91 commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +                         NotificationTypeId.WELCOME,
moved as well

2022-07-29 12:54 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public IAsyncEnumerable<(Guid CompanyUserId, bool IsCatenaXAdmin, bool IsCompanyAdmin)> GetCatenaAndCompanyAdminIdAsync(Guid companyId) =>
refactored it.

2022-07-29 12:54 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyUser.cs
>      public virtual ICollection<Notification> Notifications { get; set; }
it's private again

2022-07-29 12:54 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyUser.cs
> +    public virtual ICollection<UserRole> UserRoles { get; set; }
private again :)

2022-07-29 12:54 UTC, Phil91 commented on src/notification/CatenaX.NetworkServices.Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        NotificationCreationData creationData, Guid receiverId) =>
refactored

2022-07-29 12:54 UTC, Phil91 commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +        await _portalRepositories.SaveAsync().ConfigureAwait(false);
i refactored it.

2022-07-29 12:55 UTC, Phil91 commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +    public async Task CreateWelcomeNotificationsForCompanyAsync(Guid companyId)
totaly right, the only use case for the welcome messages is in the bl, refactored it

2022-07-29 12:55 UTC, Phil91 commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +        await _portalRepositories.SaveAsync().ConfigureAwait(false);
refactored

2022-07-29 12:55 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Select(companyUser => ((Guid CompanyUserId, bool IsIamUser)) new ValueTuple<Guid, bool>(companyUser.Id, companyUser.IamUser!.UserEntityId == iamUserId))
I've added the value tuple due to SonarCloud CodeSmells, i could remove it and we mark it as 'won't fix'

2022-08-01 17:04 UTC, ntruchsess requested changes

2022-08-01 17:04 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(x => (x.Company!.Name == catenaXCompanyName && x.UserRoles.Any(y => y.UserRoleText == cxAdminRolename)) ||
Neither are company.Name and userRoles.UserRoleText primary-key-fields nor are there (and so far also shall not be) any unique constraints that would ensure we actually get the expected result. That is also a security-issue, we must use the companyId and RoleIds here. ( please also negotiate with @jjeroch )

2022-08-01 17:28 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.Notifications/NotificationService.cs
> +        await _portalRepositories.SaveAsync().ConfigureAwait(false);
cannot see how your refactoring (moving this piece of code into private method in RegistrationBusinessLogic) does address the issue with 'should participate in the same transaction' as the calling code. There are still 2 separate calls to portalrespositories.SaveAsync().

2022-08-01 17:37 UTC, ntruchsess requested changes

2022-08-01 17:37 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                throw new ArgumentException($"user {userName} has no assigned email");
I know this is from preexisting code, but if any of the users does not have a email-address assigned the remaining users would not get an email either. (This also results in a code-smell ;-) ).
From my point of view it would be fine to collect the usernames in question (not throwing the exception here but skipping the sending of email) and throwing the ArgumentException once for all users without emailaddress after all other emails have been sent out.
For the very same reason the call to 'SendEmails' should be enclosed in a try-catch as any (even temporary) failure in sending an email (like malformed emal-address) would also stop sending out the remaining emails.

2022-08-02 19:53 UTC, ntruchsess requested changes

2022-08-02 19:53 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var catenaXAdmin = userIds.First(x => x.CompanyId == _settings.CatenaXCompanyId && x.RoleId == _settings.CxAdminRoleId).CompanyUserId;
I just realize that this is most likely not what we need here (finding the CX-Admin in the database). Actually the endpoint is called by a CX-Admin user and it would make most sense if this CX-Admin-user calling the endpoint is also the sender of the notifications. @jjeroch : can you confirm this?

2022-08-03 09:31 UTC, ntruchsess requested changes

2022-08-03 09:31 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    // [Authorize(Roles = "approve_new_partner")]
why has this role-check been removed?

2022-08-03 11:35 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var catenaXAdmin = userIds.First(x => x.CompanyId == _settings.CatenaXCompanyId && x.RoleId == _settings.CxAdminRoleId).CompanyUserId;
i talked with @jjeroch about it. the requesting user should be the creator of the notification. I've already made the changes in the code

2022-08-03 11:35 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                throw new ArgumentException($"user {userName} has no assigned email");
I've edited it.

2022-08-03 11:36 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    // [Authorize(Roles = "approve_new_partner")]
was not supposed to be. it's back in

2022-08-03 13:50 UTC, ntruchsess requested changes

2022-08-03 13:50 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public IAsyncEnumerable<(Guid CompanyUserId, Guid CompanyId, Guid RoleId)> GetCompanyUsersByCompanyAndRoleIdAsync(IEnumerable<(Guid companyId, Guid userRoleId)> companyUserRoleIds) =>
As it has no references to businesscode but tests any more this method is redundant and may be removed. (Unit-tests need to be adjusted accordingly).

2022-08-03 13:50 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/appsettings.json
> +    "CatenaXCompanyId": "",
this is not in sync with the latest code

2022-08-03 13:50 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IUserRepository.cs
> +    IAsyncEnumerable<(Guid CompanyUserId, Guid CompanyId, Guid RoleId)> GetCompanyUsersByCompanyAndRoleIdAsync(IEnumerable<(Guid companyId, Guid userRoleId)> companyUserRoleIds);
obsole as of latest code-changes

2022-08-03 15:57 UTC, ntruchsess approved these changes

2022-08-03 15:57 UTC, merged