CPLP-613: implemented keycloak api call and limiting count of passwor…
catenax-ng/product-portal-backend pull request #14
Opened 2022-04-12 10:38 UTC by qxz2mqe

implemented keycloak api call and limiting count of password reset attempt

2022-04-12 17:10 UTC, ntruchsess requested changes
see my comments inline

2022-04-12 17:10 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +             return Task.FromResult(true);
incorrect use of async api - see my comment above.

2022-04-12 17:10 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +             _dbContext.SaveChangesAsync();
same here - incorrect use of async api.

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +            var response = _provisioningDBAccess.GetUserPasswordResetInfo(userId);
incorrect use of async api. Directly accessing the result will cause a synchronous wait for the async task to return the result. Use the 'await' statement here.

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +            return Task.FromResult(userPasswordReset);
please use the keyword 'async' in the methods signature and just return userPasswordReset as it is. The compiler will automatically wrap it in a Task-object. (It is required to make use of the async keywork in the methods signature as soon you make use of the await statement within the method which you need to do to avoid the synchronous wait on 'response.Result'.
This is a multiuser, multithreaded program. Any syncronous wait on an asynchronous result is strictly forbidden as it may cause issues with responsitivness. Just use google search for 'dotnet async await' and read the docs.

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +          if(string.IsNullOrEmpty(userInfo.Result.ResetCount.ToString())||userInfo.Result.ResetCount==0)
same as above - access Result in synchronous way is forbidden. Please use await to execute the method asynchronously.

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +          var userInfo = GetUserPasswordResetInfo(Guid.Parse(userId));
same as above - please use type string for userId

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +           _provisioningDBAccess.SaveUserPasswordResetInfo(Guid.Parse(userId),DateTime.Now,val);//insert record
same as above - no guid here

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +          else if(userInfo.Result.ResetCount >0)
synchronous use of Result is forbidden.

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                _provisioningDBAccess.SetUserPassword(Guid.Parse(userId),val);
incorrect use of asynchronous method. You must use 'await' to ensure the method is actually executed asynchronously.

2022-04-12 17:10 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                 _provisioningDBAccess.SetUserPassword(Guid.Parse(userId),DateTime.Now,1);
same as before - use 'await'!

2022-04-13 04:19 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +                .Where(x=>x.UserEntityId.ToString().ToLower() == userId.ToString().ToLower())
UserEntityId data type of Entities 'UserPasswordReset' which you created was having data type of Guid.That's the reason I used Guid everywhere even in Database Table also I changed data type to uuid otherwise i had to do lot of typecasting.If still I have to change the datatype then all the places i can use the string but the entities you created also have to change

2022-04-13 07:40 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +                .Where(x=>x.UserEntityId.ToString().ToLower() == userId.ToString().ToLower())
you are right - that was my fault. I forgot to rename this in the database when it was renamed in the portal-scheme. I did change this both in the database (see https://github.com/tractusx-team-portal-onboarding/devenv/pull/9 )
and in your code (see https://github.com/catenax-ng/product-portal-backend/pull/15 )
Please review both PRs and merge accordingly.

2022-04-13 07:54 UTC, ntruchsess commented
a more general remark: please ensure proper formating. Indentation shall always be 4 chars, properly aligned.

2022-04-13 08:55 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +                .Where(x=>x.UserEntityId.ToString().ToLower() == userId.ToString().ToLower())
Fixed

2022-04-13 08:56 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +                _dbContext.SaveChangesAsync();
Fixed

2022-04-13 08:56 UTC, qxz2mqe commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +             _dbContext.SaveChangesAsync();
https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed

2022-04-13 08:56 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +            var response = _provisioningDBAccess.GetUserPasswordResetInfo(userId);
https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed

2022-04-13 08:57 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +          var userInfo = GetUserPasswordResetInfo(Guid.Parse(userId));
_https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed_

2022-04-13 08:57 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +           _provisioningDBAccess.SaveUserPasswordResetInfo(Guid.Parse(userId),DateTime.Now,val);//insert record
https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed

2022-04-13 08:57 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +          else if(userInfo.Result.ResetCount >0)
https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed

2022-04-13 08:57 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                _provisioningDBAccess.SetUserPassword(Guid.Parse(userId),val);
https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed

2022-04-13 08:57 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +                 _provisioningDBAccess.SetUserPassword(Guid.Parse(userId),DateTime.Now,1);
https://github.com/catenax-ng/product-portal-backend/commit/55b2caecd43d09206f372316dfbc138362225952  

Fixed

2022-04-25 18:24 UTC, ntruchsess requested changes

2022-04-25 18:24 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +        public async Task<UserPasswordReset> GetUserPasswordResetInfo(string userId)
This method doing a conversion of database-entity to service-model seems to be completely unnecessary as it isn't called from anywhere else than from the businesslogic itself. There is no benefit to do such conversion, it's ok that the businesslogic is dealing with database-entities as they are.

2022-04-25 18:24 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +            if (string.IsNullOrEmpty(userInfo.ResetCount.ToString()) || userInfo.ResetCount == 0)
Why this conversion to string? If the type being used is int? (the nullable type) there is a method 'HasValue' to check whether the int? has been properpy initialized. If it is 'int' (not nullable, without the '?') then the int being a primitive type will have a value and cannot be null or empty.

2022-04-25 18:24 UTC, ntruchsess commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/Models/UserPasswordReset.cs
> +using System;
From my point of view this class is redundant as it never crosses the boundary in between controller and businesslogic.

2022-04-25 18:24 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +                await _dbContext.UserPasswordResets.AddAsync
I did resolve this.

2022-04-25 18:25 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
> +                await _dbContext.SaveChangesAsync();
I did fix this.

2022-04-26 07:55 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/BusinessLogic/UserAdministrationBusinessLogic.cs
> +            if (string.IsNullOrEmpty(userInfo.ResetCount.ToString()) || userInfo.ResetCount == 0)
This method has been removed

2022-04-26 07:55 UTC, qxz2mqe commented on src/useradministration/CatenaX.NetworkServices.UserAdministration.Service/Models/UserPasswordReset.cs
> +using System;
This class has been deleted

2022-04-27 08:17 UTC, ntruchsess approved these changes
Approved as discussed :-)

2022-04-27 08:17 UTC, merged