cplp 1151 and 1152 - api(refactoring) response to show the user assigned roles per app
catenax-ng/product-portal-backend pull request #142
Opened 2022-07-28 09:37 UTC by Akshay-Chaudhari-BMW

refactoring api response to show the user assigned roles per app.

2022-07-28 11:36 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    .Select(app => new CompanyUserAssignedRoleDetails(
As discussed today Create Record Instead of Class for CompanyUserAssignedRoleDetails

2022-07-28 14:28 UTC, ntruchsess requested changes
please pull once before working on my comment - I did commit the refactoring of CompanyUserAssingedRoleDetails to record (as suggested by @qxz2mqe Majid)

2022-07-28 14:28 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                companyUser.Company!.CompanyAssignedApps
that data is not being returned by the call to _userRepository.GetUserWithCompanyIdpAsync. Actually below selection-logic should be included in the query to run on the database.
Actually the query currently includes the whole entity Company whereas we only need the companies name and assigned apps. Please take this into account when refactoring the query.

2022-07-28 14:28 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    .Select(app => new CompanyUserAssignedRoleDetails(
done

2022-07-29 13:21 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                companyUser.Company!.CompanyAssignedApps
resolved

2022-07-29 14:31 UTC, ntruchsess commented
The query now returns all roles of all activly subscribed apps regardless of whether they are assigned to that  user or not. So to say the 'assignable roles'.
It rather should return the roles that both are assigned to that user and are roles of apps with active subscription for the users company.

2022-07-29 14:33 UTC, ntruchsess requested changes
The query now works but returns other data than being asked for in CPLP-1151 / CPLP-1152

It returns all roles of all activly subscribed apps regardless of whether they are assigned to that user or not. So to say the 'assignable roles'.
It rather should return the roles that both are assigned to that user and are roles of apps with active subscription for the users company.

2022-08-01 12:54 UTC, Akshay-Chaudhari-BMW commented
resolved

2022-08-02 06:32 UTC, ntruchsess approved these changes

2022-08-02 06:32 UTC, merged