feature/cplp 805 get all app
catenax-ng/product-portal-backend pull request #148
Opened 2022-08-02 07:19 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-805

2022-08-02 14:21 UTC, jjeroch requested changes

2022-08-02 14:21 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// Get app data for user own company
Summary to be updated. That is quite confusing like that. Please call it "Get all company owned apps"

2022-08-02 14:21 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="200">Returns the list of apps of current user.</response>
Th response should be not the user apps, but the apps of the company to which the user is assigned
Adjustment needed: "Returns list of apps owned by the user assigned company."

2022-08-02 14:21 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <remarks>Example: GET: /api/apps/owncompany/app</remarks>
are we responding several apps? Yes right, I suggest to call it "apps" instead of "app"

2022-08-02 14:21 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="400">If sub claim is empty/invalid.</response>
@qxz2mqe please add here a more specific message. E.g. add the exact sub claims which you are referring to

2022-08-02 14:21 UTC, jjeroch commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                 .Select(app => new AppDataProvider
@qxz2mqe the reference to "APPDataProvider" is not fully clear. Can you shortly explain this line?

2022-08-03 05:17 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="200">Returns the list of apps of current user.</response>
fixed

2022-08-03 05:17 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <remarks>Example: GET: /api/apps/owncompany/app</remarks>
fixed

2022-08-03 05:17 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="400">If sub claim is empty/invalid.</response>
fixed

2022-08-03 05:24 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                 .Select(app => new AppDataProvider
AppDataProvider is Model for app data. I thought  this name for model as closed one because other names like AppData, AppDetailsData ,AppProviderDetailsData already in use. If you have some other name please suggest I will change it

2022-08-03 09:36 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                 .Select(app => new AppDataProvider
maybe 'AllAppData' or 'AllAppDetails' (as it is for get 'get all apps' endpoint)?

2022-08-03 09:41 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="200">Returns the list of apps of current user.</response>
@jjeroch just for clarification: 'all my company owned apps': is this referring to the apps that have been purchased by the current users company, or is this referring to the apps that are being provided by the current users company being the provider_company of the app?

current implementation will return the apps that are provided by the current users company)

2022-08-03 09:55 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                 .Select(app => new AppDataProvider
fixed:-renamed as AllAppData

2022-08-04 07:49 UTC, ntruchsess commented
technically this PR is fine, but I cannot say whether it's doing what it is supposed to do:

@jjeroch just for clarification: 'all my company owned apps': is this referring to the apps that have been purchased by the current users company, or is this referring to the apps that are being provided by the current users company being the provider_company of the app?

(current implementation will return the apps that are provided by the current users company)

2022-08-04 10:51 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="200">Returns the list of apps of current user.</response>
@ntruchsess  right, its the view of the app provider, we want to have all the apps where my organization/company is listed as "provider"

2022-08-04 10:53 UTC, jjeroch commented
> technically this PR is fine, but I cannot say whether it's doing what it is supposed to do:
> 
> @jjeroch just for clarification: 'all my company owned apps': is this referring to the apps that have been purchased by the current users company, or is this referring to the apps that are being provided by the current users company being the provider_company of the app?
> 
> (current implementation will return the apps that are provided by the current users company)

That sounds good. This API will be relevant for app providers to be able to manage all apps which they are offering on the marketplace. So we want to see all apps where my company is mentioned as app provider

2022-08-04 10:54 UTC, jjeroch commented
@ntruchsess my findings are solved, I will approve from my side the pr. However would only merge when you are approving as well

2022-08-04 10:55 UTC, jjeroch approved these changes

2022-08-04 11:35 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="200">Returns the list of apps of current user.</response>
as discussed I did adjust the path as /api/apps/provided

2022-08-04 12:19 UTC, ntruchsess approved these changes

2022-08-04 12:19 UTC, merged