Create new app
catenax-ng/product-portal-backend pull request #149
Opened 2022-08-02 07:21 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-827

2022-08-02 09:00 UTC, ntruchsess requested changes

2022-08-02 09:00 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/InputModels/AppRequestModel.cs
> +        UseCaseIds = new HashSet<Guid>();
What is this good for? A non-nullable property of a data-transfer-object shall be initialized as mandatory argument to the public constructor

2022-08-03 07:24 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +        if (appRequestModel.Descriptions.Select(x => x.LanguageCode) == null)
fixed

2022-08-03 07:24 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/InputModels/AppRequestModel.cs
> +public class AppRequestModel
fixed

2022-08-03 07:26 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/InputModels/AppRequestModel.cs
> +    public virtual ICollection<Guid> UseCaseIds { get; set; }
fixed-not require as it is moved to record

2022-08-03 07:26 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            throw new NotFoundException($"Language Code does not exist");
fixed

2022-08-03 07:26 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/InputModels/AppRequestModel.cs
> +        UseCaseIds = new HashSet<Guid>();
fixed:- not require as it is moved to record

2022-08-03 09:30 UTC, ntruchsess approved these changes

2022-08-03 09:30 UTC, merged