cplp- 1219 - get all service account roles.
catenax-ng/product-portal-backend pull request #159
Opened 2022-08-04 14:35 UTC by Akshay-Chaudhari-BMW

get all service account roles.

2022-08-04 16:34 UTC, ntruchsess requested changes

2022-08-04 16:34 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ServiceAccountSettings.cs
> +                throw new Exception($"{nameof(ServiceAccountSettings)}: {nameof(x.ClientId)} must not be null or empty");
To resolve the code-smell please use the recently introduced ConfigurationException in namespace CatenaX.NetworkServices.Framework.ErrorHandling

2022-08-05 09:11 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ServiceAccountSettings.cs
> +                throw new Exception($"{nameof(ServiceAccountSettings)}: {nameof(x.ClientId)} must not be null or empty");
resolved

2022-08-10 07:53 UTC, jjeroch commented
approving, request from Norbert was incorporated, we can still do updates later but dont want to stop the pr

2022-08-10 07:54 UTC, jjeroch approved these changes

2022-08-10 08:10 UTC, merged