Feature/cplp 782 own identityprovider details
catenax-ng/product-portal-backend pull request #161
Opened 2022-08-05 13:08 UTC by ntruchsess

2022-08-09 14:02 UTC, Phil91 requested changes
I really like the stream approach for the files

2022-08-09 14:49 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public Task<Guid> GetOwnCompanyId(string iamUserId) =>
Any suggestions on how to do that which will not result in longandugly method-names?
Btw: doing the check with 'is default' is seen as a code-smell by sonar as the keyword 'default' and ask to compare against Guid.Empty() instead.

2022-08-09 14:50 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IdentityProviderSettings.cs
> +        new ConfigurationValidation<IdentityProviderCsvSettings>()
:-)

2022-08-09 17:16 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/IdentityProviderManager.cs
> +    private static readonly IReadOnlyDictionary<string,IamIdentityProviderClientAuthMethod> IdentityProviderClientAuthTypesIamClientAuthMethodDictionary = new Dictionary<string,IamIdentityProviderCli
implemented. Geht super-easy mit der Erweiterungsmethode ToImmutableDictionary() im namespace System.Collections.Immutable :-)

2022-08-09 21:17 UTC, jjeroch commented
@ntruchsess  & @Phil91 regarding the sonar finding, lets limit the upload file size to 800 KB.
I tried a file with over 10k users and have not reached the 1 MB. This file size is already crazy huge and normally a company would very unlikely have a such a huge file.....and if we should really get to this scenario, likely there is actually a migration needed with the operation team instead of doing the user migration with a csv in real time.

2022-08-10 06:44 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public Task<Guid> GetOwnCompanyId(string iamUserId) =>
As discussed the developer using the repository method should know that a guid is a value type and because of that should compare it to Guid.Empty()

2022-08-10 07:58 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/IdentityProviderController.cs
> +public class IdentityProviderController : ControllerBase
swagger documentation added

2022-08-10 08:15 UTC, Phil91 approved these changes

2022-08-10 08:31 UTC, merged