cplp- 1197 - refactoring api - search app users
catenax-ng/product-portal-backend pull request #165
Opened 2022-08-08 10:07 UTC by Akshay-Chaudhari-BMW

refactoring api - search all app users

2022-08-09 14:43 UTC, ntruchsess requested changes

2022-08-09 14:43 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
> +                .Where(companyUser => firstName != null ? EF.Functions.ILike(companyUser!.Firstname, $"{firstName}%") : true
using the string-template is prone to injection if the argument contains any characters that have a special meaning in this context (like firstName containing the character %). Those Characters must either be removed or escaped before building the pattern. Use the 3-parameter version of ILike which allows to specify an escape-paramter and replace all occurences of wildcard-characters (%,_,[,],^) with their escaped version. (Also see: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctionsextensions.like?view=efcore-6.0 )

2022-08-11 08:46 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
> +                .Where(companyUser => firstName != null ? EF.Functions.ILike(companyUser!.Firstname, $"{firstName}%") : true
I used Trim function to escape special characters.

2022-08-11 08:49 UTC, jjeroch commented
@Phil91  can you please take over the review finalization

2022-08-11 09:21 UTC, Phil91 requested changes
Just a small adjustment

2022-08-11 09:21 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
> +        char[] MyChar = { '%', '_', '[', ']', '^' };
should be myChar

2022-08-11 09:53 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
> +        char[] MyChar = { '%', '_', '[', ']', '^' };
renamed

2022-08-11 12:02 UTC, Phil91 approved these changes

2022-08-11 14:21 UTC, merged