feature/CPLP-830 update an app details
catenax-ng/product-portal-backend pull request #175
Opened 2022-08-17 09:25 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-830

2022-08-22 08:23 UTC, Phil91 requested changes

2022-08-22 08:23 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +        var app = await _context.Apps
since we're attaching the app to the database we don't need to select ProviderUri, ContactEmail and ContactNumber

2022-08-23 10:02 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/InputModels/AppEditableDetail.cs
> +    public AppEditableDetail(IEnumerable<Localization> descriptions, IEnumerable<string> images, string? providerUri, string? contactEmail, string? contactNumber)
I tried it with record but I was getting build error of initialization and setting properties

2022-08-23 10:04 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +}
Can yo please mention the line number after which line number you want line break?

2022-08-23 10:06 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppUpdateModel.cs
> +public class AppUpdateModel
I tried but i was getting build error maybe due to we are trying to update the entity . I was getting indexer and initialization with can't set the property

2022-08-23 10:23 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
As mentioned in user story After the validations have been successfully passed, , portal.app_descriptions (enhance existing data record. In case long description is already added, please overwrite the content)

2022-08-23 12:24 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/App.cs
> +
fixed

2022-08-23 12:24 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +    public async Task<AppUpdateModel> GetAppByIdAsync(Guid appId, string userId)
fixed

2022-08-23 12:24 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppUpdateModel.cs
> +public class AppUpdateModel
fixed

2022-08-23 12:25 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private async Task EditAppAsync(Guid appId, AppEditableDetail updateModel, string userId)
fixed

2022-08-23 12:25 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/InputModels/AppEditableDetail.cs
> +    public AppEditableDetail(IEnumerable<Localization> descriptions, IEnumerable<string> images, string? providerUri, string? contactEmail, string? contactNumber)
fixed

2022-08-23 12:25 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +        var app = await _context.Apps
fixed

2022-08-23 12:26 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
As of now I have added try catch to handle duplicate key exception and show custom message

2022-08-24 05:41 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
Is it correct like that? I understand the userstory like, if we have the key already (which is the language code), we should update it. now we would throw an error correct?

2022-08-24 05:42 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +}
line 71, at the end of the file

2022-08-24 14:54 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
Quick update from my side: thats correct. If they key is existing already with a description, the description should get updated.
An error would be wrong

2022-08-25 06:06 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
fixed

2022-08-29 19:55 UTC, ntruchsess requested changes

2022-08-29 19:55 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
.Select(a.AppDescriptions.Select(d => new AppDescription()), a.AppDetailsImages.Select(adi => new AppDetailImage(..)))
there seems to be some redundancy here that should be eliminated.
Also AppDetailImage is defined incorrectly - the Constructor must include the primary key (property Id). It's both not defined as nullable (being the primary key) and to be consistent with other entities we create the Guid client-side, not in the database.

2022-08-29 19:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var (description, images) = await _portalRepositories.GetInstance<IAppRepository>().GetAppByIdAsync(appId, userId).ConfigureAwait(false);
retrieving the whole descriptions from the database just to check for their existence is very inefficient. The Any() should be done on database-side within the query.

2022-08-29 19:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +namespace CatenaX.NetworkServices.App.Service.BusinessLogic;
consider renaming this namespace to 'CatenaX.NetworkServices.Apps.Service.BusinessLogic' to avoid the Name-clash on 'App' (being the entity-type)

2022-08-29 19:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +           {
again: indentation is 4 chars. Please ensure proper formating of all changed code as indentation is incorrect in other places as well.

2022-08-29 19:55 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs
> +
What is this newline good for? Please do not commit useless whitespace-only changes as those files show up as changed in your PR for no good reason.

2022-08-29 19:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            _portalRepositories.Attach(new CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.AppDescription(appId, item.LanguageCode), appdesc =>
using the full-qualified classname is not required here as the Entities-namespace is included. The nameclash is on App, not on AppDescription

2022-08-30 05:15 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            _portalRepositories.Attach(new CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.AppDescription(appId, item.LanguageCode), appdesc =>
fixed

2022-08-30 05:15 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs
> +
fixed

2022-08-30 05:15 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +           {
fixed

2022-08-30 05:15 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +namespace CatenaX.NetworkServices.App.Service.BusinessLogic;
fixed

2022-08-30 05:15 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var (description, images) = await _portalRepositories.GetInstance<IAppRepository>().GetAppByIdAsync(appId, userId).ConfigureAwait(false);
fixed

2022-08-30 05:15 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
fixed

2022-08-30 05:15 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppDescription.cs
> +    public string? DescriptionLong { get; set; }
fixed

2022-08-31 10:41 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
Cannot see any fix to AppDetailImage? Please add the property 'Id' to the Constructor of AppDetailImage and add a method 'CreateAppDetailImage' to AppRepository that passes Guid.NewGuid() as Id to the Constructor (use e.g. 'CreateApp' as template). Then use this new CreateAppDetailImage instead of 'new AppDetailImage(...)' in the businesslogic.

2022-08-31 10:50 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
I am not sure why it is not reflecting. I have changed it now as below
 public  Task<Guid> GetAppByIdAsync(Guid appId, string userId)
    =>
        _context.Apps
            .Where(a => a.Id == appId && a.AppStatusId == AppStatusId.CREATED
            && a.ProviderCompany!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == userId))
            .Select(a => a.Id)
            .SingleOrDefaultAsync();

2022-08-31 10:51 UTC, ntruchsess requested changes

2022-08-31 10:51 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var appId= await _portalRepositories.GetInstance<IAppRepository>().GetAppByIdAsync(appId, userId).ConfigureAwait(false);
That assignment hides the input-parameter 'appId'. Change the query to return Task<Boolean> by calling AnyAsync instead of 'Where + SingeOrDefaultAsync':
`    public  Task<Boolean> GetAppByIdAsync(Guid appId, string userId) =>
        _context.Apps.AnyAsync(a => a.Id == appId && a.AppStatusId == AppStatusId.CREATED
            && a.ProviderCompany!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == userId));
`

2022-08-31 11:18 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var appId= await _portalRepositories.GetInstance<IAppRepository>().GetAppByIdAsync(appId, userId).ConfigureAwait(false);
fixed

2022-09-01 19:46 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +namespace CatenaX.NetworkServices.App.Service.BusinessLogic;
of course you need to rename that namespace 'CatenaX.NetworkServices.Apps' to 'CatenaX.NetworkServices.App' whereever it is being used (that includes all included namespaces).
Otherwise the clash inherently remains.

2022-09-01 19:50 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var appId= await _portalRepositories.GetInstance<IAppRepository>().GetAppByIdAsync(appId, userId).ConfigureAwait(false);
As it now doesnt return the AppId any more I suggest to rename the method to something that describes the semantecs better like IsAppProviderCompanyUserAsync or something simmilar.

2022-09-01 19:50 UTC, ntruchsess commented
fixing the conflicts would also be a good idea...

2022-09-01 19:52 UTC, ntruchsess requested changes
see my comments that I did add to the existing comments.

2022-09-02 04:27 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
I am not sure why this pull request is still showing you old code but locally I can  this method was changed as below as you suggested last time 
public  Task<bool> GetAppByIdAsync(Guid appId, string userId)
    =>
        _context.Apps
            .AnyAsync(a => a.Id == appId && a.AppStatusId == AppStatusId.CREATED
            && a.ProviderCompany!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == userId));

2022-09-02 04:32 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +namespace CatenaX.NetworkServices.App.Service.BusinessLogic;
This was also fixed last time. Those changes are showing on my local code base but I dont know why in PR showing old code

2022-09-02 04:33 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
PR also showing my changes

2022-09-02 04:33 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +namespace CatenaX.NetworkServices.App.Service.BusinessLogic;
PR also showing my changes

2022-09-02 05:26 UTC, qxz2mqe commented
Resolved conflicts and merged main branch to CPLP-830

2022-09-02 06:41 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId,d.LanguageShortName,d.DescriptionLong,d.DescriptionShort)),
In my latest comment I was **not** refering to method GetAppByIdAsync, I was refering to the **entity AppDetailImage**.

2022-09-02 06:56 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +namespace CatenaX.NetworkServices.App.Service.BusinessLogic;
you need to go into **all** files that relate to namespaces starting with CatenaX.NetworkServices.App and rename App to Apps.
E.g. Catenax.NetworkServices.App.Service.InputModels.AppEditableDetail is still in the old namespace.

2022-09-02 06:57 UTC, ntruchsess requested changes
see my additions to existing comments

2022-09-02 11:16 UTC, ntruchsess commented
@qxz2mqe just did merge main resolve the conflict in program.cs for you. Please pull accordingly

2022-09-02 12:03 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var appId= await _portalRepositories.GetInstance<IAppRepository>().GetAppByIdAsync(appId, userId).ConfigureAwait(false);
I did fix my own comment renaming the method to IsAppProviderUserAsync

2022-09-02 13:19 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
in case a description is not yet existing it shall be added. The current code that just uses 'Attach' will fail in this case as the entity having a full primary key is treated as preexisting by the framework which will lead to an update-statement that cannot succeed if the entity is not existing in the database.
For Descriptions that do not yet exist a new Entity must be added to the Database by using 'Add'-method (instead of Attach).
@qxz2mqe I did prepare a query GetAppDetailsForUpdateAsync in the AppRepository for you which is being called by the businesslogic. Please adjust the code so it descriptions and images only when they do not exisit and updates them (using Attach) if they do exist.

2022-09-02 13:21 UTC, ntruchsess commented
@qxz2mqe : I did cleanup and merge resolving the conflicts and fixed own my outstanding comments.

But regarding the intended functionality it will not cover all cases:

in case a description is not yet existing it shall be added. The current code that just uses 'Attach' will fail in this case as the entity having a full primary key is treated as preexisting by the framework which will lead to an update-statement that cannot succeed if the entity is not existing in the database.
For Descriptions that do not yet exist a new Entity must be added to the Database by using 'Add'-method (instead of Attach).
I did prepare a query GetAppDetailsForUpdateAsync in the AppRepository for you which is being called by the businesslogic. Please adjust the code so it descriptions and images only when they do not exisit and updates them (using Attach) if they do exist.

2022-09-02 13:25 UTC, ntruchsess requested changes
@qxz2mqe : I did cleanup and merge resolving the conflicts and fixed my own outstanding comments. So please pull before proceeding.

Regarding the intended functionality the current code will not cover all cases:

in case a description is not yet existing it shall be added. The current code that just uses 'Attach' will fail in this case as the entity having a full primary key is treated as preexisting by the framework which will lead to an update-statement that cannot succeed if the entity is not existing in the database.
For Descriptions that do not yet exist a new Entity must be added to the Database by using 'Add'-method (instead of Attach).
I did prepare a query GetAppDetailsForUpdateAsync in the AppRepository for you which is being called by the businesslogic. Please adjust the code so it descriptions and images only when they do not exisit and updates them (using Attach) if they do exist.

I did prepare the query 'GetAppDetailsForUpdateAsync' in AppRepository for you, in addition to the boolean values required for the pre-checks it contains the languagecodes of existing descriptions and imageUrls of existing images. Please adjust the code in method EditAppAsync accordingly.

2022-09-06 07:56 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            newApp.AppDescriptions.Add(new AppDescription(appId, item.LanguageCode, item.LongDescription, result.Descriptions.Where(x => x.AppId == appId).Select(x => x.DescriptionShort).ElementAt(cu
follow-up discussion: https://github.com/catenax-ng/product-portal-backend/pull/175#pullrequestreview-1094866727

2022-09-06 13:19 UTC, qxz2mqe commented
Regarding the intended functionality the current code will not cover all cases:
@ntruchsess I have implemented the change. Please look into that

2022-09-07 09:55 UTC, ntruchsess requested changes

2022-09-07 09:55 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppDescription.cs
> +    public AppDescription(Guid appId, string languageShortName, string descriptionLong)
this constructor is useless and not being referenced, ->remove
(please also remove the private constructor in line 7 as it is also not being referenced)

2022-09-07 09:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private void UpsertRemoveAppDetailImage(Guid appId, AppEditableDetail updateModel, IEnumerable<string> appImgUrl,IEnumerable<Guid> appImgId, IAppRepository appRepository)
Do not pass more information to a method than required - so pass updateModel.Images as parameter not the entrire updateModel

2022-09-07 09:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +                _portalRepositories.Remove(new AppDetailImage(appImgId.ElementAt(currentIndex)));
Same as for the descriptions: refering to the order of database-entries is not reliable and will eventually produce unexpected results.

2022-09-07 09:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/InputModels/AppEditableDetail.cs
> +public record Localization(string? LanguageCode, string? LongDescription);
LanguageCode shall be a non-nullable String
(You cannot add, delete or modify a description without LanguageCode)

2022-09-07 09:55 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            if (string.IsNullOrWhiteSpace(item.LanguageCode) && appResult.Any())
Passing null or whitespace as languagecode to mark entries to be deleted is a very bad design choice as the entry to be deleted cannot be identified unambiguously with the primary key missing.
Relying on the order of entries in the request matching the order of entries in the database is likely to produce undesired results. Keep in mind that the database-records are not being locked and might have changed in the meantime.

2022-09-07 11:35 UTC, ntruchsess commented
@qxz2mqe I did merge main (containing the rename of App to Offer from CPLP-1212), so please pull before proceeding

2022-09-07 12:45 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/InputModels/AppRequestModel.cs
> +public record AppRequestModel(string? Title, string Provider, string? LeadPictureUri, Guid? ProviderCompanyId, ICollection<string> UseCaseIds, ICollection<LocalizedDescription> Descriptions, ICollect
fixed

2022-09-07 12:46 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                    a.AppDetailImages.Select(image => image.ImageUrl),
fixed

2022-09-07 12:47 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +                _portalRepositories.Remove(new AppDetailImage(appImgId.ElementAt(currentIndex)));
first part fixed  second part not sure what is expected here-- order of database-entries

2022-09-07 12:48 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/InputModels/AppEditableDetail.cs
> +public record Localization(string? LanguageCode, string? LongDescription);
fixed

2022-09-07 12:53 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            if (string.IsNullOrWhiteSpace(item.LanguageCode) && appResult.Any())
not sure what is expected here because at line 92 I am not passing any null or empty value. during remove passing languagecode and appid

2022-09-08 13:51 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppDescription.cs
> +    public AppDescription(Guid appId, string languageShortName, string descriptionLong)
fixed

2022-09-08 13:51 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private void UpsertRemoveAppDetailImage(Guid appId, AppEditableDetail updateModel, IEnumerable<string> appImgUrl,IEnumerable<Guid> appImgId, IAppRepository appRepository)
fixed

2022-09-08 13:51 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +                _portalRepositories.Remove(new AppDetailImage(appImgId.ElementAt(currentIndex)));
fixed

2022-09-08 13:52 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            if (string.IsNullOrWhiteSpace(item.LanguageCode) && appResult.Any())
fixed

2022-09-08 17:45 UTC, ntruchsess requested changes

2022-09-08 17:45 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +                    if (string.IsNullOrWhiteSpace(item.LongDescription) && string.IsNullOrWhiteSpace(item.ShortDescription) && LanguageShortNames.Any())
That 'LanguageShortNames.Any()' without any further condition doesn't make any sense. In our meeting today we did agree on deleting those descriptions from the database that do not have an entry for that languagecode in the request, so please implement that. It's pretty much the same as in UpsertRemoveAppDetailImage plus the update-part for languagecodes that are both in database and request (there is 'IEnumerable.Intersect' or 'Enumerable.IntersectBy' to determine that range).

2022-09-08 17:45 UTC, ntruchsess commented
I did merge main resolving the conflicts, so please pull before proceeding.

2022-09-09 12:08 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/ViewModels/AppEditableDetail.cs
> +public record Localization(string LanguageCode, string? LongDescription, string? ShortDescription);
fixed

2022-09-09 12:08 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +                    if (string.IsNullOrWhiteSpace(item.LongDescription) && string.IsNullOrWhiteSpace(item.ShortDescription) && LanguageShortNames.Any())
fixed

2022-09-09 13:10 UTC, ntruchsess approved these changes
I did some polishing (formating, renaming) for readability and added checks that would suppress updates of properties that did not change. Also had to merge main to resolve new conflicts. Can you please pull and double-check? From my point of view it's ready to merge then.

2022-09-10 07:13 UTC, qxz2mqe commented
It looks fine

2022-09-12 07:15 UTC, merged