feature/cplp-1378 app document update
catenax-ng/product-portal-backend pull request #179
Opened 2022-08-19 10:37 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1378

2022-08-21 20:27 UTC, jjeroch commented
@qxz2mqe  can you please fix the security hotspot. Its not a critical finding, but would be good to still fix it or to include and comment in case this is a false "positive"

2022-08-22 08:23 UTC, Phil91 requested changes
As discussed in the review, let's wait with creating the Migration for the database change until the pending database changes are merged

2022-08-22 08:23 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +}
please add a line break

2022-08-22 08:23 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +public class AppReleaseRepository : IAppReleaseRepository
I'd suggest moving the GetAppByIdAsync to the AppRepository, maybe rename it with ...AsAppUpdateModel.
and rename the AppReleaseRepository to AppAssignedDocumentsRepository.

2022-08-23 13:51 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +}
Could you please provide me the line number after which i have to give a line break

2022-08-23 13:53 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +public class AppReleaseRepository : IAppReleaseRepository
Moved GetAppByIdAsync to the AppRepository, All the method/action i am writing in AppReleaseRepository  is related to appreleaseprocess so i think naming is compatible with the feature we want to implement

2022-08-24 05:30 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +}
sorry, was at the end of the file

2022-08-24 05:36 UTC, Phil91 approved these changes

2022-08-24 05:57 UTC, Phil91 requested changes
Just recognized that there are some code smells, could you take a look at them

2022-08-24 06:06 UTC, qxz2mqe commented
Yes I am looking into that but could you please let me know the timing to review script for 1378 because you have already merged the code into main. If some one pull the latest and don’t find those attribute then they might get ecveption

From: Phil Schneider ***@***.***>
Sent: 24 August 2022 11:27
To: catenax-ng/product-portal-backend ***@***.***>
Cc: AKHTER MD-MAJID, ***@***.***) ***@***.***>; Mention ***@***.***>
Subject: Re: [catenax-ng/product-portal-backend] feature/cplp-1378 app document update (PR #179)


Sent from outside the BMW organization - be CAUTIOUS, particularly with links and attachments.

Absender außerhalb der BMW Organisation - Bitte VORSICHT beim Öffnen von Links und Anhängen.

________________________________

@Phil91 requested changes on this pull request.

Just recognized that there are some code smells, could you take a look at them

—
Reply to this email directly, view it on GitHub<https://github.com/catenax-ng/product-portal-backend/pull/179#pullrequestreview-1083199107>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYE7H66PNDV4VIOPBG5DYITV2W2T3ANCNFSM57AITXAQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-08-24 06:31 UTC, Phil91 commented
> 
I will. We need the migration as well

2022-08-24 06:57 UTC, Phil91 reviewed
Everything looks fine so far. The migration is missing, after that we can update devenv and merge this pr

2022-08-24 07:42 UTC, jjeroch commented
added @Akshay-Chaudhari-BMW  please inform him as soon as pr is merged, since this merge and deployment is needed for akshay to proceed on his ticcket

2022-08-24 07:45 UTC, qxz2mqe commented
https://github.com/tractusx-team-portal-onboarding/devenv/pull/111   PR Created to review script

2022-08-25 07:53 UTC, Phil91 approved these changes
Looks fine :)

2022-08-25 07:54 UTC, merged