CPLP-751 - adjust entities to match devenv PR#8
catenax-ng/product-portal-backend pull request #18
Opened 2022-04-20 16:08 UTC by ntruchsess

Adjustment of EF-Core entities to match https://github.com/tractusx-team-portal-onboarding/devenv/pull/8

2022-04-21 20:05 UTC, ntruchsess commented
snake-case maps 'Alpha2Code' to 'alpha2code', not 'alpha_2_code' so I renamed the column in the database: https://github.com/tractusx-team-portal-onboarding/devenv/pull/16

2022-04-22 08:44 UTC, ntruchsess reviewed
@wira-mms : I Did check your changes - they look fine.

2022-04-22 10:31 UTC, wira-mms requested changes

2022-04-22 10:44 UTC, ntruchsess reviewed
Datetime-relevant changes are fine and approved

2022-04-22 10:46 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +                DateTime.Now);
implementd

2022-04-22 10:48 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/IamIdentityProvider.cs
> +        public IamIdentityProvider()
of course private -> just changed it.

2022-04-22 10:49 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyApplication.cs
>          public CompanyApplication()
yes, private -> changed.

2022-04-22 10:49 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyIdentityProvider.cs
>          public CompanyIdentityProvider() {}
changed

2022-04-22 10:49 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Consent.cs
>          public Consent() {}
changed

2022-04-22 11:10 UTC, wira-mms approved these changes

2022-04-22 11:42 UTC, merged