fature/CPLP-827 create app fixed julia comments
catenax-ng/product-portal-backend pull request #182
Opened 2022-08-23 09:40 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-827

2022-08-24 05:55 UTC, Phil91 requested changes

2022-08-24 05:55 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +              (appId, Guid.Parse(uc))));
what if the conversion fails? for example user sends a request with "useCases": ["justatest" ]

2022-08-24 07:12 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +              (appId, Guid.Parse(uc))));
you are right i didn't thought about it. I will look into this

2022-08-25 11:30 UTC, Phil91 approved these changes
looks good

2022-08-25 11:31 UTC, merged