feature/cplp 833 post app roles
catenax-ng/product-portal-backend pull request #189
Opened 2022-08-25 12:08 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-833

2022-08-29 20:53 UTC, ntruchsess requested changes

2022-08-29 20:53 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
>          if (companyUserId == Guid.Empty)
line 135 'document.CopyTo(ms)' please use 'await document.CopyToAsync(ms).ConfigureAwait(false)' instead. Otherwise the service will wait for the actual file-upload to finish. (larger files will be transfered chunked-encoded which results in calling the async controller-method after receiving the the http-request-headers but for larger files that do not fit in the initial packet before the file-upload actually has finished). Copying the file synchronously is a security-thread as an attacker might send fake file-upload request that stall after sending the first package.
For the very same reason please add the CancellationToken-parameter to the both the business- and Controller-method (see e.g. https://andrewlock.net/using-cancellationtokens-in-asp-net-core-mvc-controllers/ for the reasons)

2022-08-29 20:53 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    public Task<int> UpdateAppDocumentAsync(Guid appId, DocumentTypeId documentTypeId, IFormFile document, string userId)
please add the CancellationToken to the arguments and pass on to UploadAppDoc for use in docuement.CopyToAsync(ms, cancellationToken)

2022-08-29 20:53 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/App.cs
> +
please do not commit useless whitespace-only changes as those files appear as changed in the PR for no good reason.

2022-08-29 20:53 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +    public Task<Guid> GetAppRolesAsync(Guid appId, string userId) =>
please rename this method to something that describes the result more reasonably. This query is not going to return anything being directly related to AppRoles, it returns the userid of the logged-in user in case it belongs to the provider-company of the given app.

2022-08-30 05:35 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
>          if (companyUserId == Guid.Empty)
fixed

2022-08-30 05:35 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    public Task<int> UpdateAppDocumentAsync(Guid appId, DocumentTypeId documentTypeId, IFormFile document, string userId)
fixed

2022-08-30 05:35 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/App.cs
> +
fixed

2022-08-30 05:35 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +    public Task<Guid> GetAppRolesAsync(Guid appId, string userId) =>
fixed

2022-08-31 14:51 UTC, ntruchsess requested changes

2022-08-31 14:51 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +               _context.UserRoleDescriptions.Add(
again: Indentation is 4 chars

2022-08-31 14:51 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var companyUserId = await _portalRepositories.GetInstance<IAppReleaseRepository>().GetCompanyUserIdAsync(appId, userId).ConfigureAwait(false);
companyUserId is not being used for anything else than to verify that user is linked to the appId.
A query returning Task<Boolean> would be more efficient here.
E.g.:
`    public Task<Boolean> IsProviderCompanyUserAsync(Guid appId, string userId) =>
        _context.Apps.AnyAsync(a => a.Id == appId && a.ProviderCompany!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == userId));
`
Such query would also better fit into AppRepository as it's not related to any of the app-release-process-related entities

2022-08-31 14:51 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId, d.LanguageShortName, d.DescriptionLong, d.DescriptionShort)),
to change this file (and especially this method) here for the sake of adding some whitespace is not a good idea as it is also modified in PR #175 (https://github.com/catenax-ng/product-portal-backend/pull/175/files#diff-c4b5f843ab7cf43dfa53f955cae6b7236a5c7e41ff91e14a66be6129fe62f6ae). You grow your own conflicts.

2022-09-01 10:05 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private async Task<int> UploadAppDoc(Guid appId, DocumentTypeId documentTypeId, IFormFile document, string userId, CancellationToken cancellationToken)
fixed

2022-09-01 10:05 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +               _context.UserRoleDescriptions.Add(
fixed

2022-09-01 10:06 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var companyUserId = await _portalRepositories.GetInstance<IAppReleaseRepository>().GetCompanyUserIdAsync(appId, userId).ConfigureAwait(false);
fixed

2022-09-01 10:07 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId, d.LanguageShortName, d.DescriptionLong, d.DescriptionShort)),
This space issue and old code is coming because reviewed code is not merged yet. I pulled the latest code from main branch but that reviewed code still does not reflect there

2022-09-02 13:46 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                a.AppDescriptions.Select(d => new AppDescription(appId, d.LanguageShortName, d.DescriptionLong, d.DescriptionShort)),
as it's whitespace only changes I did revert this file to latest main to avoid the conflicts with PR #175

2022-09-02 14:02 UTC, ntruchsess approved these changes

2022-09-02 14:11 UTC, merged