feature/cplp 1313-1317 db audit app & user role
catenax-ng/product-portal-backend pull request #190
Opened 2022-08-29 12:59 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1313
https://jira.catena-x.net/browse/CPLP-1317

2022-09-02 06:39 UTC, Phil91 requested changes
Since you added new code please provide at least one unit test for the following methods:

AppReleaseBusinessLogic -> AddAppUserRoleAsync
AppReleaseRepoository -> GetAppRolesAsync | CreateAppUserRole | CreateAppUserRoleDescription

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
>  }
Please add a linebreak at the end of the file

2022-09-02 06:39 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +}
Please add a linebreak at the end of the file

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Extensions/MigrationBuilderExtensions.cs
> +    private static string GetColumnName(ColumnAttribute attribute)
Could you move that behind the public methods

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/AuditEntities/AuditApp.cs
> +}
please add a linebreak at the end of the file

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/AuditEntities/AuditCompanyUserAssignedRole.cs
> +    public  DateTimeOffset DateLastChanged { get; set; }
please add linebreak at the end of the file

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/AuditEntities/AuditUserRole.cs
> +}
please add linebreak at the end of the file

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/CatenaX.NetworkServices.PortalBackend.PortalEntities.csproj
> +</Project>
please add linebreak at the end of the file

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/CatenaX.NetworkServices.PortalBackend.PortalEntities.csproj
> +    <UserSecretsId>377e9692-ccd4-476d-8852-0065c2097e2e</UserSecretsId>
what are the secrets used for?

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppDescription.cs
> +    public AppDescription(Guid appId, string languageShortName, string? descriptionLong, string? descriptionShort)
should we really have both descriptions nullable?!

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
> +            x.ToTable("audit_apps_cplp_1313_db_audit_apps");
the correct name would be audit_apps_cplp-1313-audit-app-user-role since the migration is named like that. either change the table name or the migrationname to be fitting

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
> +            x.ToTable("audit_user_roles_cplp_1313_db_audit_apps");
see comment above

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
> +
empty line can be removed

2022-09-02 06:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
> +
empty line can be removed

2022-09-02 10:31 UTC, ntruchsess requested changes

2022-09-02 10:31 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            throw new ArgumentException($"AppId must not be empty");
please use ControllerArgumentException instead

2022-09-02 10:31 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var companyUserId = await _portalRepositories.GetInstance<IAppReleaseRepository>().GetAppRolesAsync(appId, userId).ConfigureAwait(false);
same story as in PR#175 where you now have the method Task<bool> GetAppByIdAsync(Guid appId, string userId) to check whether a user is related to the app. I suggest you merge your PRs and make use of that method renaming it to something that describes the semantics better (like IsAppProviderUser)

(btw: naming a method that does not relate to roles in any way 'GetApp**Roles**Async' is not helping anyone to understand the semantics)

2022-09-02 10:31 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            var appRole = _portalRepositories.GetInstance<IAppReleaseRepository>().CreateAppUserRole(appId, indexItem.role);
don't call GetInstance within the loop, call it one and reuse the instance being returned.

2022-09-02 10:31 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
> +         _context.UserRoles.Add(
indentation 4 chars please.

2022-09-02 10:31 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
>              newApp.AppDetailImages.Add(new AppDetailImage(appId, record));
AppDetailImage is defined incorrectly - the Constructor must include the primary key (property Id). It's both not defined as nullable (being the primary key) and to be consistent with other entities we create the Guid client-side, not in the database.

Please add the property 'Id' to the Constructor of AppDetailImage and add a method 'CreateAppDetailImage' to AppRepository that passes Guid.NewGuid() as Id to the Constructor (use e.g. 'CreateApp' as template). Then use this new CreateAppDetailImage instead of 'new AppDetailImage(...)' in the businesslogic.

2022-09-02 10:31 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                       a.AppDetailImages.Select(adi => new AppDetailImage(appId, adi.ImageUrl))
you are inserting whitespace in code you modify in other PRs in parallel. Have fun resolving the conflicts.

2022-09-02 10:31 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppDescription.cs
> +    public AppDescription(Guid appId, string languageShortName, string? descriptionLong, string? descriptionShort)
I did have the same remark in PR #175 where you did revert that change of nullability. Why is it re-appearing here?

2022-09-02 11:45 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
>  }
I can write the unit test method but I dont think it is scope of this story because expected estimation was only two days to complete these four task(story) related to Db Audit. Apart from that there are already couple of open issues which I have to complete. I will talk to julia regarding writing unit test for those methods if I get additional time

2022-09-02 14:37 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
>              newApp.AppDetailImages.Add(new AppDetailImage(appId, record));
did fix this in other PR

2022-09-02 14:38 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            throw new ArgumentException($"AppId must not be empty");
did fix this in other PR

2022-09-02 14:40 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var companyUserId = await _portalRepositories.GetInstance<IAppReleaseRepository>().GetAppRolesAsync(appId, userId).ConfigureAwait(false);
fixed in other PR

2022-09-02 14:40 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            var appRole = _portalRepositories.GetInstance<IAppReleaseRepository>().CreateAppUserRole(appId, indexItem.role);
fixed in other PR

2022-09-02 15:20 UTC, ntruchsess requested changes

2022-09-02 15:20 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppDescription.cs
> +    public AppDescription(Guid appId, string languageShortName, string? descriptionLong, string? descriptionShort)
This change is in conflict with PR #175. As the change to nullablility of descriptionLong and descriptionShort is also in the Migration this must be resolved first. I suggest to merge with branch feature/CPLP-830-put-app-detail and recreate the Migration afterwards.

2022-09-02 15:20 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220902094949_CPLP-1313-AuditAppUserRole.cs
> +            migrationBuilder.AlterColumn<string>(
This change (nullability of description_short and description_long) is in conflict with PR https://github.com/catenax-ng/product-portal-backend/pull/175. I suggest to merge with branch feature/CPLP-830-put-app-detail and recreate the Migration afterwards.
The alternative is to wait for PR #175 to be finished and pull main after it's merged. Then recreate the migration

2022-09-07 10:43 UTC, ntruchsess commented
As the audit-facility is being reworked I did reset this PR to draft.

2022-10-11 10:19 UTC, ntruchsess commented
from my understanding this PR is obsoleted by https://github.com/catenax-ng/product-portal-backend/pull/257 and can be closed?

2022-10-13 12:43 UTC, ntruchsess commented
CPLP-1313 has has finally been implemented in https://github.com/catenax-ng/product-portal-backend/pull/267
@qxz2mqe Is there anything left in this PR that you want to transfer or reuse? If not please close this one.

2022-10-18 12:36 UTC, closed without merging