CPLP-1212 services
catenax-ng/product-portal-backend pull request #191
Opened 2022-08-30 14:45 UTC by Phil91

2022-08-31 08:19 UTC, Phil91 commented
@ntruchsess in my opinion it will make sense to finish the #183 first. The Vulnerability, Security Hotspot and duplication will disappear than.

2022-09-02 19:47 UTC, ntruchsess requested changes

2022-09-02 19:47 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                 app.Name ?? Constants.ErrorString,
please to the mapping to ErrorString in the businesslogic. Doing it on the database-server just enlarges to payload with no benefit. (And take care of propper formating: indentation is 4 chars)

2022-09-02 19:47 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ILanguageRepository.cs
> +    Task<List<string>> GetLanguageCodesUntrackedAsync(ICollection<string> languageCodes);
in the repository we return IAsyncEnumerable, any materialization to list shall be done in businesslogic.

2022-09-02 19:47 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            _dbContext.CompanyUsers.Where(x => x.IamUser!.UserEntityId == iamUserId || x.Id == salesManagerId)
please do propper formating. indentation is 4 chars, not 8.

2022-09-02 19:47 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220816061525_CPLP-1213-AddServices.cs
> +            // migrationBuilder.AddAuditTrigger<AuditService>("audit_services_cplp_1213_add_services");
no commented code in the git-repo, please delete

2022-09-02 19:47 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppType.cs
> +public class AppType
We should consider a rename of the entity-base-name 'App' to something more generic, like 'offer'. Both App and Services do have some properties in common which belong to the base-entiy. Some properties will reside in type-spefic tables (for apps and services) that are just linked to the base entity.
AppType would then be renamed to 'OfferType'.
Maybe you have a better suggestion than 'offer'?

2022-09-02 19:47 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Service.Service/BusinessLogic/ServiceSettings.cs
> +            .ValidateOnStart();
does ValidateOnStart() do anything if there is no metadata-validation triggered and no custom validation attached?

2022-09-04 08:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/AppType.cs
> +public class AppType
Offer was the first thing which came to my mind as well. an alternative would be component but that's not really matching in my opinion. I've talked to Julia before she went on vacation. we wanted to postpone the renaming of the app. maybe we can have a short call about that.

2022-09-04 08:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220816061525_CPLP-1213-AddServices.cs
> +            // migrationBuilder.AddAuditTrigger<AuditService>("audit_services_cplp_1213_add_services");
removed

2022-09-04 08:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            _dbContext.CompanyUsers.Where(x => x.IamUser!.UserEntityId == iamUserId || x.Id == salesManagerId)
done

2022-09-04 08:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ILanguageRepository.cs
> +    Task<List<string>> GetLanguageCodesUntrackedAsync(ICollection<string> languageCodes);
done

2022-09-04 08:39 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
> +                 app.Name ?? Constants.ErrorString,
done

2022-09-04 08:40 UTC, Phil91 commented on src/services/CatenaX.NetworkServices.Service.Service/BusinessLogic/ServiceSettings.cs
> +            .ValidateOnStart();
Tested it with removing the ApplicationsMaxPageSize from the appsettings (it's the only place where it is defined), no error was thrown. I've added the ValidateDataAnnotations

2022-09-05 21:37 UTC, ntruchsess requested changes

2022-09-05 21:37 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Service.Service/BusinessLogic/IServiceBusinessLogic.cs
> +    Task AddServiceSubscription(Guid serviceId, string iamUserId);
shouldn't this return the id of the newly created ordersubscription so the endpoint might return a CreatedAt-response pointing to the new subscription?

2022-09-05 21:37 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Service.Service/CatenaX.NetworkServices.Service.Service.csproj
> +      <ProjectReference Include="..\..\framework\CatenaX.NetworkServices.Framework.Web\CatenaX.NetworkServices.Framework.Web.csproj" />
please remove the redundant dependencies that FrameWork.Web implicitly depends on.

2022-09-05 21:58 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                        : a.OfferDescriptions.SingleOrDefault(d => d.LanguageShortName == languageShortName)!.DescriptionShort
fixed

2022-09-05 21:58 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/LanguageRepository.cs
> +            .Where(x => languageCodes.Any(y => y == x.ShortName))
fixed

2022-09-05 21:58 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    : a.OfferDescriptions.SingleOrDefault(d => d.LanguageShortName == languageShortName)!.DescriptionLong
fixed

2022-09-06 08:01 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220905140741_CPLP-1212-ChangeAppToOffer.cs
> +            migrationBuilder.CreateTable(
removed

2022-09-06 08:01 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/AuditEntities/AuditOfferSubscription.cs
> -public class AuditCompanyAssignedApp : CompanyAssignedApp, IAuditEntity
i removed the usings of the Audit entity, but didn't delete it, so we don't forget we need to implement the auditing for it

2022-09-06 08:01 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/OfferSubscription.cs
> +    public Guid? AppSubscriptionDetailId { get; set; }
done

2022-09-06 08:01 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/OfferDetailImage.cs
> +    public OfferDetailImage(Guid offerId, string imageUrl)
done

2022-09-06 08:01 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
> +    public virtual DbSet<AppAssignedDocument> AppAssignedDocuments { get; set; } = default!;
renamed

2022-09-06 08:01 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/OfferRepository.cs
>      public Task<bool> CheckAppExistsById(Guid appId) =>
valid point. added the separate method for service

2022-09-06 08:01 UTC, Phil91 commented on src/services/CatenaX.NetworkServices.Service.Service/BusinessLogic/IServiceBusinessLogic.cs
> +    Task AddServiceSubscription(Guid serviceId, string iamUserId);
good idea - added

2022-09-06 08:01 UTC, Phil91 commented on src/services/CatenaX.NetworkServices.Service.Service/CatenaX.NetworkServices.Service.Service.csproj
> +      <ProjectReference Include="..\..\framework\CatenaX.NetworkServices.Framework.Web\CatenaX.NetworkServices.Framework.Web.csproj" />
i've cleaned up the dependencies

2022-09-06 15:47 UTC, ntruchsess requested changes

2022-09-06 15:47 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Service.Service/Controllers/ServiceController.cs
> +        return CreatedAtRoute(nameof(GetSubscriptionDetail), new { notificationId = serviceSubscriptionId }, serviceSubscriptionId);
fixed

2022-09-06 15:47 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Service.Service/Controllers/ServiceController.cs
> +    public Task<Guid> CreateServiceOffering([FromBody] ServiceOfferingData data) =>
fixed

2022-09-06 15:51 UTC, ntruchsess approved these changes

2022-09-06 15:59 UTC, ntruchsess requested changes
need to rereview as DBAccess-tests do fail now

2022-09-06 17:00 UTC, ntruchsess commented
ok - I'm done so far, but in the devenv-PR https://github.com/tractusx-team-portal-onboarding/devenv/pull/114 we have 'id uuid DEFAULT gen_random_uuid() NOT NULL,' in table 'offer_subscriptions'. This auto-creation of id is not configured in other regular entities and I cannot find why it is the case here.
As one can see in the Migration Designer-files all regular entities have ValueGeneratedOnAdd() set, but in the database-export this apparently did not create the default value creation as it does in offer_subscriptions. Any idea why this is the case?

2022-09-07 08:41 UTC, Phil91 commented
> ok - I'm done so far, but in the devenv-PR [tractusx-team-portal-onboarding/devenv#114](https://github.com/tractusx-team-portal-onboarding/devenv/pull/114) we have 'id uuid DEFAULT gen_random_uuid() NOT NULL,' in table 'offer_subscriptions'. This auto-creation of id is not configured in other regular entities and I cannot find why it is the case here. As one can see in the Migration Designer-files all regular entities have ValueGeneratedOnAdd() set, but in the database-export this apparently did not create the default value creation as it does in offer_subscriptions. Any idea why this is the case?

As we found out, came with an previous migration. It's removed now.

2022-09-07 10:22 UTC, ntruchsess approved these changes

2022-09-07 10:23 UTC, merged