CPLP-1406 ServiceAgreement Consent
catenax-ng/product-portal-backend pull request #196
Opened 2022-09-05 06:59 UTC by Phil91

2022-09-07 14:06 UTC, ntruchsess requested changes

2022-09-07 14:40 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
> +
done

2022-09-07 14:40 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/CatenaX.NetworkServices.PortalBackend.Migrations.csproj
> +    <Compile Remove="Migrations\20220901070722_CPLP-1212-CombineServiceAndApps.cs" />
removed

2022-09-07 14:40 UTC, Phil91 commented on src/services/CatenaX.NetworkServices.Service.Service/BusinessLogic/ServiceBusinessLogic.cs
> +        var result = await _portalRepositories.GetInstance<IOfferSubscriptionsRepository>().GetCompanyIdWithAssignedAppForCompanyUserAsync(serviceId, iamUserId).ConfigureAwait(false);
done. very good idea.

2022-09-07 14:40 UTC, Phil91 commented on src/services/CatenaX.NetworkServices.Service.Service/BusinessLogic/ServiceBusinessLogic.cs
> +        if (companyAssignedApp is null)
renamed.

2022-09-07 14:40 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AgreementRepository.cs
> +    public IAsyncEnumerable<AgreementData> GetAgreementDataWithAppIdSet(string iamUserId) =>
done. renamed the method as well

2022-09-07 14:40 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AgreementRepository.cs
> +                    (app.Offer!.OfferSubscriptions.Any(caa => caa.Company!.CompanyUsers.Any(cu => cu.IamUser!.UserEntityId == iamUserId)) ||
renamed

2022-09-08 16:52 UTC, ntruchsess requested changes

2022-09-08 16:52 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
> +    public IAsyncEnumerable<ServiceAgreementData> GetAgreementsUntrackedAsync() =>
From my understanding that query will now (as we use Agreements for Offers) produce undesired results as it is intended to return Agreements being related to CompanyRoles only.
(The returntype being now Names ServiceAgreementData is also misleading here)

2022-09-08 16:52 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/Model/CompanyRoleAgreementData.cs
> +        [property: JsonPropertyName("agreements")] IEnumerable<ServiceAgreementData> agreementData);
same here - misleading naming of ServiceAgreementData being used in other context than services

2022-09-08 16:52 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +    private async Task CheckLanguageCodesExist(ICollection<string> languageCodes)
please pass as IEnumerable<string>. 
I do not expect passing as ICollection will make a measurable difference as Any and Except are not an Extension-methods of ICollection but of IEnumerable anyway.

2022-09-08 16:52 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +        if (!await _portalRepositories.GetInstance<IAgreementRepository>()
This check should be executed first as it is cheaper than and not depending on the result of  GetCompanyIdWithAssignedOfferForCompanyUserAsync

2022-09-08 16:52 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +        var (companyId, offerSubscription, _, companyUserId) = result;
as offerSubscription is returned as a tracked object and company-name is not required here it is more efficient to create a new AsNoTracking-Query returning a boolean value indicating the existence of the offersubscrition (and no companyname).

2022-09-08 16:52 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Services.Service/Controllers/ServicesController.cs
> +        await this.WithIamUserId(iamUserId => _serviceBusinessLogic.CreateServiceAgreementConsent(serviceId, serviceAgreementConsentData, iamUserId).ConfigureAwait(false));
is there any endpoint that returns the Consent-data by id? If so return a 'CreatedAt' response

2022-09-09 08:03 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
> +    public IAsyncEnumerable<ServiceAgreementData> GetAgreementsUntrackedAsync() =>
change it back to AgreementData again :)

2022-09-09 14:42 UTC, ntruchsess requested changes
please be aware that a new migration has been created and applied in PR https://github.com/catenax-ng/product-portal-backend/pull/192. Please pull main and recreate yours.

2022-09-09 16:14 UTC, ntruchsess requested changes

2022-09-09 16:14 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +    public async Task<Guid> CreateServiceAgreementConsentAsync(Guid serviceId,
We will need the very same logic for any other type of offer. It therefore would make sense to put such code into a reusable library-module.
(From my point of view it would make sense to group all that is related to offers under 'marketplace'. There could be a module 'CatenaX.NetworkServices.Offers.Library' and the existing Module CatenaX.NetworkServices.Services.Service would also fit in here.

2022-09-09 16:15 UTC, ntruchsess requested changes

2022-09-09 16:15 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220906145503_CPLP-1406-AddAgreementAssignedApps.cs
> +    public partial class CPLP1406AddAgreementAssignedApps : Migration
please be aware that a new migration has been created and applied in PR https://github.com/catenax-ng/product-portal-backend/pull/192. Please pull main and recreate yours.

2022-09-11 17:41 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
> +    public IAsyncEnumerable<ServiceAgreementData> GetAgreementsUntrackedAsync() =>
moved it to agreementRepository

2022-09-11 17:42 UTC, Phil91 commented on src/services/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +    public async Task<Guid> CreateServiceAgreementConsentAsync(Guid serviceId,
that's a good idea. created the new module

2022-09-11 17:42 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220906145503_CPLP-1406-AddAgreementAssignedApps.cs
> +    public partial class CPLP1406AddAgreementAssignedApps : Migration
done

2022-09-12 08:04 UTC, ntruchsess commented
To resolve conflicts I did pull main - please pull before proceeding

2022-09-12 08:37 UTC, Phil91 commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=catenax-ng_product-portal-backend&pullRequest=196)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-backend&pullRequest=196&resolved=false&types=CODE_SMELL)
> 
> [![74.9%](https://camo.githubusercontent.com/86b73734925524d51d47145ab1a1d3d06233748f7a9b0f77993d531ce5110d8e/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f36302d313670782e706e67)](https://sonarcloud.io/component_measures?id=catenax-ng_product-portal-backend&pullRequest=196&metric=new_coverage&view=list) [74.9% Coverage](https://sonarcloud.io/component_measures?id=catenax-ng_product-portal-backend&pullRequest=196&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=catenax-ng_product-portal-backend&pullRequest=196&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=catenax-ng_product-portal-backend&pullRequest=196&metric=new_duplicated_lines_density&view=list)

not sure why it says 74.9% pretty sure it's above 80. should be something around 90 after my latest changes. sonar somehow didn't recognized it

2022-09-12 15:09 UTC, ntruchsess requested changes

2022-09-12 15:09 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConsentRepository.cs
> +    public void AttachToDatabase(IEnumerable<Consent> consents) =>
What is the benefit wrapping that call? I'd understand if the input-parameter were be an IEnumerable of primary key and the return-value then would be IEnumerable<Consent>. That way the business-code would not directly create the entities by using 'new'

2022-09-13 06:38 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +        ServiceAgreementConsentData serviceAgreementConsentData, string iamUserId) =>
done

2022-09-13 06:38 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AgreementRepository.cs
> +        _context.Agreements
done

2022-09-13 06:38 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConsentRepository.cs
> +    public void AttachToDatabase(IEnumerable<Consent> consents) =>
I removed it. We didn't needed it. But did a unit test before to check whether it's possible to use attach like that. interesting thing is, it does.

2022-09-13 12:52 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IAgreementRepository.cs
> +    Task<bool> CheckAgreementExistsAsync(Guid agreementId);
done

2022-09-13 12:53 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.Offers.Library/Service/OfferService.cs
> +                .CheckAgreementExistsAsync(agreementId).ConfigureAwait(false))
done

2022-09-15 19:35 UTC, ntruchsess approved these changes

2022-09-15 19:54 UTC, ntruchsess commented
From my point of view ready to merge. Please double check my changes in respect to AgreementAssignedOffers.

2022-09-16 06:53 UTC, merged