CPLP-1378 updated more document type
catenax-ng/product-portal-backend pull request #206
Opened 2022-09-12 08:21 UTC by qxz2mqe

Additional changes of 12th September--support more document type for id 5,6,7
https://jira.catena-x.net/browse/CPLP-1378

2022-09-12 11:21 UTC, Phil91 requested changes
Since there are changes to the documentTypeId a new migration needs to be added

2022-09-12 11:21 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Enums/DocumentTypeId.cs
> +
Remove empty line

2022-09-12 11:21 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +    //[RequestFormLimits(ValueLengthLimit = 819200, MultipartBodyLengthLimit = 819200)]
Either remove commented out line or comment in again

2022-09-12 11:21 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            throw new ArgumentException($"documentType must  be either :{string.Join(",", _settings.DocumentTypeIds)}");
one whitespace too much between 'must' and 'be'

2022-09-12 11:21 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        if (!(_settings.DocumentTypeIds.Contains(documentTypeId)))
the bracelets wrapping _settings.DocumentTypeIds.Contains(documentTypeId) can be removed in my opinion

2022-09-12 11:21 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private readonly AppsSettings _settings;
please add a line break after this line

2022-09-12 13:45 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private readonly AppsSettings _settings;
fixed

2022-09-12 13:45 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        if (!(_settings.DocumentTypeIds.Contains(documentTypeId)))
fixed

2022-09-12 13:45 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            throw new ArgumentException($"documentType must  be either :{string.Join(",", _settings.DocumentTypeIds)}");
fixed

2022-09-12 13:46 UTC, qxz2mqe commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppReleaseProcessController.cs
> +    //[RequestFormLimits(ValueLengthLimit = 819200, MultipartBodyLengthLimit = 819200)]
fixed

2022-09-12 13:48 UTC, qxz2mqe commented
Since there are changes to the documentTypeId a new migration needs to be added
As discussed with Julia today  this task assigned  to philip

2022-09-14 07:30 UTC, ntruchsess approved these changes

2022-09-14 07:31 UTC, Phil91 approved these changes

2022-09-14 07:31 UTC, merged