CPLP-1413 add subscription details to service details
catenax-ng/product-portal-backend pull request #209
Opened 2022-09-12 14:36 UTC by Phil91

2022-09-12 14:48 UTC, ntruchsess requested changes

2022-09-12 14:48 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                app.Name?? Constants.ErrorString,
Why has this been revertet? Setting the ErrorString in the businesslogic is more effizient than doing this on the database-server.

2022-09-13 05:47 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                app.Name?? Constants.ErrorString,
talked to julia about that, we now return null if the values are empty or not yet set in the database

2022-09-13 10:48 UTC, ntruchsess requested changes

2022-09-13 10:48 UTC, ntruchsess commented on src/services/CatenaX.NetworkServices.Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +    public async Task<ServiceDetailData> GetServiceDetailsAsync(Guid serviceId, string lang, string iamUserId)
the Unit-test in ServiceBusinessLogicTest.cs needs to be adjusted accordingly (line 315 ```var result = await sut.GetServiceDetailsAsync(_existingServiceId, "en");```, the call is missing the additional parameter

2022-09-13 10:59 UTC, ntruchsess approved these changes

2022-09-13 10:59 UTC, merged