CPLP-1439 relocate Keycloak.Net to CatenaX src and upgrade to net6.0
catenax-ng/product-portal-backend pull request #212
Opened 2022-09-13 13:00 UTC by ntruchsess

implements https://jira.catena-x.net/browse/CPLP-1439
- Keycloak.net relocated to new module CatenaX.NetworkServices.Keycloak.Library
- dotnet6.0
- flurl upgrades to most recent 3.2.4

2022-09-13 14:55 UTC, ntruchsess commented
as preexisting project Keycloak.Net was not nullable-enabled compilation of the now nullable-enabled relocated module CatenaX.NetworkServices.Keycloak.Library results in numerous warnings for non-nullable reference-types being assigned nullable values.
Those warnings are due to most Keycloak configuration parameters being passed via the api actually being nullable, but not being declared as such. As not all those values are optional a fix requires an analysis of every single occurrence and cannot be done blindly. Therefore the warnings shall be fixed whenever a piece of code is being implemented that is affected by a particular warning.

2022-09-19 09:03 UTC, Phil91 requested changes

2022-09-19 12:51 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
>          [Obsolete]
I've no idea whether this is still used by the Frontend - we need to clarify with @jjeroch

2022-09-19 14:23 UTC, Phil91 approved these changes

2022-09-19 15:18 UTC, evegufy approved these changes

2022-09-19 15:31 UTC, merged