feature/cplp 830 put app detail
catenax-ng/product-portal-backend pull request #213
Opened 2022-09-14 05:16 UTC by qxz2mqe

Fix Provided for Error Reported by Julia. RemoveRange Function has some issue. It throw the exception as below. Instead of RemoveRange calling  Remove method which work
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll: 'The entity type 'SelectEnumerableIterator<ValueTuple<string, string, string>, OfferDescription>' was not found. Ensure that the entity type has been added to the model.'

2022-09-14 06:18 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.Apps.Service/Controllers/AppReleaseProcessController.cs
> +    /// Update created apps in the marketplace for given appId for same company as user
Change to "Add app details to a newly created owned app under the app release/publishing process."

2022-09-14 13:58 UTC, ntruchsess commented
I checked the sources of Select and RemoveRange ( https://source.dot.net/#System.Linq/System/Linq/Select.cs + https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/DbContext.cs ). RemoveRange is overloaded and it seems the compiler binds to RemoveRange(params: object[]) instead of RemoveRange(IEnumerable<object>). From my understanding there is nothing wrong in our code, Microsoft should have defined it using generigs as RemoveRange<EntityType>(IEnumerable<EntityType>) to resolve the ambiguity.

2022-09-14 14:03 UTC, ntruchsess requested changes
I checked the sources of Select and RemoveRange ( https://source.dot.net/#System.Linq/System/Linq/Select.cs + https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/DbContext.cs ). RemoveRange is overloaded and it seems the compiler binds to RemoveRange(params: object[]) instead of RemoveRange(IEnumerable<object>). From my understanding there is nothing wrong in our code, Microsoft should have defined it using generigs as RemoveRange<EntityType>(IEnumerable<EntityType>) to resolve the ambiguity.

Nevertheless - I'd rather see the foreach-loop within our own (wrapper-) implementation of PortalRepositories.RemoveRange than doing it explicitly in the businesslogic. 

It's also possible that we can force the choice of the correct method by narrowing TEntity to anything derived from class to indicate it's not 'object'.

like:
```
public void RemoveRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class
        => _dbContext.RemoveRange(entities);
```
(I did add 'where TEntity : class' here). Can you please try wether this fixes the issue? (I checked all compiles fine, but I don't have a testing-scenario ready).

2022-09-15 04:14 UTC, qxz2mqe commented
public void RemoveRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class
        => _dbContext.RemoveRange(entities);

This one has worked. I have committed the changes

2022-09-15 13:33 UTC, ntruchsess approved these changes

2022-09-15 13:39 UTC, merged