Feature/cplp 1235 add single user ownidp
catenax-ng/product-portal-backend pull request #219
Opened 2022-09-19 02:23 UTC by ntruchsess

2022-09-20 19:12 UTC, Phil91 requested changes

2022-09-21 09:31 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +    [Obsolete]
I don't know whether this is still being called by the frontend, we need to ask @jjeroch of create a bug-ticket for that. Here it is out of scope.

2022-09-21 09:39 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +    public async Task<CreatedAtRouteResult> CreateOwnIdpOwnCompanyUser([FromBody] UserCreationInfoIdp userToCreate, [FromRoute] Guid identityProviderId)
done

2022-09-21 09:47 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/CatenaX.NetworkServices.Provisioning.Library.csproj
> +</Project>
done

2022-09-21 09:47 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/CatenaX.NetworkServices.PortalBackend.DBAccess.csproj
> +</Project>
done

2022-09-21 09:49 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Service/UserProvisioningService.cs
> +                await AssignRolesToNewUser(userRolesRepository, user.Roles, companyUser.Id, centralUserId, clientId, userRoleIds);
done

2022-09-21 09:50 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Service/UserProvisioningService.cs
> +    private async Task ValidateDuplicateUsers(IUserRepository userRepository, string alias, UserCreationInfoIdp user, Guid companyId)
done

2022-09-21 09:52 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +    public async Task<CompanyUserDetails> GetOwnCompanyUserDetails(Guid companyUserId, string adminUserId)
done

2022-09-21 09:52 UTC, ntruchsess commented on src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Service/UserProvisioningService.cs
> +    private async Task AssignRolesToNewUser(IUserRolesRepository userRolesRepository, IEnumerable<string> roles, Guid companyUserId, string centralUserId, string clientId, IDictionary<string,Guid> us
done

2022-09-21 09:54 UTC, ntruchsess commented on src/framework/CatenaX.NetworkServices.Framework.IO/CatenaX.NetworkServices.Framework.IO.csproj
> +</Project>
done

2022-09-21 10:04 UTC, Phil91 approved these changes

2022-09-21 10:26 UTC, merged