CPLP-1480 service provider
catenax-ng/product-portal-backend pull request #233
Opened 2022-09-22 12:51 UTC by Phil91

2022-09-28 13:41 UTC, ntruchsess requested changes

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +            c.ProviderCompany != null && c.ProviderCompany.ServiceProviderCompanyDetail != null ?
As this is for the query-builder those null checks are redundant. c.ProviderCompany!.ServiceProviderCompanyDetail!.AutoSetupUrl (using the !-operator) will do. The generated sql cannot run into a nullreferenceexception it just returns null in case the sql join on the database doesn't match anything.

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +            .Select(x => new OfferThirdPartyAutoSetupData(new CustomerData(x.Company!.Name, x.Company!.Address!.CountryAlpha2Code, x.Company.CompanyUsers.Single(cu => cu.IamUser!.UserEntityId == iamU
please apply appropriate formating, inline creation of objects passed as parameters all in a single line is hardly readable. (Doing it within a single statement is fine, but please add linebreaks with propper indenting so it becomes more clear which values belongs to which created object)

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +    public Task<OfferProviderDetailsData?> GetOfferProviderDetailsAsync(Guid appId) =>
add the OfferTypeId as additional parameter and include into the where-condition to ensure the endpoint will not be able to process offerTypes that the endpoint is not intended to be used for.

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +            modelBuilder.Entity("CatenaX.NetworkServices.PortalBackend.PortalEntities.Entities.ServiceProviderCompanyDetail", b =>
please recreate the (not yet merged) migration as the entities namespace has changed.

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/OfferAutoSetupData.cs
> +public record OfferThirdPartyAutoSetupData(
please rename file to OfferThirdPartyAutoSetupData.cs

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/OfferAutoSetupData.cs
> +public record CustomerData(
please choose a more specific name as it's likely to clash with other future models (e.g. OfferThirdPartyAutoSetupCustomerData)

2022-09-28 13:41 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +    public virtual DbSet<ServiceProviderCompanyDetail> ServiceProviderCompanyDetails { get; set; } = default!;
please make sure the declaration of DBSets is ordered alphabetically (makes it easier to see what is already included)

2022-09-29 09:25 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
> -        var (companyId, creatorId) = await userRepository.GetOwnCompanAndCompanyUseryId(iamUserId).ConfigureAwait(false);
done

2022-09-29 10:24 UTC, ntruchsess requested changes

2022-09-29 10:24 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +            .GetServiceProviderCompanyDetailAsync(serviceProviderDetailDataId, iamUserId)
the Query should return a ValueTuple of ServiceProviderDetailData and bool IsUsersCompany, then the endpoint can differentiate and throw NotFoundException or ForbiddenException denpending on the result.

2022-09-29 10:24 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
> +        if (!await _portalRepositories.GetInstance<ICompanyRepository>().CheckCompanyIsServiceProviderAndExistsForIamUser(companyId, iamUserId, CompanyRoleId.SERVICE_PROVIDER).ConfigureAwait(false))
companyId should not be an input-parameter but returned by the query. (Query would return ValueTuple of companyId and bool HasCompanyRole), ForbiddenException shall be thrown in case the users company does not have the required company-role

2022-09-29 14:59 UTC, ntruchsess approved these changes

2022-09-29 15:19 UTC, ntruchsess commented
corresponding PR for devenv (recreated with latest migration):
https://github.com/tractusx-team-portal-onboarding/devenv/pull/137

2022-09-29 15:38 UTC, merged