CPLP-1417 add endpoint to update the user roles
catenax-ng/product-portal-backend pull request #236
Opened 2022-09-26 14:25 UTC by Phil91

2022-10-07 11:53 UTC, ntruchsess requested changes

2022-10-07 11:53 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var rolesToAdd = await userRoleRepository.GetRolesToAdd(iamClientId, userRoleInfo.CompanyUserId, roles).ToListAsync().ConfigureAwait(false);
actually determining the roleIds by referring to the iamClientId (while already knowning appId) is inefficient as the UserRoles are not linked to the iamClient but the offer

2022-10-07 11:53 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var rolesToDelete = await userRoleRepository.GetAssignedRolesForDeletion(userRoleInfo.CompanyUserId, roles).ToListAsync().ConfigureAwait(false);
without passing the appId as parameter to the query it cannot determine the unassigned roles unambigiously.

2022-10-07 11:53 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +                !userRole.CompanyUsers.SingleOrDefault(x => x.Id == companyUserId)!.CompanyUserAssignedRoles.Any(x => userRoles.Contains(x.UserRole!.UserRoleText)))
without a reference to an offer/app the role-names are ambigious and so will be the result of the 'Any'
I suggest to change that query to:
```
    public IAsyncEnumerable<UserRoleWithId> GetRolesToAdd(Guid appId, Guid companyUserId, IEnumerable<string> userRoles) =>
        _dbContext.UserRoles
            .AsNoTracking()
            .Where(userRole =>
                userRole.OfferId == appId &&
                userRoles.Contains(userRole.UserRoleText) &&
                !userRole.CompanyUsers.SingleOrDefault(x => x.Id == companyUserId)!.CompanyUserAssignedRoles.Any(x => x.UserRoleId == userRole.Id))
            .Select(userRole => new UserRoleWithId(
                userRole.UserRoleText,
                userRole.Id
            ))
            .ToAsyncEnumerable();
```

2022-10-07 11:53 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +                    x.CompanyUserId,
what to we need to return the companyUserId here? It's already known as it's an input-parameter to the query

2022-10-07 11:53 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
please add the mandatory license-header

2022-10-07 11:53 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +        _dbContext.CompanyUserAssignedRoles
without a reference to an offer/app the role-names are ambigious and so will be the result

2022-10-07 11:53 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005135736_CPLP-1417-RemoveCompanyAssignedUserRoleId.Designer.cs
> +﻿// <auto-generated />
please add the mandatory license-header

2022-10-07 11:53 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005135736_CPLP-1417-RemoveCompanyAssignedUserRoleId.cs
> +﻿using System;
please add the mandatory license-header

2022-10-07 12:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005135736_CPLP-1417-RemoveCompanyAssignedUserRoleId.cs
> +﻿using System;
done

2022-10-07 12:43 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +    public async IAsyncEnumerable<string> CreateOwnCompanyUsersAsync(IEnumerable<UserCreationInfo> userList, string createdByName)
changed

2022-10-07 12:43 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var rolesToAdd = await userRoleRepository.GetRolesToAdd(iamClientId, userRoleInfo.CompanyUserId, roles).ToListAsync().ConfigureAwait(false);
valid point, added the offerId

2022-10-07 12:43 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var rolesToDelete = await userRoleRepository.GetAssignedRolesForDeletion(userRoleInfo.CompanyUserId, roles).ToListAsync().ConfigureAwait(false);
added

2022-10-07 12:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +        _dbContext.CompanyUserAssignedRoles
added

2022-10-07 12:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +            .Where(x => x.CompanyUserId == companyUserId && userRoles.All(ur => ur != x.UserRole!.UserRoleText))
added the offerId check

2022-10-07 12:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +                    x.CompanyUserId,
true. changed to userRoleWithId

2022-10-07 12:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +                !userRole.CompanyUsers.SingleOrDefault(x => x.Id == companyUserId)!.CompanyUserAssignedRoles.Any(x => userRoles.Contains(x.UserRole!.UserRoleText)))
changed

2022-10-07 12:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
done

2022-10-07 12:45 UTC, Phil91 commented on src/administration/Administration.Service/Administration.Service.csproj
> +    <ProjectReference Include="..\..\framework\Framework.Async\Framework.Async.csproj" />
reverted the changes

2022-10-07 12:45 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    { "nameCreatedBy", createdByName },
there was an existing query. changed it.

2022-10-11 16:30 UTC, ntruchsess requested changes

2022-10-11 16:30 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005135736_CPLP-1417-RemoveCompanyAssignedUserRoleId.cs
> +﻿/********************************************************************************
There is a conflicting migration in main - please merge main and recreate

2022-10-12 06:49 UTC, Phil91 reviewed
devenv is up to date as well

2022-10-12 06:49 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005135736_CPLP-1417-RemoveCompanyAssignedUserRoleId.cs
> +﻿/********************************************************************************
recreated.

2022-10-12 06:49 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +                !userRole.CompanyUsers.SingleOrDefault(x => x.Id == companyUserId)!.CompanyUserAssignedRoles.Any(x => userRoles.Contains(x.UserRole!.UserRoleText)))
changed it and verified it. works with
`!userrole.CompanyUsers.Any(user => user.Id == companyUserId)`

2022-10-12 07:37 UTC, ntruchsess requested changes

2022-10-12 07:37 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
>          var companyUser = await _portalRepositories.GetInstance<IUserRepository>()
as 'companyUser' is not a CompanyUser-entity to avoid any ambiguity I suggest renaming to something like 'companyUserIamData'

2022-10-12 07:37 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +            .Where(role => role.OfferId == offerId && userRoles.Contains(role.UserRoleText) && role.CompanyUsers.Any(user => user.Id == companyUserId))
please apply same formating as used below for GetRolesToAdd :-)

2022-10-12 07:55 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/UserController.cs
> +    //[Authorize(Roles = "modify_user_account")]
damn -.- readded

2022-10-12 07:55 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            userRoleRepository.CreateCompanyUserAssignedRole(userRoleInfo.CompanyUserId, roleWithId.CompanyUserRoleId);
changed for both

2022-10-12 07:55 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
>          var companyUser = await _portalRepositories.GetInstance<IUserRepository>()
renamed

2022-10-12 07:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +            .Where(role => role.OfferId == offerId && userRoles.Contains(role.UserRoleText) && role.CompanyUsers.Any(user => user.Id == companyUserId))
done

2022-10-13 07:50 UTC, ntruchsess requested changes

2022-10-13 07:50 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        await _provisioningManager.AssignClientRolesToCentralUserAsync(companyUser.TargetIamUserId!, clientRoleNames)
This method behaves differently to other provisioningmanager-methods as it won't throw in case the role assignment did run into errors. That was implemented on explicit request from @jjeroch . The method returns a dictionary of all roles that were actually assigned. Please make sure that database-entries are created for those role only that were actually assigned in keycloak.
(This affects only the role-assignment - the deletion will throw in case anything goes wrong)

2022-10-13 07:53 UTC, ntruchsess approved these changes

2022-10-13 07:53 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +    private async Task AddRoles(Guid companyUserId, string iamClientId, List<UserRoleWithId> rolesToAdd, CompanyIamUser companyUser, IUserRolesRepository userRoleRepository)
as 'companyUser' is not a CompanyUser-entity to avoid any ambiguity I suggest renaming the parameter to something like 'companyUserIamData'
(affects both AddRoles and DeleteRoles)

2022-10-14 06:30 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        await _provisioningManager.AssignClientRolesToCentralUserAsync(companyUser.TargetIamUserId!, clientRoleNames)
we now return the not assigned roles

2022-10-14 06:30 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +    private async Task AddRoles(Guid companyUserId, string iamClientId, List<UserRoleWithId> rolesToAdd, CompanyIamUser companyUser, IUserRolesRepository userRoleRepository)
changed.

2022-10-18 12:14 UTC, ntruchsess requested changes

2022-10-18 12:14 UTC, ntruchsess commented on src/administration/Administration.Service/Controllers/UserController.cs
> +        await this.WithIamUserId(adminUserId => _logic.ModifyUserRoleAsync(appId, userRoleInfo, adminUserId)).ConfigureAwait(false);
async, await and ConfigureAwait are redundant here. They were only needed if converting the result into anything else (like OKResult, but this will be done by the controller implicitly)

2022-10-18 14:51 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        if (companyUserIamData == null || string.IsNullOrWhiteSpace(companyUserIamData.IdpName))
removed since it wasn't used.

2022-10-18 14:51 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            .GetAppAssignedClientIdUntrackedAsync(appId, companyUserIamData.CompanyId)
refactored. actually a pretty good idea.

2022-10-18 14:52 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var notExistingRoles = distinctRoles.Where(r => !roles.Select(ur => ur.CompanyUserRoleText).Contains(r));
changed

2022-10-18 14:52 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var rolesToAdd = distinctRoles.Except(roles.Where(x => x.IsAssignedToUser).Select(x => x.CompanyUserRoleText));
changed

2022-10-18 14:52 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        var rolesToDelete = roles.Where(x => x.IsAssignedToUser).Select(x => x.CompanyUserRoleText).Except(distinctRoles);
changed

2022-10-18 14:52 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        foreach (var roleWithId in rolesToAdd.Where(x => assignedRoles[iamClientId].Contains(x.CompanyUserRoleText)))
good idea - changed

2022-10-18 14:52 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/UserController.cs
> +        await this.WithIamUserId(adminUserId => _logic.ModifyUserRoleAsync(appId, userRoleInfo, adminUserId)).ConfigureAwait(false);
absolutly

2022-10-18 20:23 UTC, ntruchsess approved these changes

2022-10-18 20:25 UTC, ntruchsess approved these changes
corresponding (rebuild) PR on devenv: https://github.com/tractusx-team-portal-onboarding/devenv/pull/159

2022-10-19 07:35 UTC, ntruchsess approved these changes

2022-10-19 07:36 UTC, merged