CPLP-1473 edc discovery service
catenax-ng/product-portal-backend pull request #243
Opened 2022-09-28 12:04 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1473

2022-09-28 14:29 UTC, ntruchsess requested changes

2022-09-28 14:29 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +            .Where(connector => connector.Provider!.Id == connector.ProviderId && bpns.Contains(connector.Provider!.BusinessPartnerNumber))
what shall this condition be good for: 'connector.Provider.Id == connector.ProviderId'
this will be always true as this is how the navigational property is defined.

2022-09-28 14:29 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +            .GroupBy(connector => connector.Provider!.BusinessPartnerNumber)
while it compiles fine 'GroupBy' can be used in ef-queries for aggregates only. (That is because the database does not allow to select columns that are not also included in the group by clause):
see https://www.postgresql.org/docs/14/queries-table-expressions.html#QUERIES-GROUP
Please apply the GroupBy on the query result (in the businesslogic).

2022-09-28 14:46 UTC, ntruchsess commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [HttpGet]
FETCH or GET-requests cannot have a body

2022-09-29 09:58 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +            .GroupBy(connector => connector.Provider!.BusinessPartnerNumber)
Fixed . I removed GroupBy from Query and applying it in Business Logic

2022-09-29 09:59 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +            .Where(connector => connector.Provider!.Id == connector.ProviderId && bpns.Contains(connector.Provider!.BusinessPartnerNumber))
Removed

2022-09-30 12:10 UTC, ntruchsess approved these changes

2022-09-30 12:10 UTC, merged