CPLP-1481 managed connectors
catenax-ng/product-portal-backend pull request #244
Opened 2022-09-29 14:50 UTC by Phil91

This PR is base on #232, in this PR [CPLP-1481](https://jira.catena-x.net/browse/CPLP-1481) is resolved.

2022-10-11 18:08 UTC, ntruchsess requested changes

2022-10-11 18:08 UTC, ntruchsess commented on tests/administration/CatenaX.NetworkServices.Administration.Service.Tests/Controllers/ConnectorsControllerTest.cs
> +/********************************************************************************
That seems to be a leftover from the old namespace 'CatenyX.NetworkServices.Administration.Service.Tests' that was not migrated appropriately. Please compare to the existing ConnectorsControllerTest.cs in Administration.Service.Tests, transfer any outstanding changes and then delete.

2022-10-11 18:08 UTC, ntruchsess commented on tests/registration/Registration.Service.Tests/Registration.Service.Tests.csproj
> +    <PackageReference Include="FluentAssertions" Version="6.6.0" />
Be aware in PR https://github.com/catenax-ng/product-portal-backend/pull/249 I've added FluentAssertions Version 6.7.0 to Tests.Shared.csproj
As soon both PRs are merged this will not build any longer because of this Version-downgrade conflict.

2022-10-12 10:19 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [ProducesResponseType(typeof(CreatedAtRouteResult), StatusCodes.Status201Created)]
changed

2022-10-12 10:19 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [ProducesResponseType(typeof(CreatedAtRouteResult), StatusCodes.Status201Created)]
done

2022-10-12 10:19 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
> +    Task<Guid> GetTechnicalUserCompany(string iamUserId);
done

2022-10-12 10:19 UTC, Phil91 commented on tests/administration/CatenaX.NetworkServices.Administration.Service.Tests/Controllers/ConnectorsControllerTest.cs
> +/********************************************************************************
changed

2022-10-12 10:19 UTC, Phil91 commented on tests/registration/Registration.Service.Tests/Registration.Service.Tests.csproj
> +    <PackageReference Include="FluentAssertions" Version="6.6.0" />
updated

2022-10-12 10:20 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +using Org.CatenaX.Ng.Portal.Backend.PortalBackend.PortalEntities.Enums;
done

2022-10-12 10:20 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        var issuerBpn = await _portalRepositories.GetInstance<ICompanyRepository>().GetBpnForCompanyNameAsync(_settings.SdFactoryIssuerCompany).ConfigureAwait(false);
no there wasn't. I changed it to the BPN itself and moved it to the sdFactory Settings.

2022-10-12 10:21 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsSdFactoryService.cs
>          var response = await httpClient.PostAsJsonAsync(_settings.SdFactoryUrl, requestModel).ConfigureAwait(false);
added. Very good point, didn't thought about that.

2022-10-12 10:21 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsSdFactoryService.cs
> +        await using var stream = await response.Content.ReadAsStreamAsync();
done

2022-10-12 10:21 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsSdFactoryService.cs
> +        await stream.CopyToAsync(ms);
done

2022-10-12 10:26 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20220929071516_CPLP-1408-ServiceProviderCompanyDetail.cs
> +}
done

2022-10-12 10:26 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20220929071516_CPLP-1408-ServiceProviderCompanyDetail.Designer.cs
> +}
done

2022-10-12 10:28 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005130217_CPLP-1422-AddDocumentToConnector.Designer.cs
> +﻿/********************************************************************************
recreated

2022-10-12 10:28 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221005130217_CPLP-1422-AddDocumentToConnector.cs
> +﻿/********************************************************************************
recreated

2022-10-12 10:28 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> -using System;
recreated

2022-10-12 10:30 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var doc = _portalRepositories.GetInstance<IDocumentRepository>().CreateDocument(documentName, documentContent, hash,
done.

2022-10-12 14:15 UTC, ntruchsess requested changes

2022-10-12 14:15 UTC, ntruchsess commented on tests/administration/CatenaX.NetworkServices.Administration.Service.Tests/Controllers/ConnectorsControllerTest.cs
> +/********************************************************************************
cannot see that change - did you commit and push?

2022-10-12 14:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20220929071516_CPLP-1408-ServiceProviderCompanyDetail.Designer.cs
> +}
could not see this change. To revert back to main version do:
```git checkout main portalbackend/PortalBackend.Migrations/Migrations/20220929071516_CPLP-1408-ServiceProviderCompanyDetail.Designer.cs```
(I've already done so...)

2022-10-12 14:34 UTC, Phil91 commented on tests/administration/CatenaX.NetworkServices.Administration.Service.Tests/Controllers/ConnectorsControllerTest.cs
> +/********************************************************************************
didn't saw the file in the filesystem. it's removed now. renamed the existing one to ...Tests.cs as well

2022-10-12 14:59 UTC, ntruchsess approved these changes

2022-10-13 07:36 UTC, merged