feature/cplp 1598 refactor approle
catenax-ng/product-portal-backend pull request #247
Opened 2022-10-04 12:47 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1598

2022-10-04 21:45 UTC, Phil91 requested changes
Please write some UnitTests for the changed code.

2022-10-04 21:45 UTC, Phil91 commented on src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
> +    [ProducesResponseType(typeof(IEnumerable<AppRoleData>), StatusCodes.Status200OK)]
Please add a <response code="200" comment for swagger

2022-10-04 21:45 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var roelData = new List<AppRoleData>();
typo. please adjust to roleData

2022-10-05 08:01 UTC, ntruchsess requested changes

2022-10-05 08:01 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        return roelData.AsEnumerable();
List implements IEnumerable, the call to AsEnumerable() is redundant. Please remove

2022-10-06 05:44 UTC, Phil91 requested changes

2022-10-06 05:44 UTC, Phil91 commented on src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
> +    [ProducesResponseType(typeof(IEnumerable<AppRoleData>), StatusCodes.Status201Created)]
If you want a 201 you need to change the implementation to return a `CreatedAtRoute`

2022-10-06 10:00 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        return roelData.AsEnumerable();
done

2022-10-06 10:00 UTC, qxz2mqe commented on src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
> +    [ProducesResponseType(typeof(IEnumerable<AppRoleData>), StatusCodes.Status201Created)]
fixed

2022-10-06 10:00 UTC, qxz2mqe commented
Please write some UnitTests for the changed code--Added

2022-10-11 10:24 UTC, ntruchsess approved these changes

2022-10-11 11:47 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
>              .Select(x=>x.ProviderCompany!.CompanyUsers.First(companyUser => companyUser.IamUser!.UserEntityId == userId).Id)
Would it make sense to move this method into the offer repository as well? than we could get rid of the AppReleaseRepository.

2022-10-11 12:27 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/AppReleaseRepository.cs
>              .Select(x=>x.ProviderCompany!.CompanyUsers.First(companyUser => companyUser.IamUser!.UserEntityId == userId).Id)
done

2022-10-11 12:29 UTC, Phil91 approved these changes

2022-10-11 13:01 UTC, merged