CPLP-1227 bulk-upload own company shared idp users
catenax-ng/product-portal-backend pull request #249
Opened 2022-10-05 15:50 UTC by ntruchsess

2022-10-06 14:19 UTC, Phil91 requested changes
Please provide unit tests, in my opinion espacially the csv parser is perfect to test with specific csv files for each case we could add into the test.

2022-10-06 14:19 UTC, Phil91 commented on src/framework/Framework.IO/CsvParser.cs
> +        Action<string> validateFirstLine,
I'm thinking about the implementation of the first line validation, we could also hand over the HeaderColumns and validate those, than we don't need to execute an action from outside. But I'm not sure about that. The positive effect of passing the action from outside is that we could validate all kind of stuff (even service calls).

2022-10-06 15:46 UTC, ntruchsess commented
I did refactor the existing file-upload that is used in identityprovider user-migration to use the new framework implementation, so no csv-upload with individually implementation of the algorithm remains. Please check.

2022-10-07 07:18 UTC, Phil91 reviewed
changes in identityprovider looks fine, as everything else. we have 6 code smells, we should look into.
About the code duplication, I'm not sure why's that. Can you tell what sonars problem is?

2022-10-07 20:38 UTC, ntruchsess commented
All smells are fixed. To make sonar happy I had to apply small refactoring to the usercreation to reduce the complexity.
I did refactor all usecases that create companyUsers to make use of the UserCreationService-implementation. In addition to that I fixed the open 'TODO' in userdeletion not covering own-ipd or mixed idp scenarios.
Can you please re-check?

2022-10-08 08:44 UTC, ntruchsess commented
regarding the duplication: I don't think sonar has a problem. There is some duplication (the stream implementations) that technically cannot be avoided as one has to implement the whole interface.

2022-10-10 06:41 UTC, Phil91 reviewed
Code changes look fine to me. We should at least add UnitTests for the Upload

2022-10-17 22:37 UTC, ntruchsess commented
@Phil91 guess test-coverage is now sufficient ;-). Can you please do a final re-review?

2022-10-18 10:54 UTC, Phil91 requested changes
Review done. Looks good so far. Tested it - works fine.

Locally one Test is running into an error - TestAsyncCopyToSuccess in AsyncEnumerableStringStreamTest, is it only on my machine or do you get the error as well?

If its on my machine I'm going to approve it

2022-10-18 12:32 UTC, Phil91 approved these changes
Looks really good! 👍

2022-10-18 12:33 UTC, merged