CPLP-1491 user endpoint
catenax-ng/product-portal-backend pull request #252
Opened 2022-10-06 11:58 UTC by Phil91

2022-10-06 16:29 UTC, ntruchsess requested changes

2022-10-06 16:29 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(companyUser => firstName == null || EF.Functions.ILike(companyUser.Firstname!, $"%{firstName.Trim(escapeChar)}%")
as this not real 'escaping' but just trimming the special characters, did you try searching with % or _ within the search string checking whether you get an exact match with names that actually do include % or _ while not matching the % or _ as a wildcard?
see https://www.postgresql.org/docs/current/functions-matching.html how postgres does treat those values.

2022-10-07 05:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(companyUser => firstName == null || EF.Functions.ILike(companyUser.Firstname!, $"%{firstName.Trim(escapeChar)}%")
i just moved the code, i will check it.
but should it really be possible to have company users with an % or _ in the firstname?
at least the % could open the possibility to mess with our database.

2022-10-14 14:48 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(companyUser => firstName == null || EF.Functions.ILike(companyUser.Firstname!, $"%{firstName.Trim(escapeChar)}%")
escaping added

2022-10-19 16:15 UTC, ntruchsess approved these changes
I did fix the operator-precedence issue and removed the characters that (according to https://www.postgresql.org/docs/7.3/functions-matching.html) are not special characters in this context. Please re-check before merging.

2022-10-19 16:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(companyUser => firstName == null || EF.Functions.ILike(companyUser.Firstname!, $"%{regex.Replace(firstName!, @"\")}%")
I did fix this.

2022-10-19 19:01 UTC, merged