CPLP-1625 appdetailstatus refactoring
catenax-ng/product-portal-backend pull request #255
Opened 2022-10-07 05:09 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1625

2022-10-07 07:05 UTC, ntruchsess requested changes

2022-10-07 07:05 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    a.Documents.Select(d => new DocumentTypeData(d.DocumentType!.Id, d.Id, d.DocumentName))),
DocumentTypeId is nullable on the database, either that has to be changed or the definition of DocumentTypeData.documentTypeId must be changed.

2022-10-07 07:08 UTC, ntruchsess requested changes

2022-10-07 07:08 UTC, ntruchsess commented on src/marketplace/Offers.Library/Offers.Library.csproj
> -
please review your changes before committing and to avoid conflicts exclude whitespace-only changes of project-files from the commit

2022-10-07 07:28 UTC, jjeroch commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            offerDetail.OfferProviderData.Documents.GroupBy(d => d.documentTypeId).ToDictionary(g => g.Key, g => g.Select(d => new DocumentData(d.documentId, d.documentName))));
as discussed - lets put documentTypeId to notnullable
A quick recheck would be create to check if we have any code where we upload a document without a type, if so, we need to update the code to include the documenttype

2022-10-07 11:55 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    a.Documents.Select(d => new DocumentTypeData(d.DocumentType!.Id, d.Id, d.DocumentName))),
fixed

2022-10-07 12:48 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +            offerDetail.OfferProviderData.Documents.GroupBy(d => d.documentTypeId).ToDictionary(g => g.Key, g => g.Select(d => new DocumentData(d.documentId, d.documentName))));
Two places where we are not passing documenttypeid 
1)IdentityProviderController-->UploadOwnCompanyUsersIdentityProviderLinkDataAsync
2)UserController-->UploadOwnCompanyUsersIdentityProviderFileAsync

2022-10-11 09:04 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    a.Documents.Select(d => new DocumentTypeData(d.DocumentType!.Id, d.Id, d.DocumentName))),
the use of the navigational property ```d.DocumentType!.Id``` is redundant as the 'real' property ```d.DocumentTypeId``` is available

2022-10-11 09:06 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +                && email != null && EF.Functions.ILike(companyUser.Email!, $"%{email.Trim(escapeChar)}%"));
to fix the code-smell I suggest: ```&& (email == null || EF.Functions ...)``` (be aware this change is in conflict with https://github.com/catenax-ng/product-portal-backend/pull/260 )

2022-10-11 11:14 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
fixed

2022-10-11 11:14 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221007102646_CPLP-1625-ChangeDocumentTypeIdtoNonNullable.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
fixed

2022-10-11 11:15 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221007102646_CPLP-1625-ChangeDocumentTypeIdtoNonNullable.Designer.cs
> +﻿// <auto-generated />
fixed

2022-10-11 11:15 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    a.Documents.Select(d => new DocumentTypeData(d.DocumentType!.Id, d.Id, d.DocumentName))),
fixed

2022-10-11 13:18 UTC, ntruchsess commented on src/marketplace/Offers.Library/Offers.Library.csproj
> -
reverted

2022-10-11 13:19 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +                && email != null && EF.Functions.ILike(companyUser.Email!, $"%{email.Trim(escapeChar)}%"));
reverted as this was completely implemented in #260

2022-10-11 13:51 UTC, ntruchsess approved these changes

2022-10-11 13:51 UTC, merged