CPLP-1313-DbAudit App
catenax-ng/product-portal-backend pull request #257
Opened 2022-10-10 07:44 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1313

2022-10-11 08:47 UTC, ntruchsess requested changes

2022-10-11 08:47 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
please manually (re-)add license-header

2022-10-11 08:47 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221010092958_CPLP-1313-AuditOffer.cs
> +﻿using System;
please manually add license-header

2022-10-11 08:47 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221010092958_CPLP-1313-AuditOffer.Designer.cs
> +using System;
please manually add license-header

2022-10-12 07:31 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
fixed

2022-10-12 07:31 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221010092958_CPLP-1313-AuditOffer.cs
> +﻿using System;
fixed

2022-10-12 07:32 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221010092958_CPLP-1313-AuditOffer.Designer.cs
> +using System;
fixed

2022-10-13 11:51 UTC, ntruchsess commented
somehow the merge of main caused all changes from main to re-appear in the PR resulting in a whole bunch of conflicts. Looks as if the merge was done as a squash-commit.
I therefore I did restart on a new branch cherry-picking the existing commits recreating the migration: https://github.com/catenax-ng/product-portal-backend/pull/267
I therefore close this PR as redundant

2022-10-13 11:51 UTC, closed without merging