CPLP-1660 subscription log
catenax-ng/product-portal-backend pull request #262
Opened 2022-10-11 15:11 UTC by Phil91

Added logging to autoSetup on subscription
Added Endpoint for Apps AutoSetup

2022-10-11 18:22 UTC, ntruchsess requested changes
as I thought I would merge this right away I did some cosmetical changes. Didn't want to re-enable the role-check though as I was not sure whether this might have been explicitly requested by Julia for testing. Please pull before proceeding.

2022-10-11 18:22 UTC, ntruchsess commented on src/marketplace/Services.Service/Controllers/ServicesController.cs
> +    //[Authorize(Roles = "subscribe_service")]
I guess this has been removed for testing only? Please re-enable role-based authorisation-check

2022-10-11 18:58 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +                _logger.LogInformation(e.Message);
i provided a logging template to have a nicer information

2022-10-11 18:59 UTC, Phil91 commented on src/marketplace/Services.Service/Controllers/ServicesController.cs
> +    //[Authorize(Roles = "subscribe_service")]
jep, sorry for missing - re-enabled

2022-10-13 09:53 UTC, ntruchsess requested changes

2022-10-13 09:53 UTC, ntruchsess commented on tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
> +        var result = await sut.AutoSetupAppAsync(data, IamUserId).ConfigureAwait(false);
as the offerservice is not injected this call is not testing anything. If the result would have been tested for correctness, you would have noticed:
```
    public async Task AutoSetupService_ReturnsExcepted()
    {
        var offerAutoSetupResponseData = _fixture.Create<OfferAutoSetupResponseData>();
        // Arrange
        var offerService = A.Fake<IOfferService>();
        A.CallTo(() => offerService.AutoSetupServiceAsync(A<OfferAutoSetupData>._, A<IDictionary<string, IEnumerable<string>>>._, A<IDictionary<string, IEnumerable<string>>>._, A<string>._, A<OfferTypeId>._))
            .ReturnsLazily(() => offerAutoSetupResponseData);
        var data = new OfferAutoSetupData(Guid.NewGuid(), "https://www.offer.com");
//        _fixture.Inject(offerService); // when doing the service-injection the test passes.

        var sut = _fixture.Create<AppsBusinessLogic>();

        // Act
        var result = await sut.AutoSetupAppAsync(data, IamUserId).ConfigureAwait(false);

        // Assert
        result.Should().Be(offerAutoSetupResponseData);
    }
```

2022-10-13 10:21 UTC, ntruchsess approved these changes

2022-10-13 10:25 UTC, merged