feature/cplp-832-appdetail-refactoring
catenax-ng/product-portal-backend pull request #266
Opened 2022-10-13 09:35 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-832

2022-10-18 12:52 UTC, ntruchsess requested changes
It appears your PR contains many files that are completely unrelated to your change containing changes that apparently have been applied to main recently. That also causes quite a lot of conflicts in locations I'm pretty sure you did not really work on. Did you merge main squashing the requests?
Please resolve, I'm not going to review such a mess.
(The easiest was is to start a new branch an pick the commits you intend to keep - that will take way less time than trying to resolve the tons of conflicts you are facing now).

2022-10-19 13:42 UTC, ntruchsess requested changes

2022-10-19 14:00 UTC, ntruchsess requested changes

2022-10-19 14:19 UTC, ntruchsess requested changes
Please be aware that I did rework my comments multiple times to come up with the appropriate suggestion. Please re-check my comments.

2022-10-20 06:42 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    a.AgreementAssignedOffers.Where(agreementtAssignedOffer=>agreementtAssignedOffer.Agreement!.AgreementAssignedOfferTypes
Deleted this method

2022-10-20 06:42 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                    .Select(aaot => new AgreementAssignedOfferData(aaot.AgreementId, aaot.Agreement!.Name)).Distinct(),
fixed

2022-10-20 09:38 UTC, ntruchsess requested changes

2022-10-20 09:38 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +        foreach(var agreementConsentData in offerDetail.OfferProviderData.Agreements)
```var offerAgreementData = offerDetail.OfferProviderData.Agreements.Select(a => new OfferAgreement(a.Id,a.Name,a.ConsentStatus == null ? string.Empty : a.ConsentStatus.ToString()));````

2022-10-20 14:56 UTC, ntruchsess approved these changes

2022-10-20 14:56 UTC, merged