CPLP-1599 delete appuser role
catenax-ng/product-portal-backend pull request #270
Opened 2022-10-14 08:40 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1599

2022-10-18 13:25 UTC, ntruchsess requested changes

2022-10-18 13:25 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +            var userRole = new UserRole(roleId, string.Empty, appId);
only the primary key is required to remove the entity. The appId is not part of the primary key, only the id is.
Initialize the to be deleted entity as ```new UserRole(roleId,null!,null!);```

2022-10-18 13:25 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +            _context.UserRoles.Attach(userRole);
calling attach before remove is redundant.

2022-10-18 13:25 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +            await _context.SaveChangesAsync().ConfigureAwait(false);
for consistency with other code the call to SaveChangesAsync shall be done in the businesslogic.

2022-10-19 13:45 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +            _context.UserRoles.Attach(userRole);
fixed

2022-10-19 13:46 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +            var userRole = new UserRole(roleId, string.Empty, appId);
fixed

2022-10-20 14:22 UTC, ntruchsess approved these changes

2022-10-20 14:29 UTC, merged