CPLP-1657 add update service provider details endpoint
catenax-ng/product-portal-backend pull request #274
Opened 2022-10-17 10:15 UTC by Phil91

With this PR [CPLP-1657](https://jira.catena-x.net/browse/CPLP-1657) is resolved.

2022-10-17 10:37 UTC, Phil91 commented
I don't understand why TestCoverage is shown as 76.7% the shown as untested code is covered.

2022-10-17 11:09 UTC, evegufy commented
> I don't understand why TestCoverage is shown as 76.7% the shown as untested code is covered.

You mean the lines at the bottom here are covered?: https://sonarcloud.io/code?id=catenax-ng_product-portal-backend&pullRequest=274&selected=catenax-ng_product-portal-backend%3Asrc%2Fportalbackend%2FPortalBackend.DBAccess%2FRepositories%2FCompanyRepository.cs

2022-10-17 11:31 UTC, Phil91 commented
> > I don't understand why TestCoverage is shown as 76.7% the shown as untested code is covered.
> 
> You mean the lines at the bottom here are covered?: https://sonarcloud.io/code?id=catenax-ng_product-portal-backend&pullRequest=274&selected=catenax-ng_product-portal-backend%3Asrc%2Fportalbackend%2FPortalBackend.DBAccess%2FRepositories%2FCompanyRepository.cs

yes. they are covered with multiple test cases: https://github.com/catenax-ng/product-portal-backend/pull/274/files#diff-44c04d8737c33165098313143f0fd9098f1cbae600c82523df86f22af958188c

2022-10-18 07:17 UTC, evegufy commented
> > > I don't understand why TestCoverage is shown as 76.7% the shown as untested code is covered.
> > 
> > 
> > You mean the lines at the bottom here are covered?: https://sonarcloud.io/code?id=catenax-ng_product-portal-backend&pullRequest=274&selected=catenax-ng_product-portal-backend%3Asrc%2Fportalbackend%2FPortalBackend.DBAccess%2FRepositories%2FCompanyRepository.cs
> 
> yes. they are covered with multiple test cases: https://github.com/catenax-ng/product-portal-backend/pull/274/files#diff-44c04d8737c33165098313143f0fd9098f1cbae600c82523df86f22af958188c

Sometimes I see the following in the logs of sonarcloud https://github.com/catenax-ng/product-portal-backend/actions/runs/3264348820/jobs/5364854600#step:7:2500 , could it be connected to that?

2022-10-18 07:45 UTC, Phil91 commented
> > > > I don't understand why TestCoverage is shown as 76.7% the shown as untested code is covered.
> > > 
> > > 
> > > You mean the lines at the bottom here are covered?: https://sonarcloud.io/code?id=catenax-ng_product-portal-backend&pullRequest=274&selected=catenax-ng_product-portal-backend%3Asrc%2Fportalbackend%2FPortalBackend.DBAccess%2FRepositories%2FCompanyRepository.cs
> > 
> > 
> > yes. they are covered with multiple test cases: https://github.com/catenax-ng/product-portal-backend/pull/274/files#diff-44c04d8737c33165098313143f0fd9098f1cbae600c82523df86f22af958188c
> 
> Sometimes I see the following in the logs of sonarcloud https://github.com/catenax-ng/product-portal-backend/actions/runs/3264348820/jobs/5364854600#step:7:2500 , could it be connected to that?

okay, that's interesting never recognized that. Looks like the build server can't connect to docker properly. Since we need this to start our Integration and Database Tests it's very likely that the percentage is connected with that.

2022-10-18 17:20 UTC, ntruchsess requested changes
I did a small refactoring that allows to differentiate in between 'NotFound' and 'Forbidden'. 
Please pull before fixing the comments.

2022-10-18 17:20 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
that assert cannot fail as Action() has not been executed yet.

2022-10-18 17:20 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
that assert cannot fail as Action() has not been executed yet.

2022-10-18 17:20 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
that assert cannot fail as Action() has not been executed yet.

2022-10-18 17:20 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
that assert cannot fail as Action() has not been executed yet.

2022-10-18 17:20 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
that assert cannot fail as Action() has not been executed yet.

2022-10-18 17:26 UTC, ntruchsess requested changes

2022-10-18 17:26 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
that assert cannot fail as Action() has been declared but not yet been executed. It actually being scheduled to run by awaiting Assert.ThrowsAsync(Action).

2022-10-19 07:02 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
order fixed

2022-10-19 07:02 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
order fixed

2022-10-19 07:02 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
order fixed

2022-10-19 07:02 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
order fixed

2022-10-19 07:03 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
> +        A.CallTo(() => _portalRepositories.SaveAsync()).MustNotHaveHappened();
order fixed

2022-10-19 12:15 UTC, ntruchsess approved these changes

2022-10-19 12:15 UTC, merged