CPLP-734-exclude-delete-status
catenax-ng/product-portal-backend pull request #285
Opened 2022-10-24 14:55 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-734

2022-10-24 20:56 UTC, jjeroch commented on src/administration/Administration.Service/BusinessLogic/UserSettings.cs
> +    /// Document Type Id
@qxz2mqe why do we add something related to "Document Type Id"?

2022-10-24 20:58 UTC, jjeroch commented on tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
> +        };
@qxz2mqe  the test validates that active and inactive user status is received. Does it also validate inside the example that any other status especially DELETE is not included in the response?

2022-10-27 11:57 UTC, ntruchsess requested changes
https://jira.catena-x.net/browse/CPLP-734 is about adjusting 'GET /administration/user/owncompany/users'. You did modify 'DELETE /administration/user/owncompany/users'

2022-10-27 11:57 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
> +        };
it might be reasonable not to configure the CompanyUserStatus that are taken as active but to configure the status that is to be ignored. In case we add further status to the enum they would be ignored in case this configuration is not being adjusted accordingly.

2022-11-02 15:15 UTC, jjeroch commented
@qxz2mqe if all the comments added above are handled in the new pr - please delete this old pr and branch

2022-11-03 05:34 UTC, qxz2mqe commented
@jjeroch  I will delete the old PR

2022-11-04 04:57 UTC, closed without merging