CPLP-1458-app marketplace-controller-cleanup
catenax-ng/product-portal-backend pull request #295
Opened 2022-10-28 04:15 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1458

2022-11-02 09:19 UTC, Phil91 requested changes
One thing i recognized but could add in the review, in OfferReleaseData.cs the documentation isn't aligned with the code, please check.

2022-11-02 09:19 UTC, Phil91 commented on tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
>  namespace Org.CatenaX.Ng.Portal.Backend.Apps.Service.BusinessLogic.Tests;
Please check the unit tests, they can't be executed due to 3 errors.

2022-11-04 05:55 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +    private readonly INotificationService _notificationService;
fixed

2022-11-04 05:55 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        return  this.CreateAppAsync(appRequestModel);
fixed

2022-11-04 05:56 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +
fixed

2022-11-04 05:56 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            if(appDetails.descriptionLongIsNullOrEmpty)
This variable name was given by Norbert

2022-11-04 05:56 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            if(appDetails.descriptionShortIsNullOrEmpty)
This variable name was given by Norbert

2022-11-04 05:56 UTC, qxz2mqe commented on tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
>  namespace Org.CatenaX.Ng.Portal.Backend.Apps.Service.BusinessLogic.Tests;
fixed

2022-11-04 06:18 UTC, qxz2mqe commented on tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
>  namespace Org.CatenaX.Ng.Portal.Backend.Apps.Service.BusinessLogic.Tests;
fixed

2022-11-07 22:22 UTC, ntruchsess approved these changes

2022-11-07 22:24 UTC, ntruchsess approved these changes

2022-11-07 22:26 UTC, merged