CPLP-734-getowncompanyuser-excludedeletestatus
catenax-ng/product-portal-backend pull request #296
Opened 2022-10-28 09:00 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-734

2022-10-28 19:17 UTC, ntruchsess requested changes

2022-10-28 19:17 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                .Where(companyUser =>_settings.CompanyUserStatusIds.Contains(companyUser.CompanyUserStatusId))
that needs to be relocated into the base-query. Otherwise the pagination-metadata (count etc..) would not match the current page content. Also applying the Where after Skip() and Take() would reduce the number of items being returned on this particular page.

2022-10-31 10:50 UTC, jjeroch submitted a review, later dismissed
@qxz2mqe please also check and comment why the unit tests are failing. Can we get them running successfully?

2022-10-31 12:21 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                .Where(companyUser =>_settings.CompanyUserStatusIds.Contains(companyUser.CompanyUserStatusId))
I would like to discuss with you because same query method is being used for another end point

2022-11-02 04:52 UTC, qxz2mqe commented
@jjeroch  It was failing for other PR which I fixed

2022-11-07 22:37 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                .Where(companyUser =>_settings.CompanyUserStatusIds.Contains(companyUser.CompanyUserStatusId))
did fix my review-comment: https://github.com/catenax-ng/product-portal-backend/pull/296/commits/768e5a6c411784ff0c00a39baf3e2df0b7356ab8

2022-11-07 23:38 UTC, ntruchsess approved these changes

2022-11-07 23:39 UTC, merged