Feature/CPLP- 625 retrieve invited users
catenax-ng/product-portal-backend pull request #30
Opened 2022-05-04 05:20 UTC by qxz2mqe

CPLP- 625 retrieve invited users

2022-05-04 08:32 UTC, ntruchsess requested changes

2022-05-04 08:32 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +                          where invitation.CompanyApplicationId.ToString() == applicationId.ToString()
those calls of ToString seem to be redundant. Both sides are Guid (also on the database) and should be compared without any conversion

2022-05-04 08:32 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +    public class InvitedUsers
I suggest renaming to 'InvitedUser' (without the trailing 's'). I refers to a single instance

2022-05-04 08:32 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public string UserId { get; set; }
I'm not sure whether including the UserId is required or even helpful. (Of course it will do no harm ;-))
It's not mentioned in the userstory, please clarify with @jjeroch

2022-05-04 08:32 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public IEnumerable<Roles> InvitedUserRoles { get; set; }
I suggest to return the Role-names only:
`public IEnumerable<string> InvitedUserRoles { get; set; }`
The userstory doesn't mention the roles id and the boolean clientrole should be part of the response.
Please also clarify with @jjeroch

2022-05-04 08:32 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
> +        Task<InvitedUserRoleMapper> GetInvitedUsersDetail(Guid applicationId);
That should rather be:
`IAsyncEnumerable<InvitedUser> GetInvitedUsersDetail(Guid applicationId);`
InvitedUserRoleMapper is just an wrapper around the IEnumerable<InvitedUsers> plus instead of returning Task<IEnumerable<...>> it's always more efficient to return IAsyncEnumerable<...> (of course only if it is feasable)

2022-05-04 08:32 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        public async Task<InvitedUserRoleMapper> GetInvitedUsersDetail(Guid applicationId)
I suggest:
```
        public async IAsyncEnumerable<InvitedUsers> GetInvitedUsersDetail(Guid applicationId)
        {
            await foreach (var item in _portalDBAccess.GetInvitedUsersDetail(applicationId).ConfigureAwait(false))
            {
                var response = await _provisioningManager.GetClientRoleMappingsForUserAsync(item.UserId, _settings.KeyCloakClientID);
                var invitedUserRoles = response.Select(index =>
                    new Roles
                    {
                        Id = index.Id,
                        Name = index.Name,
                        ClientRole = index.ClientRole
                    });

                yield return new InvitedUsers
                {
                    UserId = item.UserId,
                    EmailId = item.EmailId,
                    InvitationStatus = item.InvitationStatus,
                    InvitedUserRoles = invitedUserRoles
                };
            }
        }                

```

2022-05-04 08:32 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs
> +        public async Task<IActionResult> GetInvitedUserDetailAsync([FromRoute] Guid applicationId)
I suggest:
```
        [HttpGet]
        [Authorize(Roles = "view_registration")]
        [Route("application/{applicationId}/invitedusers")]
        public IAsyncEnumerable<InvitedUsers> GetInvitedUserDetailAsync([FromRoute] Guid applicationId) =>
            _registrationBusinessLogic.GetInvitedUsersDetail(applicationId);
```
The controller knows how to handle IAsyncEnumerable response type properly. In dotnet6 it will even stream it to the client without buffering the whole response in memory first which allows kinda unlimited size of response.

Regarding the errorhandling-boilerplate code: We already have an errorhandler configured in the middleware, that explicit errorhandling and logging in the controller is now redundant (and will be removed from all constoller-methods in the near future).

2022-05-04 09:54 UTC, jjeroch commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public string UserId { get; set; }
@ntruchsess  & @qxz2mqe  true, we can delete row 10. The UserID is not used in this scenario

2022-05-04 09:56 UTC, jjeroch commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public IEnumerable<Roles> InvitedUserRoles { get; set; }
We need the Client Role itself. The role id is not relevant, but we need to ensure that we receive the Role Name - to be even more exact => it needs to be the client composite role name

2022-05-05 09:51 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public string UserId { get; set; }
fixed

2022-05-05 09:51 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public IEnumerable<Roles> InvitedUserRoles { get; set; }
fixed

2022-05-05 09:52 UTC, qxz2mqe commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        public async Task<InvitedUserRoleMapper> GetInvitedUsersDetail(Guid applicationId)
fixed

2022-05-05 09:52 UTC, qxz2mqe commented on src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs
> +        public async Task<IActionResult> GetInvitedUserDetailAsync([FromRoute] Guid applicationId)
fixed

2022-05-05 10:23 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/InvitedUsers.cs
> +        public string UserId { get; set; }
userid removed from response

2022-05-05 10:51 UTC, ntruchsess approved these changes

2022-05-05 10:51 UTC, merged