feature/cplp-1735-delete registration document
catenax-ng/product-portal-backend pull request #306
Opened 2022-11-04 04:50 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1735

2022-11-04 21:25 UTC, jjeroch submitted a review, later dismissed

2022-11-04 21:25 UTC, jjeroch commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +                document.CompanyUser!.Company!.CompanyApplications.Any(companyApplication => companyApplication.ApplicationStatusId == CompanyApplicationStatusId.SUBMITTED)
@qxz2mqe please recheck the logic. As per the requirement the company_application should'nt be in any of the following status 
- submitted
- declined
- confirmed

The code seems to only consider "submitted" and not "declined" and "confirmed"

2022-11-04 21:32 UTC, jjeroch commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new NotFoundException("Document does not exist.");
@qxz2mqe can you please recheck the exception. I wonder if this exception should not rather be located at the top. If the GUID is empty, the scenarios/exception checks above would not be possible.

2022-11-04 21:33 UTC, jjeroch commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!details.IsSameUser)
@qxz2mqe I am a bit unsure about the statement "IsSameUser" - what does this validate?
Important: the user doesn't need to be the same. They only need to belong to the same application.

2022-11-07 05:32 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +                document.CompanyUser!.Company!.CompanyApplications.Any(companyApplication => companyApplication.ApplicationStatusId == CompanyApplicationStatusId.SUBMITTED)
fixed

2022-11-07 05:32 UTC, qxz2mqe commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new NotFoundException("Document does not exist.");
fixed

2022-11-07 05:33 UTC, qxz2mqe commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!details.IsSameUser)
IsSameUser rename as IsSameApplicationUser

2022-11-09 08:08 UTC, ntruchsess requested changes
please pull main and fix the conflicts so I can to the review

2022-11-09 08:43 UTC, qxz2mqe commented
Merged Main and Resolved Conflict

2022-11-09 17:27 UTC, ntruchsess approved these changes

2022-11-09 17:27 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (details.DocumentId == Guid.Empty)
fixed

2022-11-09 17:27 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ArgumentException($"Document deletion is not allowed. DocumentType must be either :{string.Join(",", _settings.DocumentTypeIds)}");
fixed

2022-11-09 17:28 UTC, merged