CPLP-1634 notifications
catenax-ng/product-portal-backend pull request #307
Opened 2022-11-04 10:16 UTC by Phil91

2022-11-08 13:22 UTC, ntruchsess requested changes

2022-11-08 13:22 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Extensions/NotificationTopicExtensions.cs
> +}
newline at end of file ;-)

2022-11-08 13:22 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Extensions/NotificationTopicExtensions.cs
> +            NotificationTypeId.INFO => NotificationTopicId.INFO,
@jjeroch @Phil91 I suggest we should relocate this mapping into the database, entity name like 'NotificationTypeAssignedTopic'. Then the query would join this table to do the grouping.
Having this mapping in code implies that any later change would result in notifications that were created before the change would not longer comply with this mapping. When the mapping is done in the database exisiting notification records would remain unchanged while the mapped topic would change with the change of the mapping-table.

2022-11-08 13:22 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
> +using Microsoft.EntityFrameworkCore;
keep usings in alphabetical order to improve readability.

2022-11-08 16:31 UTC, Phil91 commented on src/notification/Notification.Service/Models/NotificationSorting.cs
> +namespace Notification.Service.Models;
done

2022-11-08 16:31 UTC, Phil91 commented on src/notification/Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +}
done

2022-11-08 16:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Extensions/NotificationTopicExtensions.cs
> +}
done

2022-11-08 16:57 UTC, ntruchsess commented on src/notification/Notification.Service/Models/NotificationSorting.cs
> +namespace Notification.Service.Models;
cannot see - any outstanding commits ready to push?

2022-11-08 16:59 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +            .ToDictionaryAsync(x => x.Key, x => x.Count);
i like that. changed.

2022-11-08 16:59 UTC, Phil91 commented on src/notification/Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
> +        var unreadNotifications = details.Where(x => !x.Key.IsRead);
changed

2022-11-08 18:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Extensions/NotificationTopicExtensions.cs
> +            NotificationTypeId.INFO => NotificationTopicId.INFO,
added the new mapping entity

2022-11-08 18:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +            .ToDictionaryAsync(x => x.Key, x => x.Count);
need to check it tomorrow, currently getting an error from the query

2022-11-09 11:15 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +            .ToDictionaryAsync(x => x.Key, x => x.Count);
fixed

2022-11-09 12:57 UTC, ntruchsess approved these changes

2022-11-09 12:57 UTC, merged