feature/cplp-1732-document-enum-db-adjustment
catenax-ng/product-portal-backend pull request #308
Opened 2022-11-04 12:06 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1732

2022-11-04 20:45 UTC, jjeroch commented
@qxz2mqe we need to do an update in devenv as well. Have you already considered that?

2022-11-07 05:45 UTC, qxz2mqe commented
yes

2022-11-07 07:41 UTC, Phil91 requested changes

2022-11-07 07:41 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221104115911_CPLP-1732-ChangeDocumentTypeEnum.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Please add the file header to the generated files

2022-11-07 07:41 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221104115911_CPLP-1732-ChangeDocumentTypeEnum.Designer.cs
> +﻿// <auto-generated />
Please add the file header to the generated files

2022-11-07 07:41 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
Please readd the file header

2022-11-07 07:49 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221104115911_CPLP-1732-ChangeDocumentTypeEnum.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
fixed

2022-11-07 07:49 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221104115911_CPLP-1732-ChangeDocumentTypeEnum.Designer.cs
> +﻿// <auto-generated />
fixed

2022-11-07 07:49 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
fixed

2022-11-07 08:02 UTC, Phil91 commented
@qxz2mqe as Julia mentioned please create a PR in devenv for your database changes as well. Therefor you need to run `backup_portal_basedata.sh` & `backup_portal_data.sh` against your updated database.

2022-11-08 13:32 UTC, ntruchsess approved these changes

2022-11-08 13:37 UTC, Phil91 approved these changes
As soon as devenv is ready, this PR is ready for merging

2022-11-09 10:03 UTC, merged