AppService unit tests
catenax-ng/product-portal-backend pull request #31
Opened 2022-05-04 18:19 UTC by wira-mms

2022-05-05 12:58 UTC, qxz2mqe commented on tests/marketplace/CatenaX.NetworkServices.App.Service.Tests/AppBusinessLogicTests.cs
> +            var contextFake = A.Fake<PortalDbContext>();
Better if we can move it into constructor.  var contextFake = A.Fake<PortalDbContext>();

2022-05-08 19:09 UTC, ntruchsess requested changes
I like the way dbsets are being faked. :-)
Please just fix this tiny remark in class IamUser

2022-05-09 10:10 UTC, wira-mms commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/IamUser.cs
> +        public IamUser(string iamUserId, Guid companyUserId, CompanyUser? companyUser = null)
https://github.com/catenax-ng/product-portal-backend/pull/31/commits/fcb420fccddf35e20ed16965662d72f4cf0024d4

2022-05-09 13:02 UTC, ntruchsess approved these changes

2022-05-09 13:13 UTC, merged