CPLP-1601-app-roles-activeapp
catenax-ng/product-portal-backend pull request #326
Opened 2022-11-16 07:15 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1601

2022-11-16 10:03 UTC, ntruchsess approved these changes
@qxz2mqe : I did some cleanup removing the redundancy with preexisting code, please pull in case you need to add further changes.
I noticed Offer.Name is nullable in the db. That implies the notification might not contain a valid app name (if it is not yet set). Please clarify with @jjeroch whether this is ok or should result in an error indicating the app-name must be set before.

2022-11-16 10:06 UTC, ntruchsess requested changes
please add unit-tests for the new code

2022-11-18 07:31 UTC, qxz2mqe commented
@ntruchsess Added Unit Test

2022-11-18 09:50 UTC, ntruchsess approved these changes

2022-11-18 09:50 UTC, merged