CPLP-914-post-company-bpn
catenax-ng/product-portal-backend pull request #333
Opened 2022-11-17 11:26 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-914

2022-11-21 08:34 UTC, ntruchsess requested changes

2022-11-21 08:34 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (businessPartnerNumbers.Contains(bpn))
reading all datasets to check the existence of a specific one on client-side is inefficiency at its worst. Please integrate this check into the query being called in line 382 (GetBpnForIamUserUntrackedAsync)

2022-11-21 08:34 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!bpn.ToUpper().StartsWith("BPNL"))
please use overload StartsWith(String, StringComparison) that allows to do the comparism ignoring case in a single step. (see: https://learn.microsoft.com/en-us/dotnet/api/system.string.startswith?view=net-6.0#system-string-startswith(system-string-system-stringcomparison) )

2022-11-21 08:34 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (string.IsNullOrWhiteSpace(result.Bpn))
this is not implementing the requirement 'bpn can only get added, not changed (means if the company already has an bpn, the admin can not change the bpn; BUT the admin can add an bpn if there is no bpn yet added)' that is specified in https://jira.catena-x.net/browse/CPLP-914
obviously to add an additional BusinessPartnerNumber to a company that already does have a BusinessPartnerNumber assigned we'd need to change the database-scheme to allow 1-n releationship in between company and BusinessPartnerNumber adding a separate BusinessPartnerNumber-entity that links back to the company. We need to discuss with @jjeroch how to proceed here

2022-11-21 09:47 UTC, ntruchsess requested changes

2022-11-21 09:47 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (string.IsNullOrWhiteSpace(result.Bpn))
in case the BusinessPartnerNumber is already set I suggest to throw ConflictException to indicate the update cannot be done.

2022-11-22 06:10 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!bpn.ToUpper().StartsWith("BPNL"))
fixed

2022-11-22 06:11 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (businessPartnerNumbers.Contains(bpn))
fixed

2022-11-22 06:11 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ArgumentException("BPN must contain exactly 16 characters long.", nameof(bpn));
fixed

2022-11-23 10:24 UTC, ntruchsess requested changes

2022-11-23 10:24 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(company => company.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId== iamUserId)
That condition enforces that the logged in user must be a member of the company that the businessPartnerNumber is to be updated. From my understanding this condition is not required (resp. incorrect) as a catena-X administrator shall be able to update the businesspartnernumber of a company that has a pending application. This CatenaX-Admin is certainly not member of any such company.

2022-11-23 10:24 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        await foreach (var item in _portalRepositories.GetInstance<IUserRepository>().GetBpnForIamUserUntrackedAsync(iamuserId, applicationId, bpn).ConfigureAwait(false))
that condition is not suitable here - if no match is found the IAsyncEnumerable will have zero items. Checking a result for being default makes sense when using 'SingleOrDefault()' not AsAsyncEnumerable().

Also processing this result-set while iterating makes it hard to understand the query is mostly for validating preconditions. It's known beforehand only a single dataset is to be updated (and only in case the preconditions are met).

I suggest to do all checks beforehand throwing the appropriate exception if the condition is not met, pick the item that corresponds to the application and then do the update:

like so:

```
var result = await _portalRepositories.GetInstance<IUserRepository>().GetBpnForIamUserUntrackedAsync(iamuserId, applicationId, bpn).ToListAsync().ConfigureAwait(false);
if (!result.Any(item => item.IsApplicationCompany))
{
	throw new NotFoundException($"application {applicationId} not found");
}
if (result.Any(item => !item.IsApplicationCompany))
{
	throw new ConflictException($"BusinessPartnerNumber is already assigned to a different company");
}
var applicationCompanyData = result.Single(item => item.IsApplicationCompany);
if (!applicationCompanyData.IsApplicationPending)
{
	throw new ConflictException($"application {applicationId} for company {applicationCompanyData.CompanyId} is not pending");
}
if (!string.IsNullOrWhiteSpace(applicationCompanyData.BusinessPartnerNumber))
{
	throw new ConflictException($"BusinessPartnerNumber of company {applicationCompanyData.CompanyId} has already been set.");
}
_portalRepositories.GetInstance<ICompanyRepository>().AttachAndModifyCompany(applicationCompanyData.CompanyId, c =>
{
	c.BusinessPartnerNumber = bpn;
});
await _portalRepositories.SaveAsync().ConfigureAwait(false);
```

That code assumes the query is changed to:
```
public IAsyncEnumerable<(bool IsApplicationCompany, bool IsApplicationPending, string? BusinessPartnerNumber, Guid CompanyId)> GetBpnForIamUserUntrackedAsync(string iamUserId, Guid applicationId, string businessPartnerNumber) =>
    _dbContext.Companies
        .AsNoTracking()
        .Where(company => 
            company.CompanyApplications.Any(application => application.Id == applicationId) ||
            company.BusinessPartnerNumber == businessPartnerNumber)
        .Select(company =>new ValueTuple<bool, bool, string?, Guid>(
            company.CompanyApplications.Any(application => application.Id == applicationId),
            company.CompanyStatusId==CompanyStatusId.PENDING,
            company.BusinessPartnerNumber,
            company.Id))
        .AsAsyncEnumerable();
```

2022-11-24 06:41 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!bpn.ToUpper().StartsWith("BPNL", StringComparison.OrdinalIgnoreCase))
fixed

2022-11-24 06:41 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .Where(company => company.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId== iamUserId)
fixed

2022-11-24 06:42 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        await foreach (var item in _portalRepositories.GetInstance<IUserRepository>().GetBpnForIamUserUntrackedAsync(iamuserId, applicationId, bpn).ConfigureAwait(false))
implemented the change

2022-11-25 07:52 UTC, ntruchsess approved these changes

2022-11-25 07:53 UTC, merged