CPLP-1791-getapplication
catenax-ng/product-portal-backend pull request #340
Opened 2022-11-22 12:11 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1791

2022-11-22 14:35 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var registrationData = await _portalRepositories.GetInstance<IUserRepository>().GetRegistrationDataUntrackedAsync(applicationId, iamUserId, _settings.DocumentTypeIds).ConfigureAwait(false);
Are the documentTypeIds from the settings used for another use case as well?

2022-11-23 05:33 UTC, qxz2mqe commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var registrationData = await _portalRepositories.GetInstance<IUserRepository>().GetRegistrationDataUntrackedAsync(applicationId, iamUserId, _settings.DocumentTypeIds).ConfigureAwait(false);
yes documenttypeid is being used for another use case

2022-11-24 07:09 UTC, Phil91 requested changes

2022-11-24 07:09 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public Task<RegistrationData?> GetRegistrationDataUntrackedAsync(Guid applicationId, string iamUserId, IEnumerable<DocumentTypeId> documentTypes) =>
Could you please provide unit tests for the repository

2022-11-24 07:09 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +                company.CompanyUsers.SelectMany(companyUser => companyUser!.Documents!.Where(document=>documentTypes.Contains(document.DocumentTypeId)).Select(document => new RegistrationDocumentName
Could you please provide unit tests

2022-11-24 10:23 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +    public Task<RegistrationData?> GetRegistrationDataUntrackedAsync(Guid applicationId, string iamUserId, IEnumerable<DocumentTypeId> documentTypes) =>
Added Unit Test

2022-11-25 07:22 UTC, Phil91 approved these changes

2022-11-25 07:22 UTC, merged