CPLP-1797 daps endpoint
catenax-ng/product-portal-backend pull request #342
Opened 2022-11-22 14:19 UTC by Phil91

In this PR [CPLP-1797](https://jira.catena-x.net/browse/CPLP-1797) is resolved.

Please also review the database [PR](https://github.com/tractusx-team-portal-onboarding/devenv/pull/179)

2022-11-23 15:22 UTC, jjeroch commented
@Phil91 can we do a minor enhancement? see latest comment in https://jira.catena-x.net/browse/CPLP-1797

2022-11-23 16:09 UTC, Phil91 commented
> @Phil91 can we do a minor enhancement? see latest comment in https://jira.catena-x.net/browse/CPLP-1797

@jjeroch done - see this [commit](https://github.com/catenax-ng/product-portal-backend/pull/342/commits/74c6b65855b2317b789c82eca89931946edf79a8)

2022-11-23 17:01 UTC, ntruchsess requested changes

2022-11-24 07:15 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20221122171647_CPLP-1797-AddDapsRegistration.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
done

2022-11-24 07:15 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Connector.cs
> +    public bool? DapsRegistrationSuccessful { get; set; }
going to clarify that with @jjeroch

2022-11-24 07:16 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [ProducesResponseType(typeof(bool), StatusCodes.Status200OK)]
done

2022-11-24 12:07 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/DapsService.cs
> +            return false;
changed the behaviour. for the CreateConnector case the process must not fail, therefor we just return null. for the trigger daps case we'll throw an serviceException

2022-11-24 12:07 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/DapsService.cs
> +            return response.IsSuccessStatusCode;
safe as above

2022-11-24 12:08 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Connector.cs
> +    public bool? DapsRegistrationSuccessful { get; set; }
The bool should stay nullable for later processes

2022-11-28 13:18 UTC, ntruchsess approved these changes

2022-11-28 13:35 UTC, merged