CPLP-1800 add bpdm service
catenax-ng/product-portal-backend pull request #349
Opened 2022-11-24 08:32 UTC by Phil91

2022-11-28 17:04 UTC, ntruchsess requested changes

2022-11-28 17:04 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                    x.Company!.BusinessPartnerNumber!,
as BusinessPartnerNumber is nullable in the database it must also be declared nullable in the db-model. (same for zipcode)
The businessLogic shall validate and throw ConflictException if those values are mandatory on the api being called.

2022-11-29 10:36 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/BpdmService.cs
> +    public async Task<bool> TriggerBpnDataPush(BpdmData data, CancellationToken cancellationToken)
done

2022-11-29 10:37 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> -    public Task UpdateCompanyBpn(Guid applicationId, string bpn)
changed.

2022-12-02 15:35 UTC, ntruchsess approved these changes

2022-12-02 21:20 UTC, merged