Email Templates Styling
catenax-ng/product-portal-backend pull request #352
Opened 2022-11-25 22:42 UTC by jjeroch

2022-11-28 08:11 UTC, Phil91 reviewed
Other than the two title comments, the emails look fine

2022-11-28 08:11 UTC, Phil91 commented on src/mailing/Mailing.Template/EmailTemplates/serviceprovider_subscription_request.html
> +    <title>Invite</title><!--[if (mso 16)]>
The title did change to invite, that should not make any problems, but maybe we want to change it to _Catena-X Service Subscription Request_ for consistency reasons?

2022-11-28 08:11 UTC, Phil91 commented on src/mailing/Mailing.Template/EmailTemplates/serviceprovider_subscription_activation.html
> +    <title>Invite</title><!--[if (mso 16)]>
The title did change as mentioned below, should not make any problems nor a user would see this in his mail program, but we may want to change that back?

2022-11-28 11:56 UTC, jjeroch commented
@Phil91 quick question regarding the app subscription. Are you using the service subscription activation template for apps as well or do we do not have any "App Subscription Activation" message/email so far?

2022-11-28 15:32 UTC, Phil91 commented
> @Phil91 quick question regarding the app subscription. Are you using the service subscription activation template for apps as well or do we do not have any "App Subscription Activation" message/email so far?

@jjeroch currently we just create a notification. there is no mail which gets send. I could add a mail which gets send when activating the app subscription. shouldn't be a lot of effort

2022-11-29 07:25 UTC, Phil91 commented
> > @Phil91 quick question regarding the app subscription. Are you using the service subscription activation template for apps as well or do we do not have any "App Subscription Activation" message/email so far?
> 
> @jjeroch currently we just create a notification. there is no mail which gets send. I could add a mail which gets send when activating the app subscription. shouldn't be a lot of effort

@jjeroch i've added the logic to send the app activation mail

2022-11-29 08:30 UTC, Phil91 approved these changes

2022-11-29 12:24 UTC, Phil91 commented
@ntruchsess could you please review this PR as well since i added the functionallity to send the subscriptionActivation  Mail

2022-11-30 09:42 UTC, ntruchsess requested changes

2022-11-30 09:42 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +                { "offerName", appName! },
either we validate and throw ConflictException in case AppName is not yet set or we provide a default like 'appName ?? "unknown App"'.

2022-11-30 09:42 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                app.OfferSubscriptions.SingleOrDefault(assignedApp => assignedApp.CompanyId == companyId) == null ? app.OfferSubscriptions.Single(assignedApp => assignedApp.CompanyId == companyId).Re
that's will not improve anything as this will translate into sql that is 100% redundant. In SQL you just join everything that needs to be joined and the database then traverses the joined tables as it finds data and stops traversing if there is none.
Also isMemberOfCompanyProvidingApp is redundant with companyUserId (being empty in case the user is not found).
I suggest:
```
public Task<(OfferSubscription? companyAssignedApp, string? appName, Guid companyUserId, string? email, string? firstname)> GetCompanyAssignedAppDataForProvidingCompanyUserAsync(Guid appId, Guid companyId, string iamUserId) =>
    _context.Offers
        .Where(app => app.Id == appId)
        .Select(app => new {
            App = app,
            OfferSubscription = app.OfferSubscriptions.SingleOrDefault(assignedApp => assignedApp.CompanyId == companyId),
        })
        .Select(x => new ValueTuple<OfferSubscription?, string?, Guid, string?, string?>(
            x.OfferSubscription,
            x.App.Name,
            x.App.ProviderCompany!.CompanyUsers.SingleOrDefault(companyUser => companyUser.IamUser!.UserEntityId == iamUserId)!.Id,
            x.OfferSubscription!.Requester!.Email,
            x.OfferSubscription.Requester.Firstname
        ))
        .SingleOrDefaultAsync();
```

2022-11-30 10:14 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +                { "offerName", appName! },
At this point the app should have the name set, thus we go with the ConflictException

2022-11-30 10:14 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                app.OfferSubscriptions.SingleOrDefault(assignedApp => assignedApp.CompanyId == companyId) == null ? app.OfferSubscriptions.Single(assignedApp => assignedApp.CompanyId == companyId).Re
edited

2022-11-30 17:44 UTC, ntruchsess approved these changes

2022-11-30 17:44 UTC, merged