Feature/cplp 1518 approve app release
catenax-ng/product-portal-backend pull request #354
Opened 2022-11-29 07:09 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1518

2022-11-29 08:29 UTC, Phil91 requested changes
Please add unit tests as well

2022-11-29 08:29 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                true,
This bool value is not needed. You can check in the BL if the result is == default. When no offer exists for the given id the default would be returned.

2022-11-29 08:29 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        if (!appDetails.OfferExists)
this check must be changed to `appDetails == default` since the repository would return a default value when the given app does not exists

2022-11-29 09:49 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                true,
fixed

2022-11-29 09:49 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        if (!appDetails.OfferExists)
fixed

2022-11-29 09:50 UTC, qxz2mqe commented
@Phil91 I have added the Unit Test

2022-11-29 17:56 UTC, Phil91 commented
@qxz2mqe the implementation looks good for me. But before approving the PR I'd like to discuss with you and @jjeroch if we really don't want to add a user validation at all. With this implementation everyone with the role _approve_app_release_ would be able to approve the app.

2022-11-30 09:49 UTC, Phil91 commented
> @qxz2mqe the implementation looks good for me. But before approving the PR I'd like to discuss with you and @jjeroch if we really don't want to add a user validation at all. With this implementation everyone with the role _approve_app_release_ would be able to approve the app.

After discussing we will have a followup story in the future to add a check if the current user is assigned to an operating company.

2022-11-30 09:53 UTC, Phil91 requested changes

2022-11-30 09:53 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            throw new ConflictException($"Apps in InCorrect Status {appDetails.IsStatusInReview} ");
Just recognized, the message would always be _Apps in InCorrect Status false_ if we want to get the current status of the app the repository should return the status instead of the bool identifier if the app is in the correct state

2022-11-30 09:53 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                offer.Name!
We should return the nullable value here and throw a ConflictException in the BusinessLogic if the AppName is null

2022-11-30 11:05 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +            throw new ConflictException($"Apps in InCorrect Status {appDetails.IsStatusInReview} ");
fixed

2022-11-30 11:06 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                offer.Name!
fixed

2022-12-01 06:59 UTC, Phil91 approved these changes

2022-12-01 07:00 UTC, merged