CPLP-1833 company role consent
catenax-ng/product-portal-backend pull request #358
Opened 2022-11-30 19:37 UTC by Phil91

2022-12-02 17:31 UTC, ntruchsess requested changes

2022-12-02 17:31 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        consentRepository.AttachAndModifiesConsents(consentsToInactivate, consent =>
attaching tracked entities is pointless:
https://github.com/catenax-ng/product-portal-backend/blob/1936198c234559b1559b73524b6a2873fe07201b/src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs#L49

(We should consider to change the query to return only those fields that are required to identify and apply the changes instead of full tracked entities).

2022-12-02 22:55 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        consentRepository.AttachAndModifiesConsents(consentsToInactivate, consent =>
did a bit of refactoring.

2022-12-05 21:11 UTC, ntruchsess approved these changes
I did equivalent refactoring in respect to applicationAssingedRoles adjusting the unit-tests accordingly. Please double-check before merging

2022-12-06 07:11 UTC, merged