Feature/cplp 1606 approve service offering
catenax-ng/product-portal-backend pull request #362
Opened 2022-12-02 09:48 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1606

2022-12-05 07:05 UTC, Phil91 requested changes
The build of the unit tests failed, please have a look into it and fix the unit tests if needed

2022-12-05 07:05 UTC, Phil91 commented on src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
> +    public async Task ApproveServiceRequestAsync(Guid appId, string iamUserId)
Since this method does the same as the ApproveAppRequestAsync in the AppReleaseBuisnessLogic, please move the logic to OfferService, you would than need to call the offerService from here and the AppReleaseBusinessLogic.

The Method in the offerService would also receive the OfferTypeId and _settings.ApproveServiceNotificationTypeIds as Parameter.

2022-12-05 19:49 UTC, ntruchsess approved these changes
@Phil91 @qxz2mqe I did do the required refactoring, merged the changes from CPLP-1605 and recreated the migration. Codingwise it should be fine now, please double-check.
Before merging adjust the secrets accordingly! (see my comments).
Devenv PR https://github.com/tractusx-team-portal-onboarding/devenv/pull/184 is also updated and ready to merge.

2022-12-06 05:26 UTC, qxz2mqe commented on src/marketplace/Apps.Service/appsettings.json
> +    "ApproveAppUserRoles": {}
Resolved

2022-12-06 05:26 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
> +    public IDictionary<string, IEnumerable<string>> ApproveAppUserRoles { get; set; } = null!;
Resolved

2022-12-06 05:26 UTC, qxz2mqe commented on src/marketplace/Services.Service/appsettings.json
> +    "ApproveServiceUserRoles": {},
Resolved

2022-12-06 07:14 UTC, merged