CPLP-1828-registration-document-refactor
catenax-ng/product-portal-backend pull request #367
Opened 2022-12-06 12:24 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-1828

2022-12-06 13:51 UTC, Phil91 requested changes

2022-12-06 13:51 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .Where(iamUser => iamUser.CompanyUser!.Company!.CompanyApplications.Any(application => application.Id == applicationId))
we should add a check if the user is part of the company of the given application, otherwise any user could see the documents for a specific application

2022-12-07 03:53 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .Where(iamUser => iamUser.CompanyUser!.Company!.CompanyApplications.Any(application => application.Id == applicationId))
As part of this requirement the documents uploaded by another user under the same application id should also be visible . Earlier we had validation where executing user can see only document uploaded by himself

2022-12-07 07:29 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .Where(iamUser => iamUser.CompanyUser!.Company!.CompanyApplications.Any(application => application.Id == applicationId))
correct, but we still should check that the users are in the same company of the given application, if we don't a user of company a would be able to access a document of company b with the application id, that would be a huge security issue.

2022-12-07 08:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .Where(iamUser => iamUser.CompanyUser!.Company!.CompanyApplications.Any(application => application.Id == applicationId))
oversaw the where check - all good.

2022-12-07 08:34 UTC, Phil91 approved these changes

2022-12-07 08:48 UTC, merged

2022-12-07 08:54 UTC, ntruchsess requested changes

2022-12-07 08:54 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +            .Where(iamUser => iamUser.CompanyUser!.Company!.CompanyApplications.Any(application => application.Id == applicationId))
actually the query does not check the calling user is associated with the application. It will return documents of any application regardless whether the company of the calling user is the one that applies.
(Side note: having removed any iam-user-related criteria it's nonsense to start the query at 'IamUsers' given that none of the fields is being referenced any more. If the criteria would be correct the query then should rather start at 'Documents')