Self Service: Create App
catenax-ng/product-portal-backend pull request #37
Opened 2022-05-06 15:26 UTC by wira-mms

2022-05-08 19:54 UTC, ntruchsess requested changes

2022-05-08 19:54 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            await this.context.Apps.AddAsync(appEntity).ConfigureAwait(false);
According to the documentation AddAsync should only be used if value generators are being used that require it:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-6.0
In all other cases the use of synchronous Add is recommended.
(same with 'AddRangeAsync' which is being used few lines below)

2022-05-08 19:54 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            await transaction.CommitAsync();
Why doing several calls to the database within an explicitly controlled transaction and not just build all related entities in memory and call save only once (which does the transaction-management implicitly)?

2022-05-08 19:54 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            var appLicenseEntity = new AppLicense(Guid.Empty, appInputModel.Price);
Guid.Empty?

2022-05-08 19:54 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            var appEntity = new PortalBackend.PortalEntities.Entities.App(Guid.Empty, appInputModel.Provider, DateTimeOffset.UtcNow)
Why Guid.Empty?
There is no guid-generation set up in the database (yet). If you want to introduce such we should discuss this in a separate call.
Guids can be generated by the program using Guid.NewGuid()

2022-05-08 19:54 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            try
please use the GeneralHttpErrorHandler (project CatenaX.NetworkServices.Framework.ErrorHandling) and remove the logging / statuscode-mapping boilerplate code (as it is done e.g. here: https://github.com/catenax-ng/product-portal-backend/blob/30f9db58e66ec40cb73a007e73a5b09a690fadf9/src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs#L121 )
To enable just add the GeneralHttpErrorHandler to the middleware in program.cs:
https://github.com/catenax-ng/product-portal-backend/blob/30f9db58e66ec40cb73a007e73a5b09a690fadf9/src/registration/CatenaX.NetworkServices.Registration.Service/Program.cs#L128

2022-05-09 07:33 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            try
https://github.com/catenax-ng/product-portal-backend/pull/37/commits/ad9459cc8fe1adec5c1dbfd5a5cf952d0db39f39

2022-05-09 08:45 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            var appEntity = new PortalBackend.PortalEntities.Entities.App(Guid.Empty, appInputModel.Provider, DateTimeOffset.UtcNow)
https://github.com/catenax-ng/product-portal-backend/pull/37/commits/2826aca1596684a3c35e02f075af784d9cf6964e

2022-05-09 08:45 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            var appLicenseEntity = new AppLicense(Guid.Empty, appInputModel.Price);
https://github.com/catenax-ng/product-portal-backend/pull/37/commits/2826aca1596684a3c35e02f075af784d9cf6964e

2022-05-09 08:45 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            await transaction.CommitAsync();
https://github.com/catenax-ng/product-portal-backend/pull/37/commits/2826aca1596684a3c35e02f075af784d9cf6964e

2022-05-09 08:45 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            await this.context.Apps.AddAsync(appEntity).ConfigureAwait(false);
https://github.com/catenax-ng/product-portal-backend/pull/37/commits/2826aca1596684a3c35e02f075af784d9cf6964e

2022-05-09 09:14 UTC, ntruchsess approved these changes

2022-05-09 13:21 UTC, merged