App service implementation
catenax-ng/product-portal-backend pull request #4
Opened 2022-04-08 08:43 UTC by wira-mms

- [x] GetAllActiveApps()
- [ ] GetFavouritesForCurrentUser()
- [ ] SetFavouriteForCurrentUser()
- [ ] RemoveFavouriteForCurrentUser()

2022-04-09 20:15 UTC, ntruchsess requested changes
please see me comments and check https://github.com/catenax-ng/product-portal-backend/pull/10 for a more efficient version

2022-04-09 20:15 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/AppViewModel.cs
> +        public ICollection<string> UseCases { get; set; } = new HashSet<string>();
I suggest the use or IEnumerable with default 'Enumerable.Empty' instead of ICollection to indicate it is not intended to add anything to the property but set (and thus replace) the reference entirely.

2022-04-12 18:27 UTC, ntruchsess requested changes
see my comments inline

2022-04-12 18:27 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +        public async Task RemoveFavouriteAppForUserAsync(Guid appId, Guid userId)
please use string as type of userId. While the userIds we retrive from Keycloak by default look like guids there is no guarantee it will always be a guid. The field in table 'user_entity' (see the schema of keycloak-db) is of type varchar(36) and you may pass in whatever 36char string on creation of a new keycloak user. It just happens that keycloak makes use of guids if you do not pass in your id of choice.

2022-04-12 18:27 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            var app = companyUser.Apps.FirstOrDefault(a => a.Id == appId);
why not just remove the entry from CompanyUserAppAssignedFavorites like 'context.Delete(new CompanyUserAppAssignedFavorite { CompanyUserId = companyUserId, AppId = appId };'
There really is no benefit in retrieving any of the linked entities before. If you really(!) want to know the entry actually exists before deleting it you'd use context.CompanyUserAppAssignedFavorites.FindAsync( new CompanyUserAppAssignedFavorite { .... }) before and delete the retrieved entity but this will only work reliably when being enclosed in a single transaction-context with the deletion. (The entry might be removed from the db in a parallel thread while this one executes). As the outcome is correct even if the entry is not existing before the deletion (and we certainly do not want to lock that on the database if it really does not make a difference) there is no point in first reading then deleting an entry that should be gone after the call anyway.

BTW: I'm pretty sure that can be done in a single call to the database combining the retrieval of companyuser with the deletion from CompanyUserAppAssingedFavorites.  @jjeroch:  It would be even better if we store the company-user as an Attribute in Keycloak and map it into the token so any application might access that value without going to the database.

2022-04-12 18:27 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            return Ok(await this.appsBusinessLogic.GetAllActiveAppsAsync(lang).ToListAsync().ConfigureAwait(false));
I checked the dotnet core 6 documentation. You may just return the IAsyncEnumerable as it is (no await, no ToListAsync) - the framework will make sure it is being streamed to the client

2022-04-12 18:27 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        public async Task<ActionResult<IEnumerable<Guid>>> GetAllFavouriteAppsForUser([FromRoute] Guid userId)
same as above: please use 'string' as type of parameter 'userId' for the reasons given above

2022-04-14 08:59 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +            var app = companyUser.Apps.FirstOrDefault(a => a.Id == appId);
@ntruchsess with your statement above 
`_@jjeroch: It would be even better if we store the company-user as an Attribute in Keycloak and map it into the token so any application might access that value without going to the database._`
I am guessing you are talking about the company_user_id given by us, right? Good idea. I am running a quick check later how many services this will impact. I believe its a small number and we can discuss jointly when such an improvement of the logic would make sense. Likely with the next "company user id" ticket

2022-04-19 15:23 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            _ = Guid.TryParse(subClaimValue, out var userId);
https://github.com/catenax-ng/product-portal-backend/pull/4/commits/1f99a887dce0ac9cb65c37f9e5a6210574aca0d4

2022-04-19 15:23 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
> +        public async Task RemoveFavouriteAppForUserAsync(Guid appId, Guid userId)
https://github.com/catenax-ng/product-portal-backend/pull/4/commits/1f99a887dce0ac9cb65c37f9e5a6210574aca0d4

2022-04-19 15:34 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            return Ok(await this.appsBusinessLogic.GetAllActiveAppsAsync(lang).ToListAsync().ConfigureAwait(false));
https://github.com/catenax-ng/product-portal-backend/pull/4/commits/afb9ebc010b9838d6366da826d8cbd25a770dde0
Although I am unsure whether this is a good idea because it's not obviously async anymore.

2022-04-20 14:56 UTC, ntruchsess requested changes

2022-04-20 14:56 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/IAppsBusinessLogic.cs
> +        public Task<IEnumerable<Guid>> GetAllFavouriteAppsForUserAsync(string userId);
return type should be `IAsyncEnumerable<Guid>`

2022-04-20 14:56 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        public ActionResult<IEnumerable<AppViewModel>> GetAllActiveApps([FromQuery] string? lang = null)
return type should be `IAsyncEnumerable<AppViewModel>`, return-type ActionResult seems no longer be required (see e.g. https://www.tpeczek.com/2021/07/aspnet-core-6-and-iasyncenumerable.html )

2022-04-20 14:56 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        public async Task<ActionResult<IEnumerable<Guid>>> GetAllFavouriteAppsForCurrentUserAsync()
return type should be `IAsyncEnumerable<Guid>`, return-type ActionResult seems no longer be required (see e.g. https://www.tpeczek.com/2021/07/aspnet-core-6-and-iasyncenumerable.html )

2022-04-20 15:45 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/IAppsBusinessLogic.cs
> +        public Task<IEnumerable<Guid>> GetAllFavouriteAppsForUserAsync(string userId);
https://github.com/catenax-ng/product-portal-backend/pull/4/commits/a4783f2608c8c19704456a3f4e8e5d17400bda62

2022-04-20 15:49 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        public ActionResult<IEnumerable<AppViewModel>> GetAllActiveApps([FromQuery] string? lang = null)
https://github.com/catenax-ng/product-portal-backend/pull/4/commits/a4783f2608c8c19704456a3f4e8e5d17400bda62

2022-04-20 15:52 UTC, ntruchsess approved these changes

2022-04-20 15:54 UTC, merged