CPLP-903 password reset error handling & user data
catenax-ng/product-portal-backend pull request #41
Opened 2022-05-10 11:15 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-903

2022-05-10 11:31 UTC, ntruchsess requested changes

2022-05-10 11:31 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        public async Task<IdpUser> GetIdpCategoryIdByUserId(string userId, string adminUserId)
declare userId (refering to companyUserId) as type Guid, not string. Also do this in the controller - the framework is capable to convert the path-parameter into Guid right from the beginning

2022-05-10 11:31 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +            return result;
no need to await the result, you are not making use of it within the method, just return the Task<IdpUser> that is being returned by SingleOrDefaultAsync(), it can be awaited where it is actually being used.

2022-05-10 11:31 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +                var idpUserName = await _logic.GetIdpCategoryIdByUserId(userId, adminuserId, tenant).ConfigureAwait(false);
please consolidate this logic within a single ResetUserPassword-method in the business-logic, the controller should just be a thin wrapper

2022-05-10 12:04 UTC, jjeroch reviewed
@qxz2mqe can you please add an information regarding the differentiation of the 3 possible error cases (for reverence have a look again into the story ticket). Which error code or message related to which scenario?

2022-05-10 13:15 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +                var idpUserName = await _logic.GetIdpCategoryIdByUserId(userId, adminuserId, tenant).ConfigureAwait(false);
fixed

2022-05-11 07:37 UTC, ntruchsess requested changes

2022-05-11 07:37 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        public async Task<StatusErrorCode> GetStatusCode(Guid companyUserId, string adminUserId, string tenant)
please do not put any dependencies to the http-protocol into the business-layer.
We have an Errorhandler in the middleware that does map Exceptions to Status-codes:
use the exceptions defined in https://github.com/catenax-ng/product-portal-backend/tree/main/src/framework/CatenaX.NetworkServices.Framework.ErrorHandling 
In addition to the (self-explenatory named) Exceptions in this package the Errorhandler will map ArgumentException to BAD_REQUEST and any other unknown Exception to 500 - SERVER_ERROR.
Not throwing an exception will result in StatusCode 200 OK

2022-05-11 07:37 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +                var result = await _logic.GetStatusCode(companyUserId, adminuserId, tenant).ConfigureAwait(false);
please to Exception-handling, logging and standard ErrorCode-mapping here, that is done implicitly by [the GeneralHttpErrorHandler (](https://github.com/catenax-ng/product-portal-backend/blob/main/src/framework/CatenaX.NetworkServices.Framework.ErrorHandling/GeneralHttpErrorHandler.cs) which is configured for this project.
Just call the businesslogic returning it's result.
(The other endpoints in the controller were created before introducing the GeneralHttpErrorHandler and need to be cleaned up as well in a separate Userstory)

2022-05-11 09:39 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        public async Task<StatusErrorCode> GetStatusCode(Guid companyUserId, string adminUserId, string tenant)
fixed

2022-05-11 09:40 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +                var result = await _logic.GetStatusCode(companyUserId, adminuserId, tenant).ConfigureAwait(false);
fixed

2022-05-11 10:15 UTC, ntruchsess requested changes

2022-05-11 10:15 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Enums/StatusErrorCode.cs
> +namespace CatenaX.NetworkServices.Administration.Service.Enums
please delete this class

2022-05-11 10:15 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        public async Task<bool> GetStatusCode(Guid companyUserId, string adminUserId, string tenant)
please use a more descriptive name like 'ExecutePasswordReset'

2022-05-11 10:15 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        public async Task<IActionResult> ResetUserPassword([FromRoute] string tenant, [FromRoute] Guid companyUserId)
change return type to Task<bool>

2022-05-11 10:15 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +            var result = await _logic.GetStatusCode(companyUserId, adminuserId, tenant).ConfigureAwait(false);
just return the result (Task<bool>), no need to await and map to Ok - this will be implictly done by the framework.

2022-05-11 11:06 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Enums/StatusErrorCode.cs
> +namespace CatenaX.NetworkServices.Administration.Service.Enums
fixed

2022-05-11 11:06 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +        public async Task<bool> GetStatusCode(Guid companyUserId, string adminUserId, string tenant)
fixed

2022-05-11 11:06 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +            var result = await _logic.GetStatusCode(companyUserId, adminuserId, tenant).ConfigureAwait(false);
fixed

2022-05-11 12:14 UTC, ntruchsess approved these changes

2022-05-11 12:14 UTC, merged