cplp-907 enhancing backend service for welcome email
catenax-ng/product-portal-backend pull request #45
Opened 2022-05-12 04:49 UTC by Akshay-Chaudhari-BMW

enhancing backend service for welcome email

2022-05-12 11:01 UTC, ntruchsess requested changes

2022-05-12 11:01 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +                     companyuser.Firstname + " " + companyuser.Lastname,
both FirstName and LastName may be null here

2022-05-12 11:02 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        (from invitation in _dbContext.Invitations
no need to join Invitations - you are not reading data from there and the referential integrity with invitations is taken care of by a database-constraint.

2022-05-13 05:52 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var userDetails = await _portalDBAccess.GetWelcomeEmailDataUntrackedAsync(applicationId).ToListAsync().ConfigureAwait(false);
removed ToListAsync()

2022-05-13 05:52 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    throw new ArgumentNullException("Email must not be empty");
resolved

2022-05-13 05:52 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +                     companyuser.Firstname + " " + companyuser.Lastname,
changed to nullable

2022-05-13 06:02 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        (from invitation in _dbContext.Invitations
resolved

2022-05-13 11:05 UTC, ntruchsess requested changes

2022-05-13 16:52 UTC, merged