CPLP-836 My Business Applications
catenax-ng/product-portal-backend pull request #54
Opened 2022-05-17 12:00 UTC by wira-mms

2022-05-17 16:13 UTC, ntruchsess requested changes

2022-05-17 16:13 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            if (string.IsNullOrWhiteSpace(userId))
No explicit mapping to Statuscodes - businesslogic should throw ArgumentException (which will be mapped to BadRequest with propper json error-response body by the GeneralHttpErrorHandler in the middleware).

2022-05-18 08:19 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            if (string.IsNullOrWhiteSpace(userId))
@ntruchsess pagination does not need to get considered in that scenario due to a very low amount of elements

2022-05-18 08:20 UTC, jjeroch commented
FYI I have run through the code as well, from what I could see I dont have any finding so far. I am planning to run a test later still before starting FE integration

2022-05-18 10:18 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +            if (string.IsNullOrWhiteSpace(userId))
https://github.com/catenax-ng/product-portal-backend/pull/54/commits/157492e5355f379831ce90e80dcc33b4ecc2faca

2022-05-18 15:20 UTC, ntruchsess commented
@jjeroch  : shall this endpoint implement pagination?

2022-05-18 15:33 UTC, ntruchsess requested changes

2022-05-18 15:33 UTC, ntruchsess commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        if (string.IsNullOrWhiteSpace(userId))
please move this check and throw of ArgumentException into method GetIamUserIdFromClaims(), then you can remove all this duplicated code

2022-05-18 15:48 UTC, wira-mms commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +        if (string.IsNullOrWhiteSpace(userId))
https://github.com/catenax-ng/product-portal-backend/pull/54/commits/d71c38334a0b481631d54a1572264f851de73e4a

2022-05-20 07:31 UTC, ntruchsess approved these changes

2022-05-20 07:31 UTC, merged