CPLP-999  password reset adapt  new logic
catenax-ng/product-portal-backend pull request #56
Opened 2022-05-18 06:42 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-999

2022-05-18 07:58 UTC, ntruchsess requested changes

2022-05-18 07:58 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            throw new ArgumentException($"Company ID  does not exist");
that message should give more information about the root cause - like '$"Cannot identify companyId: companyUserId {companyUserId} is not associated with the same company as adminUserId {adminUserId}"

2022-05-18 07:58 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
>                  .Where(iamUser => iamUser.UserEntityId == adminUserId)
That query certainly works. As an optimization I suggest to include the 'same company'-condition into the very first Where() so the overall result would be null if the condition is not met. That saves the additional steps of data-retrieval from the database (like idp-data) that would be redundant in this case. And don't forget the 'AsNoTracking()' as you are not going to modify the entities being returned.
e.g.:
            _dbContext.CompanyUsers
                .AsNoTracking()
                .Where(companyUser => 
                    companyUser.Id == companyUserId
                    && companyUser.Company!.CompanyUsers.Any(companyUser => companyUser.IamUser!.UserEntityId == adminUserId))
                .Select(companyUser => new IdpUser
                {
                    TargetIamUserId = companyUser.IamUser!.UserEntityId,
                    CompanyId = companyUser.CompanyId,
                    IdpName = companyUser.Company!.IdentityProviders
                        .Where(identityProvider => identityProvider.IdentityProviderCategoryId == IdentityProviderCategoryId.KEYCLOAK_SHARED)
                        .Select(identityProvider => identityProvider.IamIdentityProvider!.IamIdpAlias)
                        .SingleOrDefault()
                }).SingleOrDefaultAsync();

2022-05-18 10:12 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            throw new ArgumentException($"Company ID  does not exist");
fixed

2022-05-18 10:12 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
>                  .Where(iamUser => iamUser.UserEntityId == adminUserId)
fixed

2022-05-18 15:19 UTC, ntruchsess requested changes

2022-05-18 15:19 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    if (!string.IsNullOrWhiteSpace(idpUserName?.TargetIamUserId) && !string.IsNullOrWhiteSpace(idpUserName?.IdpName))
this if-statement should be executed before the call to CanResetPassword as the reset cannot be done if  targetIamUserid and/or idpName are not known so there is no point in updating the database in this case.

2022-05-19 04:12 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    if (!string.IsNullOrWhiteSpace(idpUserName?.TargetIamUserId) && !string.IsNullOrWhiteSpace(idpUserName?.IdpName))
fixed

2022-05-19 21:07 UTC, ntruchsess approved these changes

2022-05-19 21:07 UTC, merged