CPLP 459 confirm application request
catenax-ng/product-portal-backend pull request #62
Opened 2022-05-24 10:42 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-459

2022-05-24 20:31 UTC, ntruchsess requested changes

2022-05-24 20:31 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    _portalDBAccess.CreateCompanyUserAssignedRole(item.CompanyUserId, companyRoleIds[roleName]);
move to the first iteration if IAsyncEnumerable (line 380), make sure the companyRoleId that is required is read from the database before the IAsyncEnumerable is being retrieved.

2022-05-24 20:31 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                var application = await _portalDBAccess.GetCompanyApplicationAsync(applicationId).ConfigureAwait(false);
see comment above about retrieving application and company in single query

2022-05-24 20:31 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            throw new ArgumentException($"CompanyApplication {applicationId} is in wrong status");
as there is no return statement ArgumentException will allways be thrown if above code did run successful. Guess you couldn't test this as sending out the email did fail in your case.

2022-05-24 20:32 UTC, ntruchsess commented
@qxz2mqe : remark: I did resolve the conflicts with latest commits on main, so please pull your branch before starting to fix the remarks.

2022-05-25 10:04 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var result = (CompanyApplicationStatusId?)await _portalDBAccess.GetApplicationStatusUntrackedAsync(applicationId).ConfigureAwait(false);
Fixed

2022-05-25 10:04 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            bool success = false;
Fixed

2022-05-25 10:04 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                if (companyId == null)
Fixed

2022-05-25 10:04 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                string roleName = "IT Admin";
Fixed

2022-05-25 10:05 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                    _portalDBAccess.CreateCompanyUserAssignedRole(item.CompanyUserId, companyRoleIds[roleName]);
Fixed

2022-05-25 10:05 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +                var application = await _portalDBAccess.GetCompanyApplicationAsync(applicationId).ConfigureAwait(false);
Fixed

2022-05-25 19:26 UTC, ntruchsess requested changes

2022-05-25 19:26 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("application/{applicationId}/approveRequest")]
from my understanding this endpoint is called as last step in registration-process.
Instead of: /api/administration/user/application/{applicationId}/approveRequest
the path should rather be: /api/administration/registration/application/{applicationId}/approveRequest
Please move this endpoint to RegistrationController / RegistrationBusinessLogic

2022-05-27 19:24 UTC, ntruchsess approved these changes

2022-05-27 19:24 UTC, merged