CPLP-790 Connector SD factory registration
catenax-ng/product-portal-backend pull request #81
Opened 2022-06-08 08:52 UTC by wira-mms

2022-06-14 09:40 UTC, evegufy commented
@Phil91 Can you review this PR?

2022-06-14 10:46 UTC, jjeroch requested changes
Looks overall very good. I have only one comment regarding a inline comment for the hardcoded values

2022-06-14 14:25 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +            response = await httpClient.PostAsJsonAsync(_settings.SdFactoryUrl, requestModel);
Done

2022-06-14 14:26 UTC, Phil91 commented
> @Phil91 Can you review this PR?

I will

2022-06-14 19:09 UTC, Phil91 reviewed
@jjeroch i'd like to discuss the future usage of repositories in the solution. We currently do have two ways to use those: 

1. directly injecting and using the repository (e.g the usage of the [`IConnectorsRepository`](https://github.com/catenax-ng/product-portal-backend/blob/feature/CPLP-790-connector-sd-factory/src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs#:~:text=public%20ConnectorsBusinessLogic(-,IConnectorsRepository,-connectorsRepository%2C%20ICompanyRepository) )
2. injecting [`IPortalRepositories`](https://github.com/catenax-ng/product-portal-backend/blob/main/src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalRepositories.cs) and use the [`GetInstance`](https://github.com/catenax-ng/product-portal-backend/blob/main/src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs#:~:text=public%20RepositoryType-,GetInstance,-%3CRepositoryType%3E) implementation.

depending of the result of the discussion above, we would need to talk about the implementation of the transaction.

who would be the best person(s) for this discussion?

2022-06-15 05:35 UTC, Phil91 commented
> > @jjeroch i'd like to discuss the future usage of repositories in the solution. We currently do have two ways to use those:
> > 
> > 1. directly injecting and using the repository (e.g the usage of the [`IConnectorsRepository`](https://github.com/catenax-ng/product-portal-backend/blob/feature/CPLP-790-connector-sd-factory/src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs#:~:text=public%20ConnectorsBusinessLogic(-,IConnectorsRepository,-connectorsRepository%2C%20ICompanyRepository))
> > 2. injecting [`IPortalRepositories`](https://github.com/catenax-ng/product-portal-backend/blob/main/src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalRepositories.cs) and use the [`GetInstance`](https://github.com/catenax-ng/product-portal-backend/blob/main/src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs#:~:text=public%20RepositoryType-,GetInstance,-%3CRepositoryType%3E) implementation.
> > 
> > depending of the result of the discussion above, we would need to talk about the implementation of the transaction.
> > who would be the best person(s) for this discussion?
> 
> @Phil91 for a detailed discussion as well as open brainstorming, Norbert is ideal. Additionally please include Evelyn where possible (that topic can likely also result into a longer discussion, but it will be interesting for Evelyn to understand the ideas as well and see the pro and cons for the different approaches). As soon as the topic is further defined and a "preferred approach" is agreed, please also include Akshay and Majid to ensure that they understand the preferred approach Can you please keep me in loop, I will not be the right person to discuss this in detail neither I will be able to join all discussions, however if possible I like to stay in the loop since I am always interested in improvements

@jjeroch i will setup a meeting for further discussion with Norbert and Evelyn (you as optional as well). In my opinion i could approve this PR, we would then need an additional task to refactor the repository usage depending on which usage we decide to take. Whats your opinion on that?

2022-06-15 05:38 UTC, jjeroch commented
> > > @jjeroch i'd like to discuss the future usage of repositories in the solution. We currently do have two ways to use those:
> > > 
> > > 1. directly injecting and using the repository (e.g the usage of the [`IConnectorsRepository`](https://github.com/catenax-ng/product-portal-backend/blob/feature/CPLP-790-connector-sd-factory/src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs#:~:text=public%20ConnectorsBusinessLogic(-,IConnectorsRepository,-connectorsRepository%2C%20ICompanyRepository))
> > > 2. injecting [`IPortalRepositories`](https://github.com/catenax-ng/product-portal-backend/blob/main/src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalRepositories.cs) and use the [`GetInstance`](https://github.com/catenax-ng/product-portal-backend/blob/main/src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs#:~:text=public%20RepositoryType-,GetInstance,-%3CRepositoryType%3E) implementation.
> > > 
> > > depending of the result of the discussion above, we would need to talk about the implementation of the transaction.
> > > who would be the best person(s) for this discussion?
> > 
> > 
> > @Phil91 for a detailed discussion as well as open brainstorming, Norbert is ideal. Additionally please include Evelyn where possible (that topic can likely also result into a longer discussion, but it will be interesting for Evelyn to understand the ideas as well and see the pro and cons for the different approaches). As soon as the topic is further defined and a "preferred approach" is agreed, please also include Akshay and Majid to ensure that they understand the preferred approach Can you please keep me in loop, I will not be the right person to discuss this in detail neither I will be able to join all discussions, however if possible I like to stay in the loop since I am always interested in improvements
> 
> @jjeroch i will setup a meeting for further discussion with Norbert and Evelyn (you as optional as well). In my opinion i could approve this PR, we would then need an additional task to refactor the repository usage depending on which usage we decide to take. Whats your opinion on that?

@Phil91 fully agree

2022-06-15 05:47 UTC, Phil91 approved these changes

2022-06-15 05:48 UTC, merged