Cplp 464 get api to show app roles
catenax-ng/product-portal-backend pull request #82
Opened 2022-06-08 10:40 UTC by Akshay-Chaudhari-BMW

get api to show app roles

2022-06-08 21:35 UTC, jjeroch submitted a review, later dismissed

2022-06-08 21:35 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("app/{applicationId}/roles")]
@Akshay-Chaudhari-BMW  can you please change this to _appID_ instead of _applicationID_
"Application" is used for the company applications and app for the services. It would be confusing if we call it "applicationId"

2022-06-08 21:35 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +            _logic.GetClientRolesAsync(applicationId,languageShortName);
Same here, please dont call it applicationID

2022-06-09 04:31 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +            _logic.GetClientRolesAsync(applicationId,languageShortName);
replaced applicationId with appId

2022-06-09 04:31 UTC, Akshay-Chaudhari-BMW commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("app/{applicationId}/roles")]
replaced applicationId with appId

2022-06-10 08:50 UTC, evegufy requested changes
@Akshay-Chaudhari-BMW as just discussed: Please use the word 'app' everywhere where you really mean app and not application like in the sense of becoming member of the consortia.

2022-06-10 08:56 UTC, evegufy commented
@Akshay-Chaudhari-BMW @jjeroch If there are additional endpoints coming up for the administration of apps we may want to establish an own controller (and logic and so on) for Apps, not having it under the User controller anymore as it doesn't really fit there functionally (technically it's not an issue to leave it in the User Controller). I wouldn't do that for one endpoint, just to have that in mind for an upcoming user stories or sub tasks.

2022-06-10 09:30 UTC, Akshay-Chaudhari-BMW commented
> @Akshay-Chaudhari-BMW as just discussed: Please use the word 'app' everywhere where you really mean app and not application like in the sense of becoming member of the consortia.

@evegufy done

2022-06-10 10:03 UTC, evegufy approved these changes

2022-06-10 10:07 UTC, merged