feature/CPLP- 466  add role to user
catenax-ng/product-portal-backend pull request #83
Opened 2022-06-08 12:31 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-466

2022-06-09 14:55 UTC, jjeroch commented
@wira-mms  & @Phil91 can you please support on the code review? Let me know in case I should provide a functional explanation. Main review scope: anything coding wise which is not "best practice"?

2022-06-13 07:02 UTC, wira-mms commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
> +    Task<string> AddUserRole(Guid appId, UserRoleInfo userRoleInfo, string adminUserId);
You should add documentation comments in new code, mainly on public classes, methods and properties (and it would be great to also document every existing method that is touched in a PR). @jjeroch So far @Phil91 and me seem to be the only ones adding them, maybe you can enforce a rule from now on 😊

2022-06-13 07:04 UTC, wira-mms commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
> +        Task<CompanyIamUser> GetIdpUserById(Guid companyUserId, string adminUserId);
Please add new methods to the recently created repository structure.

2022-06-13 07:05 UTC, wira-mms commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyIamUser.cs
> +namespace CatenaX.NetworkServices.PortalBackend.DBAccess.Models
Use new namespace declaration with semicolon instead of braces.

2022-06-13 07:06 UTC, wira-mms commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        =>
Should stay at the end of the previous line.

2022-06-13 07:13 UTC, wira-mms commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyIamUser.cs
> +        public string? TargetIamUserId { get; set; }
Only make fields nullable if you're sure they should be optional by design. This seems like a necessary information for this model to be valid.

2022-06-13 07:15 UTC, wira-mms commented on src/administration/CatenaX.NetworkServices.Administration.Service/Models/UserRoleInfo.cs
> +        [JsonPropertyName("userEntityId")]
Empty lines between multi-line properties. Also, comments as I said before. You can get an example in marketplace App.Service!

2022-06-13 10:44 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
> +    Task<string> AddUserRole(Guid appId, UserRoleInfo userRoleInfo, string adminUserId);
fixed

2022-06-13 10:44 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
> +        Task<CompanyIamUser> GetIdpUserById(Guid companyUserId, string adminUserId);
fixed

2022-06-13 10:44 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyIamUser.cs
> +namespace CatenaX.NetworkServices.PortalBackend.DBAccess.Models
fixed

2022-06-13 10:45 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        =>
Not require because method is now moved to repository

2022-06-13 10:46 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyIamUser.cs
> +        public string? TargetIamUserId { get; set; }
Here TargetIamUserId Can be Null

2022-06-13 10:46 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Models/UserRoleInfo.cs
> +        [JsonPropertyName("userEntityId")]
fixed

2022-06-13 12:33 UTC, wira-mms commented on src/administration/CatenaX.NetworkServices.Administration.Service/Models/UserRoleInfo.cs
> +    /// <value></value>
Remove these value elements, please.

2022-06-13 13:22 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Models/UserRoleInfo.cs
> +    /// <value></value>
fixed

2022-06-13 13:23 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IUserRepository.cs
> +    Task<CompanyIamUser> GetIdpUserById(Guid companyUserId, string adminUserId);
fixed

2022-06-14 09:45 UTC, evegufy commented
@qxz2mqe can you please solve the conflicts?

2022-06-14 14:11 UTC, evegufy requested changes

2022-06-14 14:11 UTC, evegufy commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("users/{appId}/userrole")]
I think the route should reflect the relation to the GET endpoint, according to this, it should be called 'roles' not 'userrole'.
I think 'users' is not needed as we are already in the user Controller/Context of the Administration Service.

2022-06-15 04:24 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("users/{appId}/userrole")]
fixed

2022-06-15 04:25 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
> +    /// <param name="userRoleInfo">User and Role Infformation like Company and UserEntity Id and Role Name</param>
fixed

2022-06-15 04:25 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("users/{appId}/userrole")]
fixed

2022-06-15 04:25 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("users/{appId}/userrole")]
fixed

2022-06-15 04:25 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
> +    /// <param name="userRoleInfo">User and Role Infformation like Company and UserEntity Id and Role Name</param>
fixed

2022-06-15 07:29 UTC, jjeroch commented
As just discussed jointly with Majid and Evelyn: we kick out the 

- userEntityId

from the request body.

with that, the following validation is not needed anymore

`first, validate if userCompanyID and userEntityID are matching (use the iam_users table)if yes, proceedof no, stop and send an error to the FE (UserIds are not matching) `
With that the method/function to get the user_entity_id via the company_user_id should get used before calling keycloak

2022-06-15 09:07 UTC, evegufy commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("users/{appId}/userrole")]
Looks better, could you please add 'app' to that it is exactly like the GET endpoint 'app/{appId}/roles'

2022-06-15 09:08 UTC, evegufy commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
> +    /// <param name="userRoleInfo">User and Role Information like Company and UserEntity Id and Role Name</param>
I think 'UserEntity' should be removed here.

2022-06-15 09:11 UTC, evegufy requested changes

2022-06-15 09:32 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        [Route("users/{appId}/userrole")]
fixed

2022-06-15 09:32 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
> +    /// <param name="userRoleInfo">User and Role Information like Company and UserEntity Id and Role Name</param>
fixed

2022-06-15 09:42 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var result = await _portalRepositories.GetInstance<IUserRepository>().GetIdpUserByIdAsync(userRoleInfo.CompanyUserId, adminUserId).ConfigureAwait(false);
There are many examples in our  BusinessLogic class for example in GetOwnCompanyServiceAccountDetailsAsync,ResetOwnCompanyServiceAccountSecretAsync,GetOwnCompanyServiceAccountsDataAsync  etc in ServiceAccountBusinessLogic.

2022-06-15 10:50 UTC, evegufy commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var result = await _portalRepositories.GetInstance<IUserRepository>().GetIdpUserByIdAsync(userRoleInfo.CompanyUserId, adminUserId).ConfigureAwait(false);
Just because there are examples for this in other businesslogic files, doesn't mean we can't do better.
Variables can be named anything, yes, but at the same code can be more or less readable, I'd prefer more.

2022-06-15 10:57 UTC, evegufy commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            };
I googeled this indent issue which I noticed yesterday in our call, I don't think that formatting should be changed especially not in feature unrelated places and as this will come up again in the future with your  VS Code settings, I'd like to solve this now, please do the following:
1. Go to File | Preferences > Settings. Type "save" in the search box. In the list, choose Text Editor | Formatting. Untick the box for Editor: Format On Save
2. Remove re-add the indents from line 305-309
3. Save
4. Indents shouldn't be removed again

2022-06-15 10:59 UTC, evegufy commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            })
Re-add the indents from line 93-97

2022-06-15 11:00 UTC, evegufy requested changes

2022-06-15 11:00 UTC, evegufy commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            })
Re-add the indents from line 93-97

2022-06-15 11:26 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            var result = await _portalRepositories.GetInstance<IUserRepository>().GetIdpUserByIdAsync(userRoleInfo.CompanyUserId, adminUserId).ConfigureAwait(false);
fixed

2022-06-15 11:26 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            };
fixed

2022-06-15 11:26 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            })
fixed

2022-06-15 11:58 UTC, evegufy approved these changes

2022-06-15 11:59 UTC, merged