cplp -1040: handle user creation case for already existing user.
catenax-ng/product-portal-backend pull request #86
Opened 2022-06-09 10:55 UTC by Akshay-Chaudhari-BMW

handle user creation case for already existing user

2022-06-09 14:52 UTC, jjeroch commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                throw new ForbiddenException($"user {createdById} is already exist");
@Akshay-Chaudhari-BMW very simple change - can we please update the error message to "user {createdById} does already exist"

2022-06-10 04:05 UTC, Akshay-Chaudhari-BMW commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                throw new ForbiddenException($"user {createdById} is already exist");
resolved

2022-06-10 09:13 UTC, evegufy commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        public async Task<bool> IsUserAlreadyExist(string iamUserId) =>
I think 'IsUserExisting' as method name is better English.

2022-06-10 09:15 UTC, evegufy requested changes

2022-06-10 09:15 UTC, evegufy commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            var userCheck = await _portalDBAccess.IsUserAlreadyExist(createdById);
I think 'userExists' as variable name is more straight forward.

2022-06-10 10:09 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalBackendDBAccess.cs
> +        Task<bool> IsUserAlreadyExist(string iamUserId);
resolved

2022-06-10 10:09 UTC, Akshay-Chaudhari-BMW commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +        public async Task<bool> IsUserAlreadyExist(string iamUserId) =>
rename to IsUserExisting

2022-06-10 10:10 UTC, Akshay-Chaudhari-BMW commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            var userCheck = await _portalDBAccess.IsUserAlreadyExist(createdById);
resolved

2022-06-10 10:11 UTC, evegufy commented
@Akshay-Chaudhari-BMW Please resolve the conflicts, afterwards the merge is fine for me.
In general, please re-request the review once you made the changes, that makes the process easier with Github.
@jjeroch could you please also resolve your conversation?

2022-06-10 10:13 UTC, evegufy approved these changes

2022-06-10 10:14 UTC, merged