CPLP-1087 add swagger documentation
catenax-ng/product-portal-backend pull request #91
Opened 2022-06-14 14:21 UTC by Phil91

✅ Add Swagger documentation to Marketplace (App)
✅ Add Swagger documentation to Provisioning
✅ Add Swagger documentation to Registration
⬜ Add Swagger documentation to Administration
⬜ Add documentation to Confluence

2022-06-15 15:35 UTC, evegufy commented
@Phil91 Looks great! I had a quick look and think it's best to go over the descriptions in a quick call together on Monday. I'll send out a call. I hope it's okay for you that the PR remains open until then.

2022-06-15 16:19 UTC, jjeroch requested changes
I have added a few comments. I think it makes sense to also update it over the time :D I feel a bit bad about pushing all the comments into the pr. The implementation is good, actually everyone needs to take care as part of the normal development in each sprint that the error codes are well managed. We will implement this from now on :)

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="404">ServiceAccount not found in company of the user.</response>
"Record was not found. Service account is either not existing or not connected to the respective company."

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="400">User is not associated with any company.</response>
maybe this should be a 404 ?
"Record was not found. Service account is either not existing or not connected to the respective company."

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid Role.</response>
I think that should be a 404. Record not found - either user or role are not existing.

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns the emails of the new users.</response>
"User successfully created and invite email send"

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns a list of company user data for the current users company.</response>
What about a 404 message here as well "Record not found."

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">No company-user data found</response>
"Record not found. User id not existing."

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">User not found in company.</response>
"Record was not found. User is either not existing or not connected to the respective company."

2022-06-15 16:19 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Users have successfully been deleted.</response>
Do we also have a 404 here as well? In case the ID is not found an 404 error would be great, ideally the respective developer can enhance the service "Record was not found. User is either not existing or not connected to the respective company."

2022-06-15 18:11 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns <c>true</c> if the password was reset, <c>false</c> if it hasn't been reset.</response>
i agree, i need to check the explicit case. i would change it to a 400 if the result is false

2022-06-15 18:11 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns a list of company user data for the current users company.</response>
I think thats a good idea, we would need to implement that in the business logic. i'll take a look at that.

2022-06-15 18:21 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">no company-user data found for user</response>
changed

2022-06-15 18:21 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="403">invalid company User Id for user</response>
changed

2022-06-15 18:21 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Successfully added role.</response>
changed

2022-06-15 18:22 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/InvitationController.cs
> +    /// <response code="400">Either the email or the organisation name was empty.</response>
changed

2022-06-15 18:22 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ConnectorsController.cs
> +    /// <response code="400">Connector with provided ID does not exist.</response>
changed

2022-06-15 18:22 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// </response>
i totally agree

2022-06-15 18:23 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="404">ServiceAccount not found in company of the user.</response>
changed

2022-06-15 18:23 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="404">ServiceAccount not found in company of the user.</response>
changed

2022-06-15 18:23 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="404">ServiceAccount not found in company of the user.</response>
changed

2022-06-15 18:23 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="404">ServiceAccount not found in company of the user.</response>
changed

2022-06-15 18:24 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="400">User is not associated with any company.</response>
I agree, changed it.

2022-06-15 18:24 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid Role.</response>
changed as well :)

2022-06-15 18:24 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns the emails of the new users.</response>
changed

2022-06-15 18:24 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">User not found in company.</response>
changed

2022-06-17 05:51 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Users have successfully been deleted.</response>
Changed

2022-06-17 05:52 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns a list of company user data for the current users company.</response>
I'd like to discuss this one in the meeting on monday, because it could result in a general logic change

2022-06-17 05:52 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns <c>true</c> if the password was reset, <c>false</c> if it hasn't been reset.</response>
i changed the status code 200 description, in the buisiness logic is a check which throws an error if the reset failed - my bad sorry

2022-06-20 19:26 UTC, ntruchsess requested changes

2022-06-20 19:26 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Users have successfully been deleted.</response>
@jjeroch : the endpoints allows to delete multiple users at a time. How exactly should the endpoint behave in case only some of the id's are not existing while others are? The way this is implemented as of now would delete those users that do exist.
From my point of view a 404 result should only be returned if the logic first ensures all users actually do exist before starting to process the data. In this case I suggest no user should be deleted if only a single id is not existing.

2022-06-20 19:26 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid Role.</response>
I do not agreee 404 is the appropriate response for a post request that is going to create a resource if some input-parameters are invalid as the parameter does not refer to the location of the resource but to the content of the to-be-created resource. Returning 404 indicates a resource that is being requested does not exist but this POST-request is not requesting a resource to be returned it is requesting a resource to be created. It might be an appropriate answer if the input-parameter in question is mapped from the path as in this case the url-path would not be resolvable which is what 404 shall tell the frontend.

2022-06-22 04:58 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns the emails of the new users.</response>
@Phil91 can you please recheck, I dont see the change somehow

2022-06-22 05:17 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid Role.</response>
@ntruchsess the important question for me is "why is the user not created". We can have "missing parameter" (like role or email) and we can have an input value of a not existing role => which also leads to an error.
404 is a not found requested resource - you are right - dont we actually request a resource with this POST by fetching the role_id via the role name? Off course that resource is not inside the URI
When looking at some other APIs we do use the 404 code if a resource is not found (even if this resource is not a part of the URI) - from my point of view we need a clear or standardized implementation method and use it across all the APIs. Lets have a talk about this - maybe we get a quick catch up later today or tomorrow

2022-06-22 05:21 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns a list of company user data for the current users company.</response>
@ntruchsess technically right, but actually not possible right? Cause I cant call a Get/all/users endpoint and receiving an empty response. As a minimum I should be able to see my own user.
I would still tent to agree that we dont necessarily need an error code here since it wont be used for messages to the user or to monitor the same.

2022-06-22 05:27 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Users have successfully been deleted.</response>
Now we are at the same topic as above. We need to define first, if we allow a 404 in case the request id is not inside the api uri

Currently we only support to delete one specific user - that was the original API requirement. The logic regarding the deletion of multiple users gets a bot more tricky. I would actually just manage this in PI5, since we dont necessarily need that function. The initial tests and services will run with a single user deletion quite well

2022-06-30 06:19 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns the emails of the new users.</response>
somehow github mange to show the old code even when clicking on the file. If you click on the file make sure to select "Show all changes" in the left upper corner

![image](https://user-images.githubusercontent.com/7672600/176606362-552d5d11-4889-4cab-8b79-773f8c82073d.png)

2022-06-30 06:25 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            throw new NotFoundException($"user {iamAdminId} is not associated with any company");
removed

2022-07-01 08:57 UTC, Phil91 commented
@ntruchsess could you review this pr again, all discussed changes were made

2022-07-04 17:11 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid Role.</response>
kept 404 based on latest alignment (y)

2022-07-04 17:12 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Users have successfully been deleted.</response>
defined

2022-07-04 17:14 UTC, jjeroch commented
All open comments are resolved

2022-07-05 21:56 UTC, jjeroch requested changes

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    /// <response code="404">No company found for applicationId.</response>
404 error message update to "Application ID not found"

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    /// <response code="400">Either the CompanyApplication is not in status SUBMITTED or the BusinessPartnerNumber (bpn) for the given CompanyApplications company is empty.</response>
do we support here the 404 error as well
=> Application ID not found

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
> +    /// <response code="404">Record was not found. Possible reason: invalid user role, requester user invalid.</response>
@ntruchsess I am not sure about the 404 error here. Any opinion from your side?

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns the company user details.</response>
We are missing the 404 error for this scenario "User not found"

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">The app was not found.</response>
Something doesnt fit here. Row 173 is talking about app roles; but row 176 about password reset. Can you please recheck that?

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    /// <response code="400">No applicationId was set.</response>
its not wrong that we support the 400 error for the GET Api, BUT I realized that we do this for no other case. I would actually try to keep it in sync and either do it for all or for none.

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="403">Invalid or not existing user id.</response>
Typo? Isn't this a 404?

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/InvitationController.cs
> +    /// <response code="400">Missing mandatory input values (e.g. email, organization name, etc.)</response>
@ntruchsess  what about adding on top the 503 for the case of a portal/keycloak sync issue

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">User is either not existing.</response>
Correction of the response message needed "User not found"

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">User or user role not found.</response>
If the user role is not found we would go for a 400 error right? Cause we have an invalid request body.
@Phil91 can you please recheck if I mix it up currently?

404 => lets only cover there the "User not found" scenario

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <remarks>Example: POST: api/administration/user/app/D3B1ECA2-6148-4008-9E6C-C1C2AEA5C645/roles</remarks>
Ideally we also support the 503 error. Depending on the work for getting 503 enabled, I suggest we discuss if we put this in own defect tickets to handle the workload across the team

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ConnectorsController.cs
> +    /// <response code="400">Provided connector does not respect database constraints.</response>
Shall we standardize the description to something generic such as "Input values are insufficient. Either data are missing or in an incorrect form."

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">Cannot identify companyId or shared idp</response>
404 reason:
- user id not found

Regarding the "cannot identify CompanyID or SharedIdP" isnt this an 503 (internal error) ? I am actually not fully sure

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="403">Invalid or not existing user id.</response>
403 should be the forbidden access. I wouldn't expect here a message such as "invalid or not existing user id".
Can you please recheck?

2022-07-05 21:56 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <remarks>Example: PUT: api/administration/user/ownUser/ac1cf001-7fbc-1f2f-817f-bce0575a0011</remarks>
This API will need refactoring soon, since it was developed without a requirement ticket. We can keep the work here low and do changes basically when the refactoring is getting tackled

2022-07-05 21:56 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="404">App does not exist.</response>
Could that be actually "App Subscription Record not found. The subscription might not have the correct staus or the companyID is incorrect" ?

2022-07-05 21:56 UTC, jjeroch commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
>      /// <remarks>Example: PUT: /api/apps/D3B1ECA2-6148-4008-9E6C-C1C2AEA5C645/unsubscribe</remarks>
to be consistent, why not adding
`<response code="400">If sub claim is empty/invalid or user does not exist, or any other parameters are invalid.</response>`

2022-07-06 12:54 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
>      /// <remarks>Example: PUT: /api/apps/D3B1ECA2-6148-4008-9E6C-C1C2AEA5C645/unsubscribe</remarks>
changed it.

2022-07-06 12:54 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> +    /// <response code="404">App does not exist.</response>
The 404 is a database check if an app exists for the given id, i'd not change it.
The 400 can be thrown if the subscription state or company id is not correct, so i changed the description of that

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ConnectorsController.cs
> +    /// <response code="400">Provided connector does not respect database constraints.</response>
should we standardize it for all endpoint that return a 400? maybe we than could remove the comment and add it via a code convention.

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <remarks>Example: POST: api/administration/user/app/D3B1ECA2-6148-4008-9E6C-C1C2AEA5C645/roles</remarks>
i agree to add a 503 error here, i'm not fully sure what happens in the method itself.

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">User or user role not found.</response>
you got that right :)
I've changed it to just cover the "User not found" scenario with 404 and added a 400 response for the other case as well

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">User is either not existing.</response>
changed

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="403">Invalid or not existing user id.</response>
403 if the companyUserId which is found in the database doesn't match the given companyUserId
i've added a 404 as well

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    /// <response code="400">No applicationId was set.</response>
I've added the check to the other endpoints as well.

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">The app was not found.</response>
absolutly right, i updated the url

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="200">Returns the company user details.</response>
added.

2022-07-06 12:55 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +    /// <response code="400">Either the CompanyApplication is not in status SUBMITTED or the BusinessPartnerNumber (bpn) for the given CompanyApplications company is empty.</response>
added

2022-07-06 12:56 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
> -    /// <response code="400">If sub claim is empty/invalid.</response>
i updated the description here. For explanation:

400 if e.g. the user isn't authorized for the request.
404 not found if there is no specific app in the database for the given appId.

2022-07-06 12:56 UTC, Phil91 commented on src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
>      /// <remarks>Example: GET: /api/apps/D3B1ECA2-6148-4008-9E6C-C1C2AEA5C645</remarks>
changed

2022-07-06 12:56 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid role.</response>
changed

2022-07-06 12:57 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="403">Invalid or not existing user id.</response>
i changed the message, hope it fits now

2022-07-07 12:11 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">Cannot identify companyId or shared idp</response>
I will create a ticket and close the comment afterwards

2022-07-07 13:20 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">Cannot identify companyId or shared idp</response>
@jjeroch could you take a look at [CPLP-1170](https://jira.catena-x.net/browse/CPLP-1170), should include the needed changes.

2022-07-08 13:54 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="400">Invalid role.</response>
Ticket created for 500 and 503 error. Closing this comment :) https://jira.catena-x.net/browse/CPLP-1170

2022-07-11 09:41 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/InvitationController.cs
> +    /// <response code="400">Missing mandatory input values (e.g. email, organization name, etc.)</response>
should be already implemented: 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/94133633/178236220-95beb2f8-5f23-4b86-b1c9-5515373ef449.png">

2022-07-11 20:32 UTC, jjeroch commented
von meiner Seite gibt es keine Kommentare mehr - ich würde mergen.
@ntruchsess bist du auch schon durch?

2022-07-11 20:32 UTC, jjeroch commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
> +        /// <response code="404">Cannot identify companyId or shared idp</response>
Ticket updated and will get implemented in a own PR :) thanks

2022-07-14 07:19 UTC, ntruchsess approved these changes

2022-07-14 07:38 UTC, jjeroch approved these changes

2022-07-14 07:38 UTC, merged