feature/CPLP- 753 decline application request
catenax-ng/product-portal-backend pull request #92
Opened 2022-06-15 04:40 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-753

2022-06-15 15:32 UTC, evegufy commented
@Phil91 Could you please review? Thank you!

2022-06-17 11:18 UTC, Phil91 requested changes

2022-06-17 11:18 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +
Please remove the empty lines

2022-06-17 11:18 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +
Please add code documentation, for the swagger doc. You can see examples in this PR #91 or we can have a chat :)

2022-06-17 12:48 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalBackendDBAccess.cs
> +
fixed

2022-06-17 12:49 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
> +
fixed

2022-06-17 16:38 UTC, Phil91 approved these changes

2022-06-20 19:45 UTC, ntruchsess requested changes

2022-06-20 19:45 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        return true;
the call to _portalRepositories.SaveAsync() is missing here.

2022-06-20 19:45 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                  .AsNoTracking()
indentation shall be 4 chars

2022-06-20 19:45 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +            await foreach (var item in _dbContext.CompanyApplications
if multiple roles are configured we may get duplicate entries in the result-set. I probably makes sense to first query the primary-keys of the roles in question (user_role_id) then pass all those roles at once to the query that selects the user data.

2022-06-21 08:42 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        return true;
fixed

2022-06-21 08:42 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                  .AsNoTracking()
fixed

2022-06-21 08:42 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +            await foreach (var item in _dbContext.CompanyApplications
fixed

2022-06-21 09:39 UTC, ntruchsess approved these changes

2022-06-21 09:48 UTC, ntruchsess commented
coding-wise the PR is fine. @qxz2mqe as we have a new configuration-parameter did you take care of updating the secrets accoridingly?

2022-06-22 10:28 UTC, merged