CPLP-1103 save document content and status in the database
catenax-ng/product-portal-backend pull request #93
Opened 2022-06-17 10:33 UTC by Phil91

✅ Add Migration
✅ Add document repository
✅ Add document and status to db
✅ Add type validation (.pdf)

2022-06-20 18:06 UTC, ntruchsess requested changes

2022-06-20 18:06 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    await _documentRepository.CreateDocumentAsync(companyUserId, documentName, documentContent, hash, 0, documentTypeId).ConfigureAwait(false);
CreateDocument shall remain a synchronous call (see my comment above)

2022-06-20 18:06 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/Program.cs
> +builder.Services.AddTransient<IDocumentRepository, DocumentRepository>();
For consistency please add IDocumentRepository to PortalRepositories and inject IPortalRepositories calling GetInstance<IDocumentRepository>() in the business-code.

2022-06-20 18:33 UTC, ntruchsess commented
@Phil91 please be aware I did add 2 commits so please pull those before working on the review comments.

2022-06-20 18:39 UTC, ntruchsess requested changes

2022-06-20 18:39 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220617072031_CPLP-1103-AddDocumentStatusAndContent.cs
> +            migrationBuilder.AddColumn<int>(
I suppose we do not want existing database-entries to remain in status '0'? To overcome this as a last step before finally merging one manually can add some data-migration-code to the generated migration-class.

2022-06-21 06:28 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Document.cs
> +        DocumentStatusId = DocumentStatusId.PENDING;
done

2022-06-21 06:28 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Document.cs
> +    public Document(Guid id, string documentContent, string documenthash, string documentname, DateTimeOffset dateCreated, DocumentStatusId documentStatusId = DocumentStatusId.PENDING) : this()
i changed it

2022-06-21 06:29 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    await _documentRepository.CreateDocumentAsync(companyUserId, documentName, documentContent, hash, 0, documentTypeId).ConfigureAwait(false);
reverted it

2022-06-21 06:29 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/Program.cs
> +builder.Services.AddTransient<IDocumentRepository, DocumentRepository>();
done

2022-06-21 06:29 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/Migrations/20220617072031_CPLP-1103-AddDocumentStatusAndContent.cs
> +            migrationBuilder.AddColumn<int>(
valid point, i added an update statement to the migration

2022-06-21 07:59 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        var result = await _dbContext.Documents.AddAsync(
done

2022-06-21 09:10 UTC, ntruchsess requested changes

2022-06-21 09:10 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        private readonly IDocumentRepository _documentRepository;
I suggest this member should be IPortalRepositories. Call the factory-method within the business-method to avoid creation of redundant repository-instances in the constructor.
creating such repository-instance in the constructor is reasonable only if this repository is used in all business-methods.

2022-06-21 09:10 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    _documentRepository.CreateDocument(companyUserId, documentName, documentContent, hash, 0, documentTypeId);
the whole method must be migrated to use the repository pattern. Mixture of repository and PortalDBAccess-class will result in 2 different instances of DBContext (we did discuss this).

2022-06-21 09:16 UTC, ntruchsess requested changes

2022-06-21 09:16 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs
> +        else if (repositoryType == typeof(IDocumentRepository))
Please move this to line 31, then the types are in alphabetical order which makes it easier to see whether a particular type has already been included.

2022-06-21 09:41 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs
> +        else if (repositoryType == typeof(IDocumentRepository))
I moved it

2022-06-21 09:42 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    _documentRepository.CreateDocument(companyUserId, documentName, documentContent, hash, 0, documentTypeId);
sorry, didn't recognized that - fixed.

2022-06-21 16:31 UTC, ntruchsess requested changes

2022-06-21 16:31 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    var hash = BitConverter.ToString(md5.ComputeHash(ms)).Replace("-","").ToLower();
I did optimize the memory-footprint pre-allocating and re-using the MemoryStreams buffer. Please pull this change before proceeding with edits.
I noticed document-table still does have column 'oid' which initially was meant to be used for uploading the document as blob. This is now redundant as we store the document-content as bytea. Please remove that column 'oid'.
Then I suggest changing the type of column documenthash to byte[] (that is what the hash-value actually is) and do the conversion to hexadecimal string representation on the fly in the businesslogic that would return it to the frontend.
I also suggest changing the names of column 'documenthash' to 'document_hash' and 'documentname' to 'document_name'.

2022-06-22 06:30 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                    var hash = BitConverter.ToString(md5.ComputeHash(ms)).Replace("-","").ToLower();
I changed the data type and renamed the columns as well as removing the column 'oid'

2022-06-22 16:26 UTC, ntruchsess approved these changes

2022-06-22 16:27 UTC, merged