CPLP-1103 delete document
catenax-ng/product-portal-backend pull request #94
Opened 2022-06-17 11:34 UTC by Phil91

⬜ Add delete endpoint
⬜ Add Validation
⬜ Set document status & delete corresponding consent

2022-06-20 18:38 UTC, ntruchsess requested changes

2022-06-23 16:34 UTC, ntruchsess requested changes

2022-06-23 16:34 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
> +        var document = await documentRepository.GetDocumentByIdAsync(documentId);
create a query that returns the document and the iamuserid in a single call to the database.

2022-06-23 16:34 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        document.DocumentStatusId = DocumentStatusId.INACTIVE;
setting the document_status_id belongs to the layer of business-logic

2022-06-23 16:34 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +    public async Task<Document?> GetDocumentByIdAsync(Guid documentId) =>
no need to await the task - just return it (removing the 'async' from the signature)

2022-06-23 16:34 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        await _dbContext.SaveChangesAsync();
this call to SaveChangesAsync is both redundant and violates the pattern of calling the final save on the PortalRepositories class by the businesslogic.

2022-06-23 16:34 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        _dbContext.Consents.RemoveRange(consents);
Consents are not to be deleted but set to status INACTIVE. See e.g. https://github.com/catenax-ng/product-portal-backend/blob/18f6dec7fd97a5ac840d459175175f8d7f319f59/src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs#L345
Please clarify with @jjeroch what is actually intended here.

2022-06-24 09:07 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        document.DocumentStatusId = DocumentStatusId.INACTIVE;
moved it

2022-06-24 09:08 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +    public async Task<Document?> GetDocumentByIdAsync(Guid documentId) =>
removed

2022-06-24 09:08 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        await _dbContext.SaveChangesAsync();
it was duplicated as well - removed it

2022-06-24 09:10 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        _dbContext.Consents.RemoveRange(consents);
@jjeroch could you verify if its correct to set the ConsentStatusId to inactive instead of deleting it completly from the database
@ntruchsess i changed the logic

2022-06-24 09:10 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
> +        var document = await documentRepository.GetDocumentByIdAsync(documentId);
i changed the implementation to a partial update

2022-06-24 18:50 UTC, ntruchsess approved these changes
I did some cleanup, removing the wrapping 'Tuple' and joining the three queries (documentStatus, ConsentIds, User) into a single one.
@Phil91 please double-check

2022-06-27 08:07 UTC, ntruchsess commented
@Phil91 is this ready to merge or do you need to make further adjustments after having merged main?

2022-06-27 08:09 UTC, merged