Get document endpoints
catenax-ng/product-portal-backend pull request #97
Opened 2022-06-21 07:58 UTC by Phil91

Depending on #93

2022-06-21 09:14 UTC, ntruchsess requested changes

2022-06-21 09:14 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs
> +        else if (repositoryType == typeof(IDocumentRepository))
Please move this to line 31, then the types are in alphabetical order which makes it easier to see whether a particular type has already been included.

2022-06-23 16:45 UTC, ntruchsess requested changes

2022-06-23 16:45 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
> +        return (document.Documentname, Convert.FromBase64String(document.DocumentContent));
document-content is byte[] not base64

2022-06-23 16:45 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        await this._dbContext.Documents.SingleOrDefaultAsync(x => x.Id == documentId);
no need to await this task here, just return it (removing 'async' from the signature)

2022-06-23 16:45 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            return (document.DocumentName, Convert.FromBase64String(document.DocumentContent));
document is byte[] not base64

2022-06-23 16:45 UTC, ntruchsess commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            var document = await documentRepository.GetDocumentByIdAsync(documentId).ConfigureAwait(false);
as the document-content is rather huge it seems to be more efficient to first query the iamuserid that is assigned to this document to do the authorization-check first, then retrieve the content in separate query. Even if this is an additional call it saves a lot of resources if an attacker would try to DDos this service.

2022-06-24 06:48 UTC, Phil91 commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
> +        return (document.Documentname, Convert.FromBase64String(document.DocumentContent));
fixed

2022-06-24 06:48 UTC, Phil91 commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/DocumentRepository.cs
> +        await this._dbContext.Documents.SingleOrDefaultAsync(x => x.Id == documentId);
fixed

2022-06-24 06:49 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            return (document.DocumentName, Convert.FromBase64String(document.DocumentContent));
fixed

2022-06-24 06:49 UTC, Phil91 commented on src/registration/CatenaX.NetworkServices.Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            var document = await documentRepository.GetDocumentByIdAsync(documentId).ConfigureAwait(false);
good idea. i changed it

2022-06-24 20:48 UTC, ntruchsess approved these changes
@Phil91 I did some cleanup, please double-check. Feel free to merge if your are fine with my changes

2022-06-27 06:13 UTC, Phil91 commented
> @Phil91 I did some cleanup, please double-check. Feel free to merge if your are fine with my changes

Looks fine by me. Will merge it

2022-06-27 06:14 UTC, merged