feature/CPLP- 461 get application by company name
catenax-ng/product-portal-backend pull request #99
Opened 2022-06-23 06:00 UTC by qxz2mqe

https://jira.catena-x.net/browse/CPLP-461

2022-06-23 17:51 UTC, ntruchsess requested changes

2022-06-23 17:51 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            15,
we want to avoid literals within the sourcecode - maxPageSize should remain configurable.

2022-06-23 17:51 UTC, ntruchsess commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +               .AsNoTracking()
indentation  shall be 4 characters not 7

2022-06-23 17:51 UTC, ntruchsess commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                        .Skip(skip)
indentation shall be 4 characters, not 8

2022-06-24 05:07 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            15,
fixed

2022-06-24 05:08 UTC, qxz2mqe commented on src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +               .AsNoTracking()
fixed

2022-06-24 05:08 UTC, qxz2mqe commented on src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                        .Skip(skip)
fixed

2022-06-24 21:37 UTC, ntruchsess approved these changes
@qxz2mqe : I figured out the case-insensitive search: column-type 'citext' did not work as it is not known to the database-driver, but there is EF.Functions.ILike, which is the case-insensitive version of like which does work fine on postgresql :-)

2022-06-24 21:49 UTC, merged